#!/usr/bin/env python3
"""Regenerate WordRank's ordered word list: the engine's frequency table and
its spelling vocabulary, which are the same fact.

The list started as Norvig's `count_1w.txt` top 20k (Google Web Trillion Word
Corpus, public domain), scraped from web text. Web text carries typos, so the
raw list holds `teh` at 19395 and `definately` at 19107. A vocabulary that
contains `teh` can never correct `teh`, which is why unit 1 of
`specs/autocorrect-parity.md` regenerates the list instead of reusing it.

Construction, measured against the frozen 434-pair typo corpus:

    head    the first HEAD_RANKS words, trusted as typed
    tail    the rest, kept when Webster's Second International or the proper
            names list also has it
    names   the proper names list, appended; a name the vocabulary lacks is
            corrected toward a common word, which is the most expensive
            miscorrection there is
    texting TextingLexicon's modern words, appended after the ranked words

Webster's Second International 1934 is `/usr/share/dict/words` on macOS
(`web2`), public domain. It predates `email` and `online`, which is why the
head is trusted rather than filtered: those words are common enough to sit
well inside it, and every typo the corpus carries sits in the tail.

Run from the repo root:

    python3 engine/tools/gen-wordrank.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / "engine" / "Sources" / "TypingEngine" / "WordRank.swift"
LEXICON = ROOT / "engine" / "Sources" / "TypingEngine" / "TextingLexicon.swift"
WEBSTER = Path("/usr/share/dict/words")
PROPER = Path("/usr/share/dict/propernames")

# Every typo in the frozen corpus that reached the raw list sits past 4000,
# and every modern word the corpus needs sits well before it. 8000 leaves
# room on both sides of that boundary.
HEAD_RANKS = 8000


def norvig_words() -> list:
    """The current list, which is the only copy of count_1w.txt in the repo."""
    source = TARGET.read_text()
    match = re.search(r'private static let list = "([^"]*)"', source, re.S)
    if not match:
        sys.exit("WordRank.swift no longer holds a `list` literal")
    return match.group(1).split()


def texting_words() -> list:
    return sorted(set(re.findall(r'"([a-z0-9]+)"', LEXICON.read_text())))


def build() -> list:
    words = norvig_words()
    webster = {line.strip().lower() for line in WEBSTER.read_text().splitlines()}
    proper = {line.strip().lower() for line in PROPER.read_text().splitlines()}
    real = webster | proper
    kept = words[:HEAD_RANKS] + [w for w in words[HEAD_RANKS:] if w in real]
    seen = set(kept)
    appended = [w for w in sorted(proper) + texting_words() if w not in seen]
    for w in appended:
        seen.add(w)
    return kept + appended


def main():
    for source in (WEBSTER, PROPER):
        if not source.exists():
            sys.exit(f"{source} is missing; this script runs on macOS")
    words = build()
    body = " ".join(words)
    TARGET.write_text(f'''// GENERATED by engine/tools/gen-wordrank.py -- do not hand-edit.
// Norvig's count_1w.txt (Google Web Trillion Word Corpus, public domain) for
// the order, filtered past rank {HEAD_RANKS} against Webster's Second
// International 1934 (/usr/share/dict/words, public domain) so web-text typos
// like "teh" leave the vocabulary, then widened with TextingLexicon.
// {len(words)} words.

/// The engine's ordered word list. Position is English word frequency, and
/// membership is "this is a word", which are one fact held in one place:
/// `CorrectionEngine` breaks candidate ties by rank and
/// `DictionarySpellChecker` draws candidates from the same list.
public enum WordRank {{
    static let ranked: [String: Int] = {{
        var table: [String: Int] = [:]
        table.reserveCapacity({len(words)})
        for (i, w) in list.split(separator: " ").enumerated() {{
            table[String(w)] = i + 1
        }}
        return table
    }}()

    /// Rank of a word, case-insensitive; unknown words sink to Int.max.
    public static func rank(_ word: String) -> Int {{
        ranked[word.lowercased()] ?? Int.max
    }}

    /// True when the list holds the word, case-insensitively. An unknown word
    /// is the one a correction is offered for.
    public static func isKnown(_ word: String) -> Bool {{
        ranked[word.lowercased()] != nil
    }}

    private static let list = "{body}"
}}
''')
    print(f"WordRank: {len(words)} words (head {HEAD_RANKS}, "
          f"filtered tail, texting lexicon appended)")


if __name__ == "__main__":
    main()
