#!/usr/bin/env python3
"""Regenerate WordRank: the engine's word list, which is both its spelling
vocabulary and its frequency order.

The list is the Android Open Source Project's LatinIME English dictionary
(`engine/tools/vendor/en_wordlist.combined.gz`, Apache-2.0, 165,544 words).
Each entry carries its own casing and a 0-255 frequency, so one file answers
both questions the engine asks: "is this a word" and "how common is it".

The list this replaced was Norvig's `count_1w.txt` top 20k, scraped from web
text, which held `teh` at rank 19395 and `definately` at 19107. A vocabulary
that contains `teh` can never correct `teh`.

Run from the repo root:

    python3 engine/tools/gen-wordrank.py
"""
import gzip
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / "engine" / "Sources" / "TypingEngine" / "WordRank.swift"
LEXICON = ROOT / "engine" / "Sources" / "TypingEngine" / "TextingLexicon.swift"
SOURCE = ROOT / "engine" / "tools" / "vendor" / "en_wordlist.combined.gz"

ENTRY = re.compile(r"^ word=([^,]+),f=(\d+)")


def aosp_words() -> list:
    """(word, frequency) in the list's own casing, most frequent first."""
    entries = []
    with gzip.open(SOURCE, "rt", encoding="utf-8") as handle:
        for line in handle:
            match = ENTRY.match(line)
            if match:
                entries.append((match.group(1), int(match.group(2))))
    if not entries:
        sys.exit(f"{SOURCE} held no word entries")
    # Frequency first, then alphabetical, so the order is total and a
    # regeneration reproduces the file byte for byte.
    entries.sort(key=lambda pair: (-pair[1], pair[0]))
    return entries


def texting_words() -> list:
    return sorted(set(re.findall(r'"([a-z0-9]+)"', LEXICON.read_text())))


def build() -> list:
    words = [word for word, _ in aosp_words()]
    seen = {w.lower() for w in words}
    # The texting lexicon is modern slang the 2014 list never had. It lands
    # last: these words are never corrected away, and rank only breaks ties.
    return words + [w for w in texting_words() if w not in seen]


def main():
    if not SOURCE.exists():
        sys.exit(f"{SOURCE} is missing; see engine/tools/vendor/NOTICE")
    words = build()
    body = " ".join(words)
    TARGET.write_text(f'''// GENERATED by engine/tools/gen-wordrank.py -- do not hand-edit.
// The Android Open Source Project's LatinIME English dictionary, ordered by
// its own frequency, then the shipped TextingLexicon. Apache-2.0; provenance
// and limits in engine/tools/vendor/NOTICE. {len(words)} words.

/// The engine's word list. Position is English word frequency, and membership
/// is "this is a word", which are one fact held in one place: `CorrectionEngine`
/// breaks candidate ties by rank and `DictionarySpellChecker` draws candidates
/// from the same list.
///
/// Lookups are case-insensitive. Each entry keeps the casing the dictionary
/// gives it, so a candidate comes back as `iPhone` rather than `iphone`.
public enum WordRank {{
    private static let entries: [(word: String, lower: String)] = {{
        list.split(separator: " ").map {{
            (word: String($0), lower: $0.lowercased())
        }}
    }}()

    static let ranked: [String: Int] = {{
        var table: [String: Int] = [:]
        table.reserveCapacity({len(words)})
        for (i, entry) in entries.enumerated() where table[entry.lower] == nil {{
            table[entry.lower] = i + 1
        }}
        return table
    }}()

    /// The dictionary's own casing for a word, keyed by its lowercase form.
    static let cased: [String: String] = {{
        var table: [String: String] = [:]
        table.reserveCapacity({len(words)})
        for entry in entries where table[entry.lower] == nil {{
            table[entry.lower] = entry.word
        }}
        return table
    }}()

    /// A word the candidate scan reads, with the set of letters it uses.
    struct Entry {{
        let lower: String
        /// Bit per a-z. Two words within `d` edits differ by at most `2 * d`
        /// letters, so comparing masks rejects most of the list for the cost
        /// of one xor, before the distance matrix runs.
        let letters: UInt32
    }}

    /// Words grouped by length. A candidate scan reads only the few lengths
    /// inside its edit budget, so it never walks all {len(words)} entries.
    static let byLength: [Int: [Entry]] = {{
        var seen = Set<String>(minimumCapacity: {len(words)})
        var table: [Int: [Entry]] = [:]
        for entry in entries where seen.insert(entry.lower).inserted {{
            table[entry.lower.count, default: []].append(
                Entry(lower: entry.lower, letters: letterMask(entry.lower)))
        }}
        return table
    }}()

    static func letterMask(_ word: String) -> UInt32 {{
        var mask: UInt32 = 0
        for scalar in word.unicodeScalars where scalar.value >= 97 && scalar.value <= 122 {{
            mask |= 1 << (scalar.value - 97)
        }}
        return mask
    }}

    /// Lowercased words grouped by their first two characters. Completions
    /// read one bucket per keystroke instead of the whole list.
    static let byPrefix: [String: [String]] = {{
        var table: [String: [String]] = [:]
        for entry in entries where entry.lower.count >= 2 {{
            let key = String(entry.lower.prefix(2))
            if table[key]?.last == entry.lower {{ continue }}
            table[key, default: []].append(entry.lower)
        }}
        return table
    }}()

    /// Rank of a word, case-insensitive; unknown words sink to Int.max.
    public static func rank(_ word: String) -> Int {{
        ranked[word.lowercased()] ?? Int.max
    }}

    /// True when the list holds the word, case-insensitively. An unknown word
    /// is the one a correction is offered for.
    public static func isKnown(_ word: String) -> Bool {{
        ranked[word.lowercased()] != nil
    }}

    private static let list = "{body}"
}}
''')
    print(f"WordRank: {len(words)} words from the AOSP list plus the texting lexicon")


if __name__ == "__main__":
    main()
