/// Curated emoji catalog (~300 entries). GENERATED-STYLE data file: one
/// entry per line, lowercase names, space-separated keywords. Grow the long
/// tail here without structural change; keep emoji unique (tested).

public enum EmojiCategory: String, CaseIterable, Sendable {
    case smileys, people, animals, food, activity, travel, objects, symbols
}

public struct EmojiEntry: Sendable {
    public let emoji: String
    public let name: String
    public let keywords: String
    public let category: EmojiCategory

    init(_ emoji: String, _ name: String, _ keywords: String, _ category: EmojiCategory) {
        self.emoji = emoji
        self.name = name
        self.keywords = keywords
        self.category = category
    }
}

public enum EmojiCatalog {
    public static func entries(in category: EmojiCategory) -> [EmojiEntry] {
        entries.filter { $0.category == category }
    }

    public static let entries: [EmojiEntry] = [
        // Smileys
        EmojiEntry("😀", "grinning face", "smile happy", .smileys),
        EmojiEntry("😃", "grinning face with big eyes", "smile happy joy", .smileys),
        EmojiEntry("😄", "grinning face with smiling eyes", "smile happy laugh", .smileys),
        EmojiEntry("😁", "beaming face", "grin smile teeth", .smileys),
        EmojiEntry("😆", "grinning squinting face", "laugh haha lol", .smileys),
        EmojiEntry("😅", "grinning face with sweat", "phew relief laugh", .smileys),
        EmojiEntry("🤣", "rolling on the floor laughing", "rofl lol funny", .smileys),
        EmojiEntry("😂", "face with tears of joy", "lol laugh cry funny", .smileys),
        EmojiEntry("🙂", "slightly smiling face", "smile ok", .smileys),
        EmojiEntry("😉", "winking face", "wink flirt", .smileys),
        EmojiEntry("😊", "smiling face with smiling eyes", "blush happy warm", .smileys),
        EmojiEntry("😇", "smiling face with halo", "angel innocent", .smileys),
        EmojiEntry("🥰", "smiling face with hearts", "love adore crush", .smileys),
        EmojiEntry("😍", "heart eyes", "love crush adore", .smileys),
        EmojiEntry("🤩", "star struck", "wow amazing eyes", .smileys),
        EmojiEntry("😘", "face blowing a kiss", "kiss love", .smileys),
        EmojiEntry("😗", "kissing face", "kiss", .smileys),
        EmojiEntry("😋", "face savoring food", "yum tasty delicious", .smileys),
        EmojiEntry("😛", "face with tongue", "tongue silly", .smileys),
        EmojiEntry("😜", "winking face with tongue", "silly joke crazy", .smileys),
        EmojiEntry("🤪", "zany face", "crazy wild silly", .smileys),
        EmojiEntry("🤑", "money mouth face", "rich dollar cash", .smileys),
        EmojiEntry("🤗", "hugging face", "hug embrace", .smileys),
        EmojiEntry("🤭", "face with hand over mouth", "oops giggle", .smileys),
        EmojiEntry("🤫", "shushing face", "quiet shh secret", .smileys),
        EmojiEntry("🤔", "thinking face", "hmm think wonder", .smileys),
        EmojiEntry("🫡", "saluting face", "salute respect", .smileys),
        EmojiEntry("😐", "neutral face", "meh blank", .smileys),
        EmojiEntry("😑", "expressionless face", "blank meh", .smileys),
        EmojiEntry("🙄", "face with rolling eyes", "eyeroll whatever", .smileys),
        EmojiEntry("😬", "grimacing face", "awkward yikes", .smileys),
        EmojiEntry("😮‍💨", "face exhaling", "sigh phew relief", .smileys),
        EmojiEntry("🤥", "lying face", "pinocchio lie", .smileys),
        EmojiEntry("😌", "relieved face", "calm content", .smileys),
        EmojiEntry("😔", "pensive face", "sad thoughtful", .smileys),
        EmojiEntry("😪", "sleepy face", "tired sleep", .smileys),
        EmojiEntry("😴", "sleeping face", "zzz sleep tired", .smileys),
        EmojiEntry("😷", "face with medical mask", "sick mask ill", .smileys),
        EmojiEntry("🤒", "face with thermometer", "sick fever ill", .smileys),
        EmojiEntry("🤕", "face with head bandage", "hurt injured", .smileys),
        EmojiEntry("🤢", "nauseated face", "sick gross vomit", .smileys),
        EmojiEntry("🤮", "face vomiting", "sick throw up", .smileys),
        EmojiEntry("🥵", "hot face", "heat sweating", .smileys),
        EmojiEntry("🥶", "cold face", "freezing frozen", .smileys),
        EmojiEntry("😵‍💫", "face with spiral eyes", "dizzy woozy", .smileys),
        EmojiEntry("🤯", "exploding head", "mind blown shocked", .smileys),
        EmojiEntry("🥳", "partying face", "party celebrate birthday", .smileys),
        EmojiEntry("😎", "smiling face with sunglasses", "cool shades", .smileys),
        EmojiEntry("🤓", "nerd face", "glasses geek", .smileys),
        EmojiEntry("😕", "confused face", "puzzled", .smileys),
        EmojiEntry("😟", "worried face", "concern anxious", .smileys),
        EmojiEntry("😢", "crying face", "sad tear", .smileys),
        EmojiEntry("😭", "loudly crying face", "sob bawl sad", .smileys),
        EmojiEntry("😤", "face with steam from nose", "frustrated huff", .smileys),
        EmojiEntry("😠", "angry face", "mad grr", .smileys),
        EmojiEntry("😡", "pouting face", "rage furious angry", .smileys),
        EmojiEntry("🤬", "face with symbols on mouth", "swear curse angry", .smileys),
        EmojiEntry("😱", "face screaming in fear", "scream shocked scared", .smileys),
        EmojiEntry("😨", "fearful face", "scared afraid", .smileys),
        EmojiEntry("😰", "anxious face with sweat", "nervous worried", .smileys),
        EmojiEntry("🥺", "pleading face", "puppy eyes beg cute", .smileys),
        EmojiEntry("😳", "flushed face", "blush embarrassed", .smileys),
        EmojiEntry("🥴", "woozy face", "drunk tipsy", .smileys),
        EmojiEntry("😈", "smiling face with horns", "devil evil", .smileys),
        EmojiEntry("💀", "skull", "dead death lol", .smileys),
        EmojiEntry("🤡", "clown face", "circus joke", .smileys),
        EmojiEntry("💩", "pile of poo", "poop crap", .smileys),
        EmojiEntry("👻", "ghost", "boo spooky halloween", .smileys),
        EmojiEntry("👽", "alien", "ufo space", .smileys),
        EmojiEntry("🤖", "robot", "bot machine", .smileys),

        // People
        EmojiEntry("👋", "waving hand", "wave hello bye hi", .people),
        EmojiEntry("🤚", "raised back of hand", "stop hand", .people),
        EmojiEntry("✋", "raised hand", "stop high five", .people),
        EmojiEntry("🖖", "vulcan salute", "spock star trek", .people),
        EmojiEntry("👌", "ok hand", "okay perfect", .people),
        EmojiEntry("🤌", "pinched fingers", "italian chef", .people),
        EmojiEntry("✌️", "victory hand", "peace two", .people),
        EmojiEntry("🤞", "crossed fingers", "luck hope", .people),
        EmojiEntry("🤟", "love you gesture", "rock love", .people),
        EmojiEntry("🤘", "sign of the horns", "rock metal", .people),
        EmojiEntry("🤙", "call me hand", "shaka hang loose", .people),
        EmojiEntry("👈", "backhand index pointing left", "point left", .people),
        EmojiEntry("👉", "backhand index pointing right", "point right", .people),
        EmojiEntry("👆", "backhand index pointing up", "point up", .people),
        EmojiEntry("👇", "backhand index pointing down", "point down", .people),
        EmojiEntry("👍", "thumbs up", "like yes approve good", .people),
        EmojiEntry("👎", "thumbs down", "dislike no bad", .people),
        EmojiEntry("✊", "raised fist", "power solidarity", .people),
        EmojiEntry("👊", "oncoming fist", "punch bro fist bump", .people),
        EmojiEntry("👏", "clapping hands", "clap applause bravo", .people),
        EmojiEntry("🙌", "raising hands", "hooray praise yay", .people),
        EmojiEntry("🫶", "heart hands", "love", .people),
        EmojiEntry("👐", "open hands", "hug", .people),
        EmojiEntry("🤝", "handshake", "deal agreement", .people),
        EmojiEntry("🙏", "folded hands", "please pray thanks", .people),
        EmojiEntry("💪", "flexed biceps", "muscle strong gym", .people),
        EmojiEntry("🖕", "middle finger", "rude", .people),
        EmojiEntry("✍️", "writing hand", "write pen", .people),
        EmojiEntry("💅", "nail polish", "sassy manicure", .people),
        EmojiEntry("🤳", "selfie", "phone photo", .people),
        EmojiEntry("👀", "eyes", "look watching sus", .people),
        EmojiEntry("👁️", "eye", "look see", .people),
        EmojiEntry("🧠", "brain", "smart mind", .people),
        EmojiEntry("🦷", "tooth", "dentist", .people),
        EmojiEntry("👶", "baby", "infant child", .people),
        EmojiEntry("🧒", "child", "kid", .people),
        EmojiEntry("👦", "boy", "kid", .people),
        EmojiEntry("👧", "girl", "kid", .people),
        EmojiEntry("🧑", "person", "adult", .people),
        EmojiEntry("👨", "man", "male adult", .people),
        EmojiEntry("👩", "woman", "female adult", .people),
        EmojiEntry("🧓", "older person", "elderly", .people),
        EmojiEntry("👮", "police officer", "cop law", .people),
        EmojiEntry("👷", "construction worker", "builder hard hat", .people),
        EmojiEntry("💂", "guard", "british soldier", .people),
        EmojiEntry("🕵️", "detective", "spy sleuth", .people),
        EmojiEntry("🧑‍⚕️", "health worker", "doctor nurse", .people),
        EmojiEntry("🧑‍🎓", "student", "graduate school", .people),
        EmojiEntry("🧑‍🏫", "teacher", "school professor", .people),
        EmojiEntry("🧑‍🍳", "cook", "chef kitchen", .people),
        EmojiEntry("🧑‍💻", "technologist", "developer programmer coder", .people),
        EmojiEntry("🧑‍🚀", "astronaut", "space nasa", .people),
        EmojiEntry("🧑‍🚒", "firefighter", "fire rescue", .people),
        EmojiEntry("🦸", "superhero", "hero cape", .people),
        EmojiEntry("🧙", "mage", "wizard magic", .people),
        EmojiEntry("🧛", "vampire", "dracula halloween", .people),
        EmojiEntry("🧟", "zombie", "undead halloween", .people),
        EmojiEntry("💃", "woman dancing", "dance salsa", .people),
        EmojiEntry("🕺", "man dancing", "dance disco", .people),
        EmojiEntry("🚶", "person walking", "walk stroll", .people),
        EmojiEntry("🏃", "person running", "run jog sprint", .people),
        EmojiEntry("🧍", "person standing", "stand", .people),
        EmojiEntry("🫂", "people hugging", "hug embrace comfort", .people),
        EmojiEntry("👪", "family", "family home", .people),

        // Animals
        EmojiEntry("🐱", "cat face", "kitten pet meow", .animals),
        EmojiEntry("🐶", "dog face", "puppy pet woof", .animals),
        EmojiEntry("🐭", "mouse face", "rodent", .animals),
        EmojiEntry("🐹", "hamster", "pet rodent", .animals),
        EmojiEntry("🐰", "rabbit face", "bunny", .animals),
        EmojiEntry("🦊", "fox", "sly", .animals),
        EmojiEntry("🐻", "bear", "grizzly", .animals),
        EmojiEntry("🐼", "panda", "china bamboo", .animals),
        EmojiEntry("🐨", "koala", "australia", .animals),
        EmojiEntry("🐯", "tiger face", "stripes", .animals),
        EmojiEntry("🦁", "lion", "king mane", .animals),
        EmojiEntry("🐮", "cow face", "moo", .animals),
        EmojiEntry("🐷", "pig face", "oink", .animals),
        EmojiEntry("🐸", "frog", "toad ribbit", .animals),
        EmojiEntry("🐵", "monkey face", "ape", .animals),
        EmojiEntry("🙈", "see no evil monkey", "hide embarrassed", .animals),
        EmojiEntry("🙉", "hear no evil monkey", "ears", .animals),
        EmojiEntry("🙊", "speak no evil monkey", "secret oops", .animals),
        EmojiEntry("🐔", "chicken", "hen cluck", .animals),
        EmojiEntry("🐧", "penguin", "antarctica", .animals),
        EmojiEntry("🐦", "bird", "tweet", .animals),
        EmojiEntry("🦅", "eagle", "bird america", .animals),
        EmojiEntry("🦆", "duck", "quack", .animals),
        EmojiEntry("🦉", "owl", "wise night bird", .animals),
        EmojiEntry("🦄", "unicorn", "magic horn", .animals),
        EmojiEntry("🐴", "horse face", "pony", .animals),
        EmojiEntry("🐝", "honeybee", "bee buzz", .animals),
        EmojiEntry("🐛", "caterpillar", "bug insect", .animals),
        EmojiEntry("🦋", "butterfly", "pretty insect", .animals),
        EmojiEntry("🐌", "snail", "slow", .animals),
        EmojiEntry("🐞", "lady beetle", "ladybug insect", .animals),
        EmojiEntry("🐜", "ant", "insect", .animals),
        EmojiEntry("🕷️", "spider", "web halloween", .animals),
        EmojiEntry("🐢", "turtle", "slow tortoise", .animals),
        EmojiEntry("🐍", "snake", "serpent hiss", .animals),
        EmojiEntry("🦎", "lizard", "gecko reptile", .animals),
        EmojiEntry("🐙", "octopus", "tentacles sea", .animals),
        EmojiEntry("🦑", "squid", "sea", .animals),
        EmojiEntry("🦐", "shrimp", "prawn sea", .animals),
        EmojiEntry("🦀", "crab", "sea pinch", .animals),
        EmojiEntry("🐡", "blowfish", "puffer sea", .animals),
        EmojiEntry("🐠", "tropical fish", "sea aquarium", .animals),
        EmojiEntry("🐟", "fish", "sea", .animals),
        EmojiEntry("🐬", "dolphin", "sea flipper", .animals),
        EmojiEntry("🐳", "spouting whale", "sea big", .animals),
        EmojiEntry("🦈", "shark", "jaws sea", .animals),
        EmojiEntry("🐊", "crocodile", "alligator", .animals),
        EmojiEntry("🐘", "elephant", "trunk big", .animals),
        EmojiEntry("🦒", "giraffe", "tall neck", .animals),
        EmojiEntry("🦘", "kangaroo", "australia jump", .animals),
        EmojiEntry("🐑", "ewe", "sheep wool", .animals),
        EmojiEntry("🐐", "goat", "greatest", .animals),
        EmojiEntry("🐺", "wolf", "howl", .animals),
        EmojiEntry("🦇", "bat", "vampire night", .animals),
        EmojiEntry("🐾", "paw prints", "tracks pet", .animals),
        EmojiEntry("🌵", "cactus", "desert plant", .animals),
        EmojiEntry("🌲", "evergreen tree", "pine forest", .animals),
        EmojiEntry("🌴", "palm tree", "beach tropical", .animals),
        EmojiEntry("🌱", "seedling", "sprout plant grow", .animals),
        EmojiEntry("🌿", "herb", "leaf plant", .animals),
        EmojiEntry("🍀", "four leaf clover", "luck irish", .animals),
        EmojiEntry("🍁", "maple leaf", "canada fall autumn", .animals),
        EmojiEntry("🌸", "cherry blossom", "flower spring pink", .animals),
        EmojiEntry("🌹", "rose", "flower love", .animals),
        EmojiEntry("🌻", "sunflower", "flower yellow", .animals),
        EmojiEntry("🌈", "rainbow", "pride colorful weather", .animals),
        EmojiEntry("☀️", "sun", "sunny weather bright", .animals),
        EmojiEntry("🌙", "crescent moon", "night sky", .animals),
        EmojiEntry("⭐", "star", "night favorite", .animals),
        EmojiEntry("⚡", "high voltage", "lightning zap bolt", .animals),
        EmojiEntry("🔥", "fire", "flame hot lit", .animals),
        EmojiEntry("❄️", "snowflake", "cold winter snow", .animals),
        EmojiEntry("☔", "umbrella with rain drops", "rain weather", .animals),
        EmojiEntry("🌊", "water wave", "ocean sea surf", .animals),

        // Food
        EmojiEntry("🍏", "green apple", "fruit", .food),
        EmojiEntry("🍎", "red apple", "fruit teacher", .food),
        EmojiEntry("🍐", "pear", "fruit", .food),
        EmojiEntry("🍊", "tangerine", "orange fruit", .food),
        EmojiEntry("🍋", "lemon", "sour fruit", .food),
        EmojiEntry("🍌", "banana", "fruit", .food),
        EmojiEntry("🍉", "watermelon", "fruit summer", .food),
        EmojiEntry("🍇", "grapes", "fruit wine", .food),
        EmojiEntry("🍓", "strawberry", "fruit berry", .food),
        EmojiEntry("🫐", "blueberries", "fruit berry", .food),
        EmojiEntry("🍒", "cherries", "fruit", .food),
        EmojiEntry("🍑", "peach", "fruit butt", .food),
        EmojiEntry("🥭", "mango", "fruit tropical", .food),
        EmojiEntry("🍍", "pineapple", "fruit tropical", .food),
        EmojiEntry("🥥", "coconut", "tropical", .food),
        EmojiEntry("🥝", "kiwi fruit", "fruit", .food),
        EmojiEntry("🍅", "tomato", "vegetable", .food),
        EmojiEntry("🥑", "avocado", "guacamole toast", .food),
        EmojiEntry("🥦", "broccoli", "vegetable", .food),
        EmojiEntry("🥕", "carrot", "vegetable", .food),
        EmojiEntry("🌽", "ear of corn", "vegetable maize", .food),
        EmojiEntry("🌶️", "hot pepper", "spicy chili", .food),
        EmojiEntry("🥔", "potato", "vegetable", .food),
        EmojiEntry("🍞", "bread", "loaf toast", .food),
        EmojiEntry("🥐", "croissant", "french pastry", .food),
        EmojiEntry("🥨", "pretzel", "snack", .food),
        EmojiEntry("🧀", "cheese wedge", "dairy", .food),
        EmojiEntry("🥚", "egg", "breakfast", .food),
        EmojiEntry("🍳", "cooking", "fried egg breakfast", .food),
        EmojiEntry("🥓", "bacon", "breakfast pork", .food),
        EmojiEntry("🥞", "pancakes", "breakfast syrup", .food),
        EmojiEntry("🧇", "waffle", "breakfast", .food),
        EmojiEntry("🍗", "poultry leg", "chicken drumstick", .food),
        EmojiEntry("🍖", "meat on bone", "bbq", .food),
        EmojiEntry("🌭", "hot dog", "sausage", .food),
        EmojiEntry("🍔", "hamburger", "burger fast food", .food),
        EmojiEntry("🍟", "french fries", "fast food", .food),
        EmojiEntry("🍕", "pizza", "slice italian", .food),
        EmojiEntry("🥪", "sandwich", "lunch", .food),
        EmojiEntry("🌮", "taco", "mexican", .food),
        EmojiEntry("🌯", "burrito", "mexican wrap", .food),
        EmojiEntry("🥗", "green salad", "healthy", .food),
        EmojiEntry("🍝", "spaghetti", "pasta italian", .food),
        EmojiEntry("🍜", "steaming bowl", "ramen noodles soup", .food),
        EmojiEntry("🍣", "sushi", "japanese fish", .food),
        EmojiEntry("🍤", "fried shrimp", "tempura", .food),
        EmojiEntry("🍚", "cooked rice", "asian", .food),
        EmojiEntry("🍙", "rice ball", "onigiri japanese", .food),
        EmojiEntry("🥟", "dumpling", "gyoza potsticker", .food),
        EmojiEntry("🍦", "soft ice cream", "dessert cone", .food),
        EmojiEntry("🍧", "shaved ice", "dessert", .food),
        EmojiEntry("🍨", "ice cream", "dessert", .food),
        EmojiEntry("🍩", "doughnut", "donut dessert", .food),
        EmojiEntry("🍪", "cookie", "dessert biscuit", .food),
        EmojiEntry("🎂", "birthday cake", "celebrate dessert", .food),
        EmojiEntry("🍰", "shortcake", "cake dessert slice", .food),
        EmojiEntry("🧁", "cupcake", "dessert", .food),
        EmojiEntry("🍫", "chocolate bar", "candy dessert", .food),
        EmojiEntry("🍬", "candy", "sweet", .food),
        EmojiEntry("🍭", "lollipop", "candy sweet", .food),
        EmojiEntry("🍿", "popcorn", "movie snack", .food),
        EmojiEntry("☕", "hot beverage", "coffee tea", .food),
        EmojiEntry("🍵", "teacup without handle", "tea green", .food),
        EmojiEntry("🥤", "cup with straw", "soda drink", .food),
        EmojiEntry("🧋", "bubble tea", "boba drink", .food),
        EmojiEntry("🍺", "beer mug", "drink pint", .food),
        EmojiEntry("🍻", "clinking beer mugs", "cheers drink", .food),
        EmojiEntry("🥂", "clinking glasses", "cheers champagne toast", .food),
        EmojiEntry("🍷", "wine glass", "drink red", .food),
        EmojiEntry("🍸", "cocktail glass", "martini drink", .food),
        EmojiEntry("🥃", "tumbler glass", "whiskey drink", .food),

        // Activity
        EmojiEntry("⚽", "soccer ball", "football sport", .activity),
        EmojiEntry("🏀", "basketball", "sport hoops", .activity),
        EmojiEntry("🏈", "american football", "sport nfl", .activity),
        EmojiEntry("⚾", "baseball", "sport", .activity),
        EmojiEntry("🥎", "softball", "sport", .activity),
        EmojiEntry("🎾", "tennis", "sport racket", .activity),
        EmojiEntry("🏐", "volleyball", "sport", .activity),
        EmojiEntry("🏉", "rugby football", "sport", .activity),
        EmojiEntry("🎱", "pool 8 ball", "billiards", .activity),
        EmojiEntry("🏓", "ping pong", "table tennis", .activity),
        EmojiEntry("🏸", "badminton", "sport", .activity),
        EmojiEntry("🥅", "goal net", "sport", .activity),
        EmojiEntry("⛳", "flag in hole", "golf", .activity),
        EmojiEntry("🏹", "bow and arrow", "archery", .activity),
        EmojiEntry("🎣", "fishing pole", "fish hobby", .activity),
        EmojiEntry("🥊", "boxing glove", "fight sport", .activity),
        EmojiEntry("🥋", "martial arts uniform", "karate judo", .activity),
        EmojiEntry("🎽", "running shirt", "marathon", .activity),
        EmojiEntry("🛹", "skateboard", "skate", .activity),
        EmojiEntry("⛸️", "ice skate", "skating winter", .activity),
        EmojiEntry("🎿", "skis", "skiing winter", .activity),
        EmojiEntry("🛷", "sled", "winter snow", .activity),
        EmojiEntry("🏂", "snowboarder", "winter snow", .activity),
        EmojiEntry("🏋️", "person lifting weights", "gym workout", .activity),
        EmojiEntry("🤸", "person cartwheeling", "gymnastics", .activity),
        EmojiEntry("🤽", "person playing water polo", "sport swim", .activity),
        EmojiEntry("🏊", "person swimming", "swim pool", .activity),
        EmojiEntry("🏄", "person surfing", "surf wave", .activity),
        EmojiEntry("🚴", "person biking", "bicycle cycling", .activity),
        EmojiEntry("🧗", "person climbing", "rock climb", .activity),
        EmojiEntry("🤺", "person fencing", "sword sport", .activity),
        EmojiEntry("🏇", "horse racing", "jockey", .activity),
        EmojiEntry("🧘", "person in lotus position", "yoga meditate zen", .activity),
        EmojiEntry("🎯", "bullseye", "target darts", .activity),
        EmojiEntry("🎮", "video game", "controller gaming", .activity),
        EmojiEntry("🕹️", "joystick", "arcade gaming", .activity),
        EmojiEntry("🎲", "game die", "dice board game", .activity),
        EmojiEntry("♟️", "chess pawn", "chess strategy", .activity),
        EmojiEntry("🧩", "puzzle piece", "jigsaw", .activity),
        EmojiEntry("🎳", "bowling", "strike pins", .activity),
        EmojiEntry("🎪", "circus tent", "carnival", .activity),
        EmojiEntry("🎭", "performing arts", "theater drama masks", .activity),
        EmojiEntry("🎨", "artist palette", "paint art", .activity),
        EmojiEntry("🎬", "clapper board", "movie film action", .activity),
        EmojiEntry("🎤", "microphone", "sing karaoke", .activity),
        EmojiEntry("🎧", "headphone", "music listen", .activity),
        EmojiEntry("🎼", "musical score", "music sheet", .activity),
        EmojiEntry("🎹", "musical keyboard", "piano music", .activity),
        EmojiEntry("🥁", "drum", "music beat", .activity),
        EmojiEntry("🎷", "saxophone", "jazz music", .activity),
        EmojiEntry("🎺", "trumpet", "music brass", .activity),
        EmojiEntry("🎸", "guitar", "music rock", .activity),
        EmojiEntry("🎻", "violin", "music strings", .activity),
        EmojiEntry("🎰", "slot machine", "casino gamble", .activity),
        EmojiEntry("🎉", "party popper", "celebrate congrats tada", .activity),
        EmojiEntry("🎊", "confetti ball", "celebrate party", .activity),
        EmojiEntry("🎈", "balloon", "party birthday", .activity),
        EmojiEntry("🎁", "wrapped gift", "present birthday", .activity),
        EmojiEntry("🏆", "trophy", "win champion award", .activity),
        EmojiEntry("🥇", "1st place medal", "gold winner first", .activity),
        EmojiEntry("🥈", "2nd place medal", "silver second", .activity),
        EmojiEntry("🥉", "3rd place medal", "bronze third", .activity),

        // Travel
        EmojiEntry("🚗", "automobile", "car drive", .travel),
        EmojiEntry("🚕", "taxi", "cab", .travel),
        EmojiEntry("🚙", "sport utility vehicle", "suv car", .travel),
        EmojiEntry("🚌", "bus", "transit", .travel),
        EmojiEntry("🚎", "trolleybus", "transit", .travel),
        EmojiEntry("🏎️", "racing car", "f1 fast", .travel),
        EmojiEntry("🚓", "police car", "cop", .travel),
        EmojiEntry("🚑", "ambulance", "emergency", .travel),
        EmojiEntry("🚒", "fire engine", "truck emergency", .travel),
        EmojiEntry("🚐", "minibus", "van", .travel),
        EmojiEntry("🚚", "delivery truck", "shipping", .travel),
        EmojiEntry("🚜", "tractor", "farm", .travel),
        EmojiEntry("🏍️", "motorcycle", "bike", .travel),
        EmojiEntry("🛵", "motor scooter", "vespa", .travel),
        EmojiEntry("🚲", "bicycle", "bike cycle", .travel),
        EmojiEntry("🛴", "kick scooter", "scoot", .travel),
        EmojiEntry("🚨", "police car light", "siren emergency alert", .travel),
        EmojiEntry("🚔", "oncoming police car", "cop", .travel),
        EmojiEntry("🚖", "oncoming taxi", "cab", .travel),
        EmojiEntry("🚡", "aerial tramway", "cable car", .travel),
        EmojiEntry("🚠", "mountain cableway", "gondola", .travel),
        EmojiEntry("🚝", "monorail", "train", .travel),
        EmojiEntry("🚄", "high speed train", "bullet rail", .travel),
        EmojiEntry("🚅", "bullet train", "rail japan", .travel),
        EmojiEntry("🚈", "light rail", "train", .travel),
        EmojiEntry("🚂", "locomotive", "steam train", .travel),
        EmojiEntry("🚆", "train", "rail", .travel),
        EmojiEntry("🚇", "metro", "subway underground", .travel),
        EmojiEntry("🚊", "tram", "streetcar", .travel),
        EmojiEntry("✈️", "airplane", "flight fly plane", .travel),
        EmojiEntry("🛫", "airplane departure", "takeoff flight", .travel),
        EmojiEntry("🛬", "airplane arrival", "landing flight", .travel),
        EmojiEntry("🪂", "parachute", "skydive", .travel),
        EmojiEntry("💺", "seat", "airplane chair", .travel),
        EmojiEntry("🚁", "helicopter", "chopper", .travel),
        EmojiEntry("🚀", "rocket", "space launch ship", .travel),
        EmojiEntry("🛸", "flying saucer", "ufo alien", .travel),
        EmojiEntry("⛵", "sailboat", "boat sea", .travel),
        EmojiEntry("🚤", "speedboat", "boat", .travel),
        EmojiEntry("🛳️", "passenger ship", "cruise boat", .travel),
        EmojiEntry("⚓", "anchor", "boat sea", .travel),
        EmojiEntry("⛽", "fuel pump", "gas station", .travel),
        EmojiEntry("🚧", "construction", "barrier roadwork", .travel),
        EmojiEntry("🚦", "vertical traffic light", "signal", .travel),
        EmojiEntry("🗺️", "world map", "travel geography", .travel),
        EmojiEntry("🗿", "moai", "easter island statue", .travel),
        EmojiEntry("🗽", "statue of liberty", "new york america", .travel),
        EmojiEntry("🗼", "tokyo tower", "japan", .travel),
        EmojiEntry("🏰", "castle", "palace fairytale", .travel),
        EmojiEntry("🏯", "japanese castle", "japan", .travel),
        EmojiEntry("🏟️", "stadium", "arena sports", .travel),
        EmojiEntry("🎡", "ferris wheel", "carnival fair", .travel),
        EmojiEntry("🎢", "roller coaster", "theme park", .travel),
        EmojiEntry("⛲", "fountain", "park water", .travel),
        EmojiEntry("⛱️", "umbrella on ground", "beach", .travel),
        EmojiEntry("🏖️", "beach with umbrella", "sand vacation", .travel),
        EmojiEntry("🏝️", "desert island", "tropical vacation", .travel),
        EmojiEntry("⛰️", "mountain", "peak hike", .travel),
        EmojiEntry("🏔️", "snow capped mountain", "peak winter", .travel),
        EmojiEntry("🌋", "volcano", "eruption lava", .travel),
        EmojiEntry("🏕️", "camping", "tent outdoors", .travel),
        EmojiEntry("🏠", "house", "home", .travel),
        EmojiEntry("🏢", "office building", "work city", .travel),
        EmojiEntry("🏥", "hospital", "medical", .travel),
        EmojiEntry("🏦", "bank", "money", .travel),
        EmojiEntry("🏫", "school", "education", .travel),
        EmojiEntry("⛪", "church", "religion", .travel),
        EmojiEntry("🕌", "mosque", "religion", .travel),
        EmojiEntry("🌃", "night with stars", "city skyline", .travel),
        EmojiEntry("🌅", "sunrise", "morning dawn", .travel),
        EmojiEntry("🌇", "sunset", "dusk evening", .travel),

        // Objects
        EmojiEntry("⌚", "watch", "time wrist", .objects),
        EmojiEntry("📱", "mobile phone", "iphone cell", .objects),
        EmojiEntry("💻", "laptop", "computer macbook", .objects),
        EmojiEntry("⌨️", "keyboard", "typing computer", .objects),
        EmojiEntry("🖥️", "desktop computer", "imac monitor", .objects),
        EmojiEntry("🖨️", "printer", "print office", .objects),
        EmojiEntry("🖱️", "computer mouse", "click", .objects),
        EmojiEntry("💽", "computer disk", "minidisc", .objects),
        EmojiEntry("💾", "floppy disk", "save retro", .objects),
        EmojiEntry("💿", "optical disk", "cd dvd", .objects),
        EmojiEntry("📷", "camera", "photo picture", .objects),
        EmojiEntry("📸", "camera with flash", "photo selfie", .objects),
        EmojiEntry("📹", "video camera", "record film", .objects),
        EmojiEntry("📺", "television", "tv screen", .objects),
        EmojiEntry("📻", "radio", "music retro", .objects),
        EmojiEntry("🎙️", "studio microphone", "podcast record", .objects),
        EmojiEntry("⏰", "alarm clock", "wake time", .objects),
        EmojiEntry("⏳", "hourglass not done", "time waiting", .objects),
        EmojiEntry("📡", "satellite antenna", "signal dish", .objects),
        EmojiEntry("🔋", "battery", "power charge", .objects),
        EmojiEntry("🔌", "electric plug", "power outlet", .objects),
        EmojiEntry("💡", "light bulb", "idea bright", .objects),
        EmojiEntry("🔦", "flashlight", "torch light", .objects),
        EmojiEntry("🕯️", "candle", "light flame", .objects),
        EmojiEntry("🗑️", "wastebasket", "trash garbage", .objects),
        EmojiEntry("🛢️", "oil drum", "barrel", .objects),
        EmojiEntry("💸", "money with wings", "spend cash", .objects),
        EmojiEntry("💵", "dollar banknote", "money cash", .objects),
        EmojiEntry("💰", "money bag", "rich cash", .objects),
        EmojiEntry("💳", "credit card", "payment", .objects),
        EmojiEntry("💎", "gem stone", "diamond jewel", .objects),
        EmojiEntry("⚖️", "balance scale", "justice law weigh", .objects),
        EmojiEntry("🔧", "wrench", "tool fix", .objects),
        EmojiEntry("🔨", "hammer", "tool build", .objects),
        EmojiEntry("⚙️", "gear", "settings cog", .objects),
        EmojiEntry("🧲", "magnet", "attract", .objects),
        EmojiEntry("🔫", "water pistol", "gun squirt", .objects),
        EmojiEntry("💣", "bomb", "explosive", .objects),
        EmojiEntry("🔪", "kitchen knife", "cut chef", .objects),
        EmojiEntry("🗡️", "dagger", "knife sword", .objects),
        EmojiEntry("🛡️", "shield", "protect defense", .objects),
        EmojiEntry("🚬", "cigarette", "smoking", .objects),
        EmojiEntry("⚰️", "coffin", "funeral death", .objects),
        EmojiEntry("🔮", "crystal ball", "fortune magic", .objects),
        EmojiEntry("📿", "prayer beads", "religion", .objects),
        EmojiEntry("💈", "barber pole", "haircut", .objects),
        EmojiEntry("🔭", "telescope", "stars astronomy", .objects),
        EmojiEntry("🔬", "microscope", "science lab", .objects),
        EmojiEntry("🕳️", "hole", "void", .objects),
        EmojiEntry("💊", "pill", "medicine drug", .objects),
        EmojiEntry("💉", "syringe", "shot vaccine needle", .objects),
        EmojiEntry("🌡️", "thermometer", "temperature fever", .objects),
        EmojiEntry("🧬", "dna", "genetics science", .objects),
        EmojiEntry("🦠", "microbe", "germ virus bacteria", .objects),
        EmojiEntry("🧴", "lotion bottle", "soap", .objects),
        EmojiEntry("🧹", "broom", "sweep clean", .objects),
        EmojiEntry("🧺", "basket", "laundry", .objects),
        EmojiEntry("🧻", "roll of paper", "toilet paper", .objects),
        EmojiEntry("🛁", "bathtub", "bath clean", .objects),
        EmojiEntry("🔑", "key", "lock unlock", .objects),
        EmojiEntry("🚪", "door", "exit entrance", .objects),
        EmojiEntry("🪑", "chair", "seat furniture", .objects),
        EmojiEntry("🛏️", "bed", "sleep furniture", .objects),
        EmojiEntry("🧸", "teddy bear", "toy plush", .objects),
        EmojiEntry("🖼️", "framed picture", "art painting", .objects),
        EmojiEntry("🛍️", "shopping bags", "buy retail", .objects),
        EmojiEntry("🎓", "graduation cap", "school degree", .objects),
        EmojiEntry("🧢", "billed cap", "hat baseball", .objects),
        EmojiEntry("👑", "crown", "king queen royal", .objects),
        EmojiEntry("💍", "ring", "wedding engagement", .objects),
        EmojiEntry("👓", "glasses", "spectacles", .objects),
        EmojiEntry("🕶️", "sunglasses", "cool shades", .objects),
        EmojiEntry("👔", "necktie", "shirt formal", .objects),
        EmojiEntry("👕", "t shirt", "clothes", .objects),
        EmojiEntry("👖", "jeans", "pants clothes", .objects),
        EmojiEntry("🧥", "coat", "jacket clothes", .objects),
        EmojiEntry("🧦", "socks", "clothes", .objects),
        EmojiEntry("👗", "dress", "clothes", .objects),
        EmojiEntry("👟", "running shoe", "sneaker shoes", .objects),
        EmojiEntry("🥾", "hiking boot", "shoes outdoors", .objects),
        EmojiEntry("👠", "high heeled shoe", "heels shoes", .objects),
        EmojiEntry("🎒", "backpack", "school bag", .objects),
        EmojiEntry("👜", "handbag", "purse bag", .objects),
        EmojiEntry("🧳", "luggage", "suitcase travel", .objects),
        EmojiEntry("📚", "books", "read library study", .objects),
        EmojiEntry("📖", "open book", "read", .objects),
        EmojiEntry("📝", "memo", "note write", .objects),
        EmojiEntry("✏️", "pencil", "write draw", .objects),
        EmojiEntry("🖊️", "pen", "write", .objects),
        EmojiEntry("📌", "pushpin", "pin tack", .objects),
        EmojiEntry("📎", "paperclip", "attach", .objects),
        EmojiEntry("✂️", "scissors", "cut", .objects),
        EmojiEntry("📏", "straight ruler", "measure", .objects),
        EmojiEntry("📦", "package", "box shipping", .objects),
        EmojiEntry("📬", "open mailbox with raised flag", "mail letter", .objects),
        EmojiEntry("✉️", "envelope", "mail letter email", .objects),
        EmojiEntry("📅", "calendar", "date schedule", .objects),
        EmojiEntry("📊", "bar chart", "graph stats", .objects),
        EmojiEntry("📈", "chart increasing", "up growth stocks", .objects),
        EmojiEntry("📉", "chart decreasing", "down loss stocks", .objects),

        // Symbols
        EmojiEntry("❤️", "red heart", "love heart", .symbols),
        EmojiEntry("🧡", "orange heart", "love heart", .symbols),
        EmojiEntry("💛", "yellow heart", "love heart", .symbols),
        EmojiEntry("💚", "green heart", "love heart", .symbols),
        EmojiEntry("💙", "blue heart", "love heart", .symbols),
        EmojiEntry("💜", "purple heart", "love heart", .symbols),
        EmojiEntry("🖤", "black heart", "love heart dark", .symbols),
        EmojiEntry("🤍", "white heart", "love heart", .symbols),
        EmojiEntry("🤎", "brown heart", "love heart", .symbols),
        EmojiEntry("💔", "broken heart", "heartbreak sad", .symbols),
        EmojiEntry("❣️", "heart exclamation", "love heart", .symbols),
        EmojiEntry("💕", "two hearts", "love", .symbols),
        EmojiEntry("💞", "revolving hearts", "love", .symbols),
        EmojiEntry("💓", "beating heart", "love pulse", .symbols),
        EmojiEntry("💗", "growing heart", "love", .symbols),
        EmojiEntry("💖", "sparkling heart", "love sparkle", .symbols),
        EmojiEntry("💘", "heart with arrow", "cupid love", .symbols),
        EmojiEntry("💝", "heart with ribbon", "gift love", .symbols),
        EmojiEntry("💯", "hundred points", "100 perfect score", .symbols),
        EmojiEntry("💢", "anger symbol", "mad", .symbols),
        EmojiEntry("💥", "collision", "boom explosion", .symbols),
        EmojiEntry("💫", "dizzy", "stars sparkle", .symbols),
        EmojiEntry("💦", "sweat droplets", "water splash", .symbols),
        EmojiEntry("💨", "dashing away", "dash wind fast", .symbols),
        EmojiEntry("✨", "sparkles", "shiny magic new", .symbols),
        EmojiEntry("🌟", "glowing star", "shine", .symbols),
        EmojiEntry("💬", "speech balloon", "chat talk comment", .symbols),
        EmojiEntry("💭", "thought balloon", "thinking bubble", .symbols),
        EmojiEntry("💤", "zzz", "sleep tired", .symbols),
        EmojiEntry("♨️", "hot springs", "steam onsen", .symbols),
        EmojiEntry("💌", "love letter", "mail heart", .symbols),
        EmojiEntry("❗", "red exclamation mark", "warning important", .symbols),
        EmojiEntry("❓", "red question mark", "what huh", .symbols),
        EmojiEntry("‼️", "double exclamation mark", "important urgent", .symbols),
        EmojiEntry("⁉️", "exclamation question mark", "what surprise", .symbols),
        EmojiEntry("⚠️", "warning", "caution alert", .symbols),
        EmojiEntry("🚫", "prohibited", "no forbidden ban", .symbols),
        EmojiEntry("✅", "check mark button", "done yes correct", .symbols),
        EmojiEntry("❌", "cross mark", "no wrong x", .symbols),
        EmojiEntry("⭕", "hollow red circle", "circle correct", .symbols),
        EmojiEntry("🆗", "ok button", "okay", .symbols),
        EmojiEntry("🆕", "new button", "new", .symbols),
        EmojiEntry("🆒", "cool button", "cool", .symbols),
        EmojiEntry("🆓", "free button", "free", .symbols),
        EmojiEntry("🔞", "no one under eighteen", "adult 18", .symbols),
        EmojiEntry("☮️", "peace symbol", "peace", .symbols),
        EmojiEntry("☯️", "yin yang", "balance tao", .symbols),
        EmojiEntry("♻️", "recycling symbol", "recycle green", .symbols),
        EmojiEntry("🔱", "trident emblem", "poseidon", .symbols),
        EmojiEntry("📛", "name badge", "name tag", .symbols),
        EmojiEntry("🔰", "japanese symbol for beginner", "beginner", .symbols),
        EmojiEntry("➕", "plus", "add math", .symbols),
        EmojiEntry("➖", "minus", "subtract math", .symbols),
        EmojiEntry("➗", "divide", "math division", .symbols),
        EmojiEntry("✖️", "multiply", "math times", .symbols),
        EmojiEntry("♾️", "infinity", "forever endless", .symbols),
        EmojiEntry("💲", "heavy dollar sign", "money price", .symbols),
        EmojiEntry("©️", "copyright", "legal", .symbols),
        EmojiEntry("®️", "registered", "legal trademark", .symbols),
        EmojiEntry("™️", "trade mark", "legal brand", .symbols),
        EmojiEntry("🔴", "red circle", "dot", .symbols),
        EmojiEntry("🟠", "orange circle", "dot", .symbols),
        EmojiEntry("🟡", "yellow circle", "dot", .symbols),
        EmojiEntry("🟢", "green circle", "dot go", .symbols),
        EmojiEntry("🔵", "blue circle", "dot", .symbols),
        EmojiEntry("🟣", "purple circle", "dot", .symbols),
        EmojiEntry("🔺", "red triangle pointed up", "shape", .symbols),
        EmojiEntry("🔻", "red triangle pointed down", "shape", .symbols),
        EmojiEntry("🔶", "large orange diamond", "shape", .symbols),
        EmojiEntry("🔷", "large blue diamond", "shape", .symbols),
        EmojiEntry("🏁", "chequered flag", "finish race done", .symbols),
        EmojiEntry("🚩", "triangular flag", "red flag warning", .symbols),
        EmojiEntry("🏳️", "white flag", "surrender", .symbols),
        EmojiEntry("🏴", "black flag", "pirate", .symbols),
        EmojiEntry("🏳️‍🌈", "rainbow flag", "pride lgbt", .symbols),
        EmojiEntry("🔔", "bell", "notification ring", .symbols),
        EmojiEntry("🔕", "bell with slash", "mute silent", .symbols),
        EmojiEntry("🎵", "musical note", "music song", .symbols),
        EmojiEntry("🎶", "musical notes", "music song melody", .symbols),
        EmojiEntry("🔒", "locked", "lock secure private", .symbols),
        EmojiEntry("🔓", "unlocked", "open lock", .symbols),
        EmojiEntry("🔍", "magnifying glass tilted left", "search find zoom", .symbols),
        EmojiEntry("🔗", "link", "chain url", .symbols),
        EmojiEntry("📣", "megaphone", "announce shout", .symbols),
        EmojiEntry("🔀", "shuffle tracks button", "random", .symbols),
        EmojiEntry("▶️", "play button", "start media", .symbols),
        EmojiEntry("⏸️", "pause button", "media", .symbols),
        EmojiEntry("⏹️", "stop button", "media", .symbols),
        EmojiEntry("⏩", "fast forward button", "media skip", .symbols),
        EmojiEntry("⏪", "fast reverse button", "media rewind", .symbols),
        EmojiEntry("🔼", "upwards button", "up arrow", .symbols),
        EmojiEntry("🔽", "downwards button", "down arrow", .symbols),
        EmojiEntry("⬆️", "up arrow", "north direction", .symbols),
        EmojiEntry("⬇️", "down arrow", "south direction", .symbols),
        EmojiEntry("⬅️", "left arrow", "west direction", .symbols),
        EmojiEntry("➡️", "right arrow", "east direction", .symbols),
        EmojiEntry("🔄", "counterclockwise arrows button", "refresh sync", .symbols),
        EmojiEntry("🔃", "clockwise vertical arrows", "refresh reload", .symbols),
    ]
}
