/// Labeled texting-style sentences: the accuracy yardstick for the engine
/// (spec AC7c ship gate) and, later, the bar any ML model must beat.
let corpus: [(text: String, label: String)] = [
    ("i went to the store", "."),
    ("i made it home", "."),
    ("see you at 8", "."),
    ("im on my way", "."),
    ("just landed", "."),
    ("the meeting got moved to friday", "."),
    ("i'll call you later", "."),
    ("we got the keys today", "."),
    ("dinner is in the fridge", "."),
    ("my phone was on silent", "."),
    ("traffic is terrible", "."),
    ("i think it starts at nine", "."),
    ("she said she'll be late", "."),
    ("the game got rained out", "."),
    ("im heading to bed", "."),
    ("that works for me", "."),
    ("sounds good", "."),
    ("ok see you there", "."),
    ("i left it on the counter", "."),
    ("the dog ate my sandwich", "."),
    ("we should leave by six", "."),
    ("i forgot my charger", "."),
    ("just say no", "."),
    ("tell them no", "."),
    ("do your homework", "."),
    ("have a great day", "."),
    ("take the trash out please", "."),
    ("call me when you land", "."),
    ("send me the address", "."),
    ("grab my jacket too", "."),
    ("let me know", "."),
    ("dont wait up", "."),
    ("pick whatever you like", "."),
    ("meet me out front", "."),
    ("text me when youre close", "."),
    ("iphone is better in my opinion", "."),
    ("it was fine i guess", "."),
    ("maybe next weekend", "."),
    ("probably not tonight", "."),
    ("not sure yet", "."),
    ("how are you", "?"),
    ("how was your day", "?"),
    ("what time does it start", "?"),
    ("what are we doing tonight", "?"),
    ("why is the door locked", "?"),
    ("when do you land", "?"),
    ("where are you", "?"),
    ("where did you park", "?"),
    ("who is coming", "?"),
    ("which one do you like", "?"),
    ("whose car is that", "?"),
    ("how much was it", "?"),
    ("are you home", "?"),
    ("is it raining there", "?"),
    ("was it fun", "?"),
    ("was your day good", "?"),
    ("were they mad", "?"),
    ("did he text back", "?"),
    ("did your mom call", "?"),
    ("does she know", "?"),
    ("can you pick up milk", "?"),
    ("can your brother come", "?"),
    ("could you send that again", "?"),
    ("will you be there", "?"),
    ("would you rather stay in", "?"),
    ("should we bring anything", "?"),
    ("may i borrow your charger", "?"),
    ("am i late", "?"),
    ("has the package arrived", "?"),
    ("do you want pizza", "?"),
    ("do we need anything else", "?"),
    ("have you eaten", "?"),
    ("want to grab dinner", "?"),
    ("wanna come with us", "?"),
    ("want me to drive", "?"),
    ("you're coming tonight right", "?"),
    ("we're still on for tomorrow right", "?"),
    ("thats the plan huh", "?"),
    ("youre in yeah", "?"),
    ("hows the new place", "?"),
    ("whats the wifi password", "?"),
    ("wheres the remote", "?"),
    ("you good", "?"),
    ("you up", "?"),
    ("any update", "?"),
    ("coffee tomorrow", "?"),
    ("guess who i saw today", "."),
    ("congrats on the new job", "!"),
    ("congratulations you two", "!"),
    ("wow that was incredible", "!"),
    ("omg that view", "!"),
    ("yay we won", "!"),
    ("woohoo finals are done", "!"),
    ("that concert was amazing", "!"),
    ("youre awesome", "!"),
    ("this is unbelievable", "!"),
    ("the finale was insane", "!"),
    ("happy birthday", "!"),
    ("lets gooo", "!"),
    ("we did it", "!"),
    ("i cant believe it", "!"),
    ("so excited for this", "!"),
    ("i had coffee with mr", "."),
    ("the appointment is with dr", "."),
    ("she lives on 5th ave", "."),
    ("bring snacks drinks etc", "."),
    ("its lakers vs", "."),
    ("happy to help", "."),
    ("lets talk tomorrow", "."),
    ("you rock", "."),
    ("so tired today", "."),
    ("u up", "?"),
    ("any news on the apartment", "?"),
    ("what's the wifi password", "?"),
    ("what\u{2019}s for dinner", "?"),
    ("let's go", "!"),
    ("don't forget your keys", "."),
    ("bring snacks e.g", "."),
    ("if you're free tomorrow", ","),
    ("when you land", ","),
    ("even if nobody comes", ","),
    ("but actually it is", ","),
    ("as i was leaving", ","),
    ("good afternoon", ","),
    ("if you quote me on this", ","),
    ("she said", "\""),
    ("u say", "\""),
    ("an amazing quote", "\""),
    ("what did he say", "?"),
    ("i thought you knew", "."),
    ("done with the car", "?"),
    ("on your way", "?"),
    ("leaving now", "."),
    ("still at work", "?"),
    ("food there yet", "?"),
    ("home in 10", "."),
]
