// GENERATED from blind-authored list rows (2026-07-31) -- do not hand-edit.
// Two independent blind authors (charter: no repo access), one blind QC
// judge (ALL PASS), 139 unique rows after dedupe. Split: crc32(text) % 2.
// FROZEN once thresholds are set in ListCorpusAccuracyTests: rows never
// change in a commit that touches engine source.
// Forms: list-item1 (intent-to-list, gold ","), list-item2, list-item3plus,
// list-close-and, comma-lookalike (comma present, not a list).

let listCorpusDev: [EvalRow] = [
    EvalRow(text: "After practice, do you want a ride", label: "?", form: "comma-lookalike", register: "full"),
    EvalRow(text: "Before you go, can you sign this", label: "?", form: "comma-lookalike", register: "full"),
    EvalRow(text: "Honestly, that movie was amazing", label: "!", form: "comma-lookalike", register: "full"),
    EvalRow(text: "after dinner, wanna watch something", label: "?", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "btw, the meeting moved to three", label: ".", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "dude, we won the whole thing", label: "!", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "i know its late, but are you up for a walk", label: "?", form: "comma-lookalike", register: "full"),
    EvalRow(text: "i tried calling twice, no answer", label: ".", form: "comma-lookalike", register: "frag"),
    EvalRow(text: "its cold out, bring a jacket", label: ".", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "just got home babe, are you still awake", label: "?", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "long story, i will tell you later", label: ".", form: "comma-lookalike", register: "frag"),
    EvalRow(text: "no worries, take your time", label: ".", form: "comma-lookalike", register: "frag"),
    EvalRow(text: "ok, see you at noon", label: ".", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "omg, that was the best game ever", label: "!", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "she said yes, i cant believe it", label: "!", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "shes running late, so start without her", label: ".", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "sorry, i totally forgot", label: ".", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "wait, did you already pay for the tickets", label: "?", form: "comma-lookalike", register: "full"),
    EvalRow(text: "The bus stops at the mall, the library, and campus", label: ".", form: "list-close-and", register: "full"),
    EvalRow(text: "get lettuce, tomatoes, and ranch", label: ".", form: "list-close-and", register: "frag"),
    EvalRow(text: "get the red one, the blue one, or whatever is cheap", label: ".", form: "list-close-and", register: "full"),
    EvalRow(text: "grab napkins, cups, or plates", label: ".", form: "list-close-and", register: "frag"),
    EvalRow(text: "i packed shirts, shorts, and sandals", label: ".", form: "list-close-and", register: "txt"),
    EvalRow(text: "im free monday, wednesday, or friday", label: ".", form: "list-close-and", register: "txt"),
    EvalRow(text: "snacks, drinks, and a speaker", label: ".", form: "list-close-and", register: "frag"),
    EvalRow(text: "we can do friday, saturday, or sunday", label: ".", form: "list-close-and", register: "full"),
    EvalRow(text: "The recipe calls for flour", label: ",", form: "list-item1", register: "full"),
    EvalRow(text: "dont forget eggs", label: ",", form: "list-item1", register: "txt"),
    EvalRow(text: "for the party we need cups", label: ",", form: "list-item1", register: "full"),
    EvalRow(text: "gotta grab batteries", label: ",", form: "list-item1", register: "txt"),
    EvalRow(text: "i still need to book the hotel", label: ",", form: "list-item1", register: "full"),
    EvalRow(text: "im packing my charger", label: ",", form: "list-item1", register: "txt"),
    EvalRow(text: "pack sunscreen", label: ",", form: "list-item1", register: "frag"),
    EvalRow(text: "today i have to do laundry", label: ",", form: "list-item1", register: "full"),
    EvalRow(text: "we need chips", label: ",", form: "list-item1", register: "txt"),
    EvalRow(text: "we should invite the neighbors", label: ",", form: "list-item1", register: "full"),
    EvalRow(text: "The movers took the couch, the bookshelf", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "add tomatoes, cucumbers", label: ",", form: "list-item2", register: "frag"),
    EvalRow(text: "bring chips, salsa", label: ",", form: "list-item2", register: "frag"),
    EvalRow(text: "can u grab onions, garlic", label: ",", form: "list-item2", register: "txt"),
    EvalRow(text: "dinner options are tacos, pasta", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "dont forget sunscreen, bug spray", label: ",", form: "list-item2", register: "txt"),
    EvalRow(text: "grab milk, eggs", label: ",", form: "list-item2", register: "frag"),
    EvalRow(text: "i still have to clean, pack", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "im bringing my charger, headphones", label: ",", form: "list-item2", register: "txt"),
    EvalRow(text: "movie night snacks are popcorn, gummies", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "need to text mom, call the dentist", label: ",", form: "list-item2", register: "frag"),
    EvalRow(text: "order me fries, a shake", label: ",", form: "list-item2", register: "frag"),
    EvalRow(text: "she wants balloons, streamers", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "the party needs cups, napkins", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "we invited sarah, her boyfriend", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "we need chips, watermelon", label: ",", form: "list-item2", register: "txt"),
    EvalRow(text: "we need paper towels, dish soap", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "we should invite jake, his brother", label: ",", form: "list-item2", register: "txt"),
    EvalRow(text: "we still owe rent, utilities", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "She ordered wings, fries, mozzarella sticks", label: ",", form: "list-item3plus", register: "full"),
    EvalRow(text: "The trip covers gas, tolls, parking", label: ",", form: "list-item3plus", register: "full"),
    EvalRow(text: "We visited the museum, the park, the pier", label: ",", form: "list-item3plus", register: "full"),
    EvalRow(text: "bring plates, forks, napkins", label: ",", form: "list-item3plus", register: "frag"),
    EvalRow(text: "grab eggs, butter, flour", label: ",", form: "list-item3plus", register: "frag"),
    EvalRow(text: "i did the dishes, the laundry, the vacuuming", label: ",", form: "list-item3plus", register: "txt"),
    EvalRow(text: "my day is class, practice, work", label: ",", form: "list-item3plus", register: "txt"),
    EvalRow(text: "my day was work, errands, more work", label: ",", form: "list-item3plus", register: "full"),
    EvalRow(text: "she invited the cousins, the neighbors, her coworkers", label: ",", form: "list-item3plus", register: "full"),
    EvalRow(text: "the box has cables, batteries, tape", label: ",", form: "list-item3plus", register: "full"),
    EvalRow(text: "we tried the ramen place, the taco truck, that new cafe", label: ",", form: "list-item3plus", register: "full"),
]

let listCorpusTest: [EvalRow] = [
    EvalRow(text: "If it rains, is the game still on", label: "?", form: "comma-lookalike", register: "full"),
    EvalRow(text: "If you get there first, grab a table", label: ".", form: "comma-lookalike", register: "full"),
    EvalRow(text: "Once the oven beeps, take the bread out", label: ".", form: "comma-lookalike", register: "full"),
    EvalRow(text: "Thanks again, that really helped", label: "!", form: "comma-lookalike", register: "full"),
    EvalRow(text: "To be honest, I liked the old one better", label: ".", form: "comma-lookalike", register: "full"),
    EvalRow(text: "When you leave, lock the door", label: ".", form: "comma-lookalike", register: "full"),
    EvalRow(text: "dude, you totally called it", label: "!", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "hey mom, can you call me", label: "?", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "hey mom, can you call me back", label: "?", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "honestly, do you even want to go", label: "?", form: "comma-lookalike", register: "full"),
    EvalRow(text: "if ur still up, wanna watch a movie", label: "?", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "if you leave now, you will beat the rain", label: ".", form: "comma-lookalike", register: "full"),
    EvalRow(text: "no worries, we can do it tomorrow", label: ".", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "omg, we got the apartment", label: "!", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "she brought snacks, we stayed way too long", label: ".", form: "comma-lookalike", register: "full"),
    EvalRow(text: "sorry, my phone died again", label: ".", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "thanks for the ride, you saved me", label: "!", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "the movie was fine, not great", label: ".", form: "comma-lookalike", register: "frag"),
    EvalRow(text: "traffic was insane, took me an hour", label: ".", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "wait, are u serious", label: "?", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "when you get a sec, send me the address", label: ".", form: "comma-lookalike", register: "full"),
    EvalRow(text: "youre coming tonight, right", label: "?", form: "comma-lookalike", register: "txt"),
    EvalRow(text: "Dinner is soup, salad, and garlic bread", label: ".", form: "list-close-and", register: "full"),
    EvalRow(text: "She needs a pen, paper, and a folder", label: ".", form: "list-close-and", register: "full"),
    EvalRow(text: "We can do pizza, tacos, or burgers", label: ".", form: "list-close-and", register: "full"),
    EvalRow(text: "bring a swimsuit, a towel, and flip flops", label: ".", form: "list-close-and", register: "frag"),
    EvalRow(text: "chips, ice, and sprite", label: ".", form: "list-close-and", register: "txt"),
    EvalRow(text: "do laundry, dishes, and the trash", label: ".", form: "list-close-and", register: "frag"),
    EvalRow(text: "i packed shorts, sandals, and sunscreen", label: ".", form: "list-close-and", register: "full"),
    EvalRow(text: "kiddo wants juice, crackers, and a banana", label: ".", form: "list-close-and", register: "txt"),
    EvalRow(text: "she brought cookies, brownies, and lemonade", label: ".", form: "list-close-and", register: "full"),
    EvalRow(text: "text me when you leave, park, and get inside", label: ".", form: "list-close-and", register: "full"),
    EvalRow(text: "we could meet at six, seven, or eight", label: ".", form: "list-close-and", register: "txt"),
    EvalRow(text: "we need bread, milk, and eggs", label: ".", form: "list-close-and", register: "full"),
    EvalRow(text: "Remember to pack towels", label: ",", form: "list-item1", register: "full"),
    EvalRow(text: "bring your swimsuit", label: ",", form: "list-item1", register: "frag"),
    EvalRow(text: "can u buy bread", label: ",", form: "list-item1", register: "txt"),
    EvalRow(text: "can you grab milk", label: ",", form: "list-item1", register: "full"),
    EvalRow(text: "dont forget the sunscreen", label: ",", form: "list-item1", register: "txt"),
    EvalRow(text: "get me a burger", label: ",", form: "list-item1", register: "frag"),
    EvalRow(text: "grab some napkins", label: ",", form: "list-item1", register: "frag"),
    EvalRow(text: "shopping list so far is eggs", label: ",", form: "list-item1", register: "frag"),
    EvalRow(text: "so far i packed shirts", label: ",", form: "list-item1", register: "txt"),
    EvalRow(text: "we need milk", label: ",", form: "list-item1", register: "full"),
    EvalRow(text: "I invited Sarah, her roommate", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "My schedule this fall has math, chem", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "Please pick up stamps, envelopes", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "She wants balloons, streamers", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "add onions, peppers", label: ",", form: "list-item2", register: "frag"),
    EvalRow(text: "can you pick up bread, cheese", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "dont forget your keys, wallet", label: ",", form: "list-item2", register: "txt"),
    EvalRow(text: "for the trip i packed sunscreen, towels", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "get the small candles, matches", label: ",", form: "list-item2", register: "frag"),
    EvalRow(text: "get the small screwdriver, some tape", label: ",", form: "list-item2", register: "frag"),
    EvalRow(text: "my list so far is stamps, envelopes", label: ",", form: "list-item2", register: "full"),
    EvalRow(text: "pack ur charger, headphones", label: ",", form: "list-item2", register: "txt"),
    EvalRow(text: "put away the dishes, the laundry", label: ",", form: "list-item2", register: "frag"),
    EvalRow(text: "remember ur water bottle, cleats", label: ",", form: "list-item2", register: "txt"),
    EvalRow(text: "today im doing laundry, dishes", label: ",", form: "list-item2", register: "txt"),
    EvalRow(text: "we gotta clean the kitchen, the bathroom", label: ",", form: "list-item2", register: "txt"),
    EvalRow(text: "We need forks, plates, cups", label: ",", form: "list-item3plus", register: "full"),
    EvalRow(text: "add tomatoes, basil, garlic", label: ",", form: "list-item3plus", register: "frag"),
    EvalRow(text: "bring towels, sunscreen, snacks", label: ",", form: "list-item3plus", register: "frag"),
    EvalRow(text: "clean ur room, the hall, the stairs", label: ",", form: "list-item3plus", register: "txt"),
    EvalRow(text: "get bananas, yogurt, granola", label: ",", form: "list-item3plus", register: "frag"),
    EvalRow(text: "gotta do laundry, groceries, gym", label: ",", form: "list-item3plus", register: "txt"),
    EvalRow(text: "grab batteries, tape, scissors", label: ",", form: "list-item3plus", register: "frag"),
    EvalRow(text: "he ordered wings, fries, a shake", label: ",", form: "list-item3plus", register: "full"),
    EvalRow(text: "i cleaned the kitchen, bathroom, hallway", label: ",", form: "list-item3plus", register: "full"),
    EvalRow(text: "pack socks, boots, gloves, a hat", label: ",", form: "list-item3plus", register: "frag"),
    EvalRow(text: "pack socks, chargers, toothbrush", label: ",", form: "list-item3plus", register: "frag"),
    EvalRow(text: "u need a pencil, calculator, notebook", label: ",", form: "list-item3plus", register: "txt"),
    EvalRow(text: "we need chips, salsa, guac", label: ",", form: "list-item3plus", register: "txt"),
]
