/// REAL eval set v2: sentences from the UCI SMS Spam Collection (ham only)
/// whose senders typed the mark themselves -- the mark is the label.
/// Now includes comma rows: text the sender followed with "," mid-message
/// (the "sentence continues" intent). Stratified 200/150/100/150 (. ? ! ,).
/// Charter, axes, and handling rules: EVAL.md at the repo root.
/// FROZEN: sentences never edited in a change that also touches engine code.
///
/// Split (seed 7): realCorpusDev misses may be studied; realCorpusTest is
/// HELD OUT -- aggregate score only, never inspect its sentences.

let realCorpusDev: [(text: String, label: String)] = [
    ("went to hair cut", "."),
    ("Going to lounge in a nice long bath now", "?"),
    ("very less contacts here", ","),
    ("Tell dear what happen to you", "."),
    ("No need lar i go engin", "?"),
    ("You intrepid duo you", "!"),
    ("Y she so funny we bluff her 4 wat", "."),
    ("would you like to go on a dinner date next week", "?"),
    ("I will be gentle princess", "!"),
    ("I hope you enjoy your driving lesson", ","),
    ("and have a big dent", "!"),
    ("Nah it's straight", ","),
    ("If none Can do it", ","),
    ("How would you like to be treated", "?"),
    ("Though V r in d same clock", ","),
    ("I am in tirupur da", ","),
    ("So what about you", "."),
    ("She doesnt need any test", "."),
    ("I'm excited each day i spend with you", "."),
    ("I'm sorry your room was so embarassing", "."),
    ("U wan me 2 tell him u're not in singapore or wat", "?"),
    ("A Boy loved a gal", "."),
    ("I shall book chez jules for half eight", ","),
    ("In the envelope", ","),
    ("I'm ok", "."),
    ("don know what will happen after that", "."),
    ("now gibbs", "."),
    ("Why de", "."),
    ("Don no da:)whats you plan", "?"),
    ("Are you eating your mom's left over dinner", "?"),
    ("I'm in class", "."),
    ("Before i left", ","),
    ("What's your room number again", "?"),
    ("I meant middle left or right", "?"),
    ("I am very tired now", "."),
    ("Hello handsome", "!"),
    ("How long before you get reply", ","),
    ("U wan 2 go buy tickets first", "?"),
    ("Then ü wait 4 me at bus stop aft ur lect lar", "."),
    ("Infact happy new year", "."),
    ("and TRUE Friends STaY forever beyond words", ","),
    ("Yes but i dont care", "!"),
    ("Do 1 thing", "!"),
    ("Why must we sit around and wait for summer days to celebrate", "."),
    ("Hi Dear Call me its urgnt", "."),
    ("I'm in church now", ","),
    ("Good morning", ","),
    ("what happend", "?"),
    ("They can get lost", ","),
    ("Wen can I pick them up", "?"),
    ("When you're unemployed", ","),
    ("Many more happy returns of the day", "."),
    ("Lol I know", "!"),
    ("You have to be in the lingo", "."),
    ("Can you pls call back", "."),
    ("when you thought i had left you", ","),
    ("It was never my intention to run you out", ","),
    ("Do have a wonderful day", "."),
    ("Wat time liao", ","),
    ("Aight I'll grab something to eat too", ","),
    ("Its good to b home but its been quite a reality check", "."),
    ("I'm at home", ","),
    ("Merry Christmas to you too babe", ","),
    ("Bit far", "!"),
    ("Night has ended for another day", ","),
    ("Was actually about to send you a reminder today", "."),
    ("Lol no", "."),
    ("See you at six then", "!"),
    ("Not to worry", "."),
    ("I started uni today", "."),
    ("Mystery solved", "!"),
    ("Hey loverboy", "!"),
    ("Water logging in desert", "."),
    ("Think about wot u want to do", ","),
    ("id luv 2 but ive had 2 go home", "!"),
    ("I don't quite know what to do", "."),
    ("I'm done", "."),
    ("Yup he msg me: is tat yijue", "?"),
    ("He propsd bt she didnt mind", "."),
    ("No openings for that room 'til after thanksgiving without an upcharge", "."),
    ("What i mean was i left too early to check", ","),
    ("Call me da", ","),
    ("Bright light", "!"),
    ("Me too baby", "!"),
    ("After that only i can come", "."),
    ("If he wont use it", ","),
    ("Can you pls open the back", "?"),
    ("How's my loverboy doing", "?"),
    ("You are eldest know", "."),
    ("You still coming tonight", "?"),
    ("Nice talking to you", "!"),
    ("That day ü say ü cut ur hair at paragon", ","),
    ("Nothing really", ","),
    ("Yes we must speak friday - egg-potato ratio for tortilla needed", "!"),
    ("Not sure but if there's anyway i can help let me know", "."),
    ("i deleted my contact that why", "?"),
    ("girls never rang after india", "."),
    ("Take care oh", "."),
    ("I KNOW U DONT LIKE ME LIKE THAT SO DONT WORRY", "."),
    ("So wats ur opinion abt him and how abt is character", "?"),
    ("The sad part is i missing home", "."),
    ("That's good", ","),
    ("is coming", "."),
    ("Are you in the library", "?"),
    ("Tyler (getting an 8th) has to leave not long after 9", ","),
    ("how are you sha", "!"),
    ("Are you gonna see him again", "?"),
    ("then had tea/coffee", "?"),
    ("Bloody hell", ","),
    ("Pass dis to all ur contacts n see wat u get", "!"),
    ("How much is blackberry bold2 in nigeria", "."),
    ("blood for heart", ","),
    ("Y she dun believe leh", "?"),
    ("Forgot you were working today", "!"),
    ("\"Im at arestaurant eating squid", "!"),
    ("It shall be fine", "."),
    ("Spoons it is then okay", "?"),
    ("Wish you guys a great semester", "."),
    ("I'll make a trip to Ptbo for that", "."),
    ("U finish dinner already", "?"),
    ("Message from", "."),
    ("Some of them told accenture is not confirm", "."),
    ("Going to take your babe out", "?"),
    ("A bit of Ur smile is my hppnss", ","),
    ("Okey dokey", ","),
    ("Im done", "."),
    ("De dont let it careless", "."),
    ("It was messy wednesday", ","),
    ("Take something for pain", "."),
    ("Short But Cute : \" Be a good person", ","),
    ("If u get back", ","),
    ("In case you wake up wondering where I am", ","),
    ("U noe where", "?"),
    ("Yes please", "."),
    ("Jordan got voted out last nite", "!"),
    ("My bf not coming", "."),
    ("Short But Cute: \"Be a good person", ","),
    ("I am on the way to tirupur", "."),
    ("No objection", "."),
    ("It may not add years to your Life", "!"),
    ("Dont pick up d call when something important is There to tell", "."),
    ("Did you get that police abstract", "?"),
    ("It sucks being ill at xmas", "!"),
    ("A cuddle would be lush", "!"),
    ("Ü going home first", "?"),
    ("Then ur physics get a-", "?"),
    ("Mode men or have you left", "."),
    ("Do you get the parish magazine", ","),
    ("Jus ans me lar", "."),
    ("I think I‘m waiting for the same bus", "!"),
    ("Hurry home u big butt", "."),
    ("And she'll be able to deliver and have basic care", "."),
    ("I tot u reach liao", "."),
    ("By march ending", ","),
    ("Just saying hey", "."),
    ("Where r we meeting", "?"),
    (":/ I'm tired of them shoving stuff up me", "."),
    ("It's ok i wun b angry", "."),
    ("And very importantly", ","),
    ("aight we can pick some up", ","),
    ("Where's my boytoy", "?"),
    ("Will you remember to kiss your mom in the morning", "?"),
    ("How will I creep on you now", "?"),
    ("Why do you ask princess", "?"),
    ("Thats cool", "!"),
    ("V nice", "!"),
    ("Both are essential in life", "!"),
    ("pls dnt forget it", "."),
    ("If i not meeting ü all rite then i'll go home lor", "."),
    ("Hey babe", ","),
    ("Same time + place as always", "?"),
    ("Darren ask me not 2 cut too short", "."),
    ("I am great princess", "!"),
    ("On the paper", ","),
    ("I'm currently shopping for the right medical insurance for her", "."),
    ("What not under standing", "."),
    ("What happened", "?"),
    ("Genius what's up", "."),
    ("Contact joke ogunrinde", ","),
    ("U having lunch alone", "?"),
    ("How much u trying to get", "?"),
    ("THATS ALRITE GIRL", ","),
    ("Yeah sure", ","),
    ("I want to show you the world", ","),
    ("Accept life the way it comes", "!"),
    ("Up to u", "!"),
    ("He's just gonna worry for nothing", "."),
    ("Will you try rebooting", "?"),
    ("Ya ok", ","),
    ("BEEN SLEEPING ON DA SOFA ALL DAY", ","),
    ("Which weekend", "?"),
    ("Jane babes not goin 2 wrk", ","),
    ("k:)advance happy pongal", "."),
    ("Go where n buy", "?"),
    ("Moral:One can 4get d name of a person", ","),
    ("Have a fab new year", ","),
    ("Er yeah", ","),
    ("Hello beautiful r u ok", "?"),
    ("Good journey", "!"),
    ("Still eating", "?"),
    ("Happy new years melody", "!"),
    ("What diet", "?"),
    ("She said", ","),
    ("What does he do that keeps him from coming to his Queen", ","),
    ("2morrow off", "!"),
    ("Hello my little party animal", "!"),
    ("Hello lover", "!"),
    ("Want to go out for a meal tonight", "?"),
    ("Merry christmas to u too annie", "!"),
    ("Party's at my place at usf", ","),
    ("Sorry im getting up now", ","),
    ("In exeter still", ","),
    ("Thk got lo oso", ","),
    ("G says you never answer your texts", ","),
    ("I promise to treat you well", "!"),
    ("It was only from tescos but quite nice", "."),
    ("Will ü b going to esplanade fr home", "?"),
    ("You DO love me", "!"),
    ("No did you check", "?"),
    ("doesnt that show I care y wont u believe im serious", "?"),
    ("Hello wats talks email address", "?"),
    ("Fighting with the world is easy", ","),
    ("Any job prospects yet", "?"),
    ("Its not the same here", "."),
    ("I had a brilliant weekend thanks", "."),
    ("Sorry again", "!"),
    ("Unlimited texts", "."),
    ("You have been wonderful", "."),
    ("We went there", "."),
    ("i just wanted my bed", "!"),
    ("You'd like that wouldn't you", "?"),
    ("what are your new years plans", "?"),
    ("daddy wants to eat you all night long", "!"),
    ("ll stay", "."),
    ("U so lousy", ","),
    ("No sir", "."),
    ("Dear reached railway", "."),
    ("I know dat feelin had it with Pete", "!"),
    ("Hope you are good", "."),
    ("Its ok", ","),
    ("Good stuff", ","),
    ("Can not use foreign stamps in this country", "."),
    ("Wat time u wan 2 come n look 4 us", "?"),
    ("Can you hear it", "?"),
    ("I've tried everything", "."),
    ("Me also da", ","),
    ("Merry Christmas", "!"),
    ("I'm ok wif it cos i like 2 try new things", "."),
    ("Yesterday its with me only", "."),
    ("I might have a nap tho", "!"),
    ("I really do miss you", "."),
    ("Sorry I flaked last night", ","),
    ("Dunno network not gd i thk", "."),
    ("Si si", "."),
    ("Everything alright", "."),
    ("All you know about costs", ","),
    ("So how many days since then", "?"),
    ("Call me when u finish then i come n pick u", "."),
    ("How are you doing", "."),
    ("Have fun", "."),
    ("Cos telling shuhui is like telling leona also", "."),
    ("Siva is in hostel aha:-", "."),
    ("Wat's da model num of ur phone", "?"),
    ("And one thinks shes obese", "."),
    ("And I walk beside you", "."),
    ("I am a one woman man", "!"),
    ("I don't think he has spatula hands", "!"),
    ("You know", "?"),
    ("If ever i was angry with you", ","),
    ("Ok i will tell her to stay out", "."),
    ("Nice one then i like lor", "."),
    ("Dont search love", ","),
    ("And get a bit stylish", "."),
    ("G o o d n i g h t", "."),
    ("Why do they get all the good stuff", "?"),
    ("Happy new year to u too", "!"),
    ("R u there in home", "."),
    ("Lol that's different", "."),
    ("At home can do my stuff or watch tv wat", "."),
    ("Hi Shanil", ","),
    ("Just sent again", "."),
    ("You keep saying that you're not", ","),
    ("How goes you day", "?"),
    ("We can think of something to do he he", "!"),
    ("After that i will keep in touch more", "."),
    ("You mean a great deal to me", "."),
    ("So why wouldn't THAT be the time to clean", ","),
    ("But wat u copied jus now got use", "?"),
    ("Are you alright", "?"),
    ("U definitely need a module from e humanities dis sem izzit", "?"),
    ("Happy new year oh", "."),
    ("Good morning princess", "!"),
    ("How much do Ta's earn there", "."),
    ("BEER is now cheaper than PETROL", "!"),
    ("Good afternoon", ","),
    ("Lol now I'm after that hot air balloon", "!"),
    ("I am going to slap your ass with my dick", "!"),
    ("Is it ok if we meet another night", "?"),
    ("'Wnevr i wana fal in luv vth my books", ","),
    ("Customer place", ","),
]

let realCorpusTest: [(text: String, label: String)] = [
    ("Where's my sexy buns now", "?"),
    ("I thought slide is enough", "."),
    ("Great escape", "."),
    ("Why you Dint come with us", "."),
    ("But I'm on a diet", "."),
    ("My butt is sore", "."),
    ("Starts on monday", "!"),
    ("Miss ya", ","),
    ("Garbage bags", ","),
    ("See you at some point", "!"),
    ("… we r stayin here an extra week", ","),
    ("I am going to film 2day da", "."),
    ("I'm exhausted", "."),
    ("When should I bring the mini cheetos bag over", "?"),
    ("Edison has rightly said", ","),
    ("And he loves so much", "!"),
    ("HEY MATE", "!"),
    ("I'm reaching home in 5 min", "."),
    ("Have I told you", "?"),
    ("Any help would be great", ","),
    ("Others have to hit", "."),
    ("Wn it was about 2 hit d girl", ","),
    ("Jay told me already", ","),
    ("Pharmacy is like 2 minutes away", "."),
    ("Crucify is c not s", "."),
    ("Are you ready to moan and scream in ecstasy", "?"),
    ("Whats the staff name who is taking class for us", "?"),
    ("Sounds great", "!"),
    ("havn't seen  for ages", ","),
    ("I can", "."),
    ("i can't pay the rent", ","),
    ("You made my day", "."),
    ("Only joking", "!"),
    ("il download", ","),
    ("this will increase the chance of winning", "."),
    ("It could work", ","),
    ("U can tell me all about", "!"),
    ("I woulda changed that if i had realized it said nyc", "!"),
    ("All are Gods blessings", "!"),
    ("Only buy 2 meals ONLY 2", "."),
    ("WHO ARE YOU SEEING", "?"),
    ("Have a beautiful day", "."),
    ("Are you going to make me moan", "?"),
    ("Not getting anywhere with this damn job hunting over here", "!"),
    ("Wot u up 2", "?"),
    ("Did u find a sitter for kaitlyn", "?"),
    ("Is there any training tomorrow", "?"),
    ("Hope ur day * good", "!"),
    ("Yeah hopefully", ","),
    ("Text me when you get off", ","),
    ("You didnt complete your gist oh", "."),
    ("I'll treat you", "!"),
    ("Its worse if if uses half way then stops", "."),
    ("Do you have any dislikes in bed", "?"),
    ("member how I said my aunt flow didn't visit for 6 months", "?"),
    ("Dunno leh", ","),
    ("Our total order is a quarter", ","),
    ("U drunkard", "!"),
    ("Stop calling everyone saying I might have cancer", "."),
    ("She was supposed to be but couldn't make it", ","),
    ("You not listen aha", "."),
    ("NOT MUCH NO FIGHTS", "."),
    ("No need for the drug anymore", "."),
    ("Ugh y can't u just apologize", ","),
    ("Will soon be over", "."),
    ("U coming 2 pick me", "?"),
    ("So what u doing today", "?"),
    ("Wat's my dear doing", "?"),
    ("Hasn't that been the pattern recently crap weekends", "?"),
    ("Or bomb and date as my phone wanted to say", "!"),
    ("How's my boytoy", "?"),
    ("How about you", "?"),
    ("Chinatown got porridge", ","),
    ("Yeah still up 4 tonight", "."),
    ("Did you try making another butt", "."),
    ("May be ur frnds or classmates", "?"),
    ("just standing", "."),
    ("Where u been hiding stranger", "?"),
    ("ll do so tomorrow", "."),
    ("That is wondar full flim", "."),
    ("Did u receive my msg", "?"),
    ("Wat time r ü going to xin's hostel", "?"),
    ("You're right", "!"),
    ("Ready for more shopping tho", "!"),
    ("Then wat r u doing now", "?"),
    ("Wuld get with em", ","),
    ("Yen madodu", ","),
    ("U GOIN OUT 2NITE", "?"),
    ("Excellent service by Dino and Prem", "."),
    ("Yeah I think my usual guy's still passed out from last night", ","),
    ("Anything lor is she coming", "?"),
    ("I can listen you but you cann't listen my voice", "."),
    ("What time are  and that going", "?"),
    ("Wat's happening on your side", "."),
    ("Anything lor", "."),
    ("life would be much simpler", ","),
    ("Where r e meeting tmr", "?"),
    ("Pick ü up at 4 is it", "?"),
    ("Were you on a friends net", "?"),
    ("I gotta cash in all my nitros", "."),
    ("Com you see", "!"),
    ("Have a good evening", "!"),
    ("Hope you are having a great day", "."),
    ("Oooh I got plenty of those", "!"),
    ("Hey come online", "!"),
    ("thts it chikku", ","),
    ("sorry brah", ","),
    ("But relax", ","),
    ("Any friend of mine and all that", "!"),
    ("Reverse is cheating", "."),
    ("Your gonna be the death if me", "."),
    ("Ü still got lessons", "?"),
    ("The hair cream has not been shipped", "."),
    ("Oh yeah", "!"),
    ("I'm in town now so i'll jus take mrt down later", "."),
    ("Lol you forgot it eh", "?"),
    ("2mro i am not coming to gym machan", "."),
    ("And will reply", "."),
    ("You need a car to move freely", ","),
    ("wot has u inmind 4 recreation dis eve", "?"),
    ("Night sweet", ","),
    ("Bt V alwys stay conected", "."),
    ("YEAH WAS A GOODNITE SHAME U NEVA CAME", "!"),
    ("Did he say how fantastic I am by any chance", ","),
    ("No need to say anything to me", "."),
    ("Get the door", ","),
    ("Sorry man", ","),
    ("Oh is it", "!"),
    ("pls do me a favor", "."),
    ("Why would i think a picture of your room would hurt you", ","),
    ("Hey sexy buns", "!"),
    ("Did you make a tea", "?"),
    ("Congratulations ore mo owo re wa", "."),
    ("Please protect yourself from e-threats", "."),
    ("Doesn't your heart ache without me", "?"),
    ("Hi its Kate how is your evening", "?"),
    ("Got a pleasant surprise when i checked my balance -u c", ","),
    ("I'll get there at 3", ","),
    ("No my blankets are sufficient", ","),
    ("Forgot it takes me 3 years to shower", ","),
    ("Hmm ok", ","),
    ("Ü all got how many pages", "?"),
    ("How goes it loverboy", "?"),
    ("he have great potential and talent", "."),
    ("I wish you were here in bed with me", ","),
    ("If we could decide who to love", ","),
    ("I take it all back ur not a freak", "!"),
    ("how tall are you princess", "?"),
    ("I'm fine", "."),
    ("Yeah why not", ","),
    ("I shoot big loads so get ready", "!"),
    ("Are you around tonght wen this girl comes", "?"),
    ("Dear relieved of westonzoyland", ","),
    ("I'm in e lazy mode today", "."),
    ("Call me when you/carlos is/are here", ","),
    ("What your plan for pongal", "?"),
    ("I'm wylie", ","),
    ("Wat's e road name of ur house", "?"),
    ("Seventeen pounds for seven hundred ml – hope ok", "."),
    ("Have a gr8 day", "."),
    ("Can we assume we won't have it this year now", "?"),
    ("R u meeting da ge at nite tmr", "?"),
    ("I appreciate you", "."),
    ("Do you have a po box number", "?"),
    ("DIDNT END UP GOIN DOWN TOWN JUS DA PUB INSTEAD", "!"),
    ("How are you", "."),
    ("Both :) i shoot big loads so get ready", "!"),
    ("He got ask me abt ur reaction lor", "."),
    ("What is this 'hex' place you talk of", "?"),
    ("When you get free", ","),
    ("When can ü come out", "?"),
    ("Yo chad which gymnastics class do you wanna take", "?"),
    ("Your opinion about me", "?"),
    ("or i have to admit", ","),
    ("Trust me", "."),
    ("Are you in the pub", "?"),
    ("Alrite jod hows the revision goin", "?"),
    ("Playin space poker", ","),
    ("Did u get  email", "?"),
    ("U must have taken your REAL Valentine out shopping first", "."),
    ("Like dat almost all know liao", "."),
    ("hope u are okay every time I call ure phone is off", "!"),
    ("Well I'm going to be an aunty", "!"),
    ("Looks like it's going 2 rain soon", "."),
    ("U Accept me as", "?"),
    ("Save yourself the stress", "."),
    ("On sat right", "?"),
    ("Did you have a good birthday", "?"),
    ("Did you get any gift", "?"),
    ("Did either of you have any idea's", "?"),
    ("That's my honeymoon outfit", "."),
    ("did u c d little thing i left in the lounge", "?"),
    ("Does cinema plus drink appeal tomo", "?"),
    ("I am in meeting sir", "."),
    ("TELL HER I SAID EAT SHIT", "."),
    ("I didn't mean to do that", "."),
    ("'' ''OK''", ","),
    ("Please complete the drug", "."),
    ("Multiply the numbers independently and count decimal points then", ","),
    ("You are a very very very very bad girl", "."),
    ("So what type of food do you like", "?"),
    ("All the best with it", "."),
    ("We took hooch for a walk toaday and i fell over", "!"),
    ("Did you say bold", ","),
    ("k:)when are you going", "?"),
    ("U were supposed to take me shopping today", "."),
    ("Neva test quality", "."),
    ("Have a lovely holiday", ","),
    ("That'll give enough time to get there", ","),
    ("On you or in you", "?"),
    ("We will be a good combination", "!"),
    ("Is he being positive or negative", "?"),
    ("Wat's ur email", "?"),
    ("So c u wan 2 watch today or tmr lor", "."),
    ("when are ü going to book", "?"),
    ("Wish we were together right now", "!"),
    ("Only hospitals and medical places are safe", "."),
    ("Wat u doing there", "?"),
    ("Will be out of class in a few hours", "."),
    ("And is there a way you can send shade's stuff to her", "."),
    ("when wil you reach here", "?"),
    ("How are you feeling today", "?"),
    ("First answer my question", "."),
    ("MY CAKE TASTS LUSH", "!"),
    ("It's cool", ","),
    ("Haha better late than ever", ","),
    ("I'm still looking for a car to buy", "."),
    ("We can skip ard oso", ","),
    ("And that's fine", ","),
    ("y r u smiling", "?"),
    ("Go until jurong point", ","),
    ("I am sorry it hurt you", "."),
    ("Been running but only managed 5 minutes and then needed oxygen", "!"),
    ("No it was cancelled yeah baby", "!"),
    ("Thanx 4 everything dat u've done today", ","),
    ("Will they still let us go a not ah", "?"),
    ("I absolutely LOVE South Park", "!"),
    ("Wen ur lovable bcums angry wid u", ","),
    ("Early bird", "!"),
    ("Thnx dude", "."),
    ("Hi this is yijue", ","),
    ("Wont a Biro do", "?"),
    ("It wasn't there", "."),
    ("My dad wake me up at 10 smth 2 eat lunch today", "."),
    ("HOPE URFEELING BETTERSN LUV", "!"),
    ("SIB never asks for sensitive information like Passwords", ","),
    ("*smacks your ass* Did you go to the gym too", "?"),
    ("Where are you", "?"),
    ("You dont have to say if it is uncomfortable", "."),
    ("Arms fine", ","),
    ("Ugh hopefully the asus ppl dont randomly do a reformat", "."),
    ("No news on job", ","),
    ("Ill phone u when i get back", "."),
    ("we have to get up at 7am every day", "!"),
    ("\"CHEERS U TEX MECAUSE U WEREBORED", "!"),
    ("Do u noe wat time e place dat sells 4d closes", "?"),
    ("You are not bothering me but you have to trust my answers", "."),
    ("U so free wan 2 help me", "?"),
    ("Geoenvironmental implications", "."),
    ("CHEERS LOU", "!"),
    ("U leh", "?"),
    ("Did you catch the bus", "?"),
    ("I love you", ","),
    ("Feel like trying kadeem again", "?"),
    ("Ya tel", ","),
    ("So april", "."),
    ("This is hoping you enjoyed your game yesterday", "."),
    ("Aight no rush", ","),
    ("his loss is my gain :) so do you work", "?"),
    ("Are you at home", ","),
    ("I think i've fixed it can you send a test message", "?"),
    ("The house is on the water with a dock", ","),
    ("Is there a reason we've not spoken this year", "?"),
    ("You got any mail", "?"),
    ("Are you you happy", "?"),
    ("Is ur paper in e morn or aft tmr", "?"),
    ("Almost there", ","),
    ("Do enjoy it", "."),
    ("Okie ü wan meet at bishan", "?"),
    ("You know my weaknesses", "!"),
    ("My sort code is  and acc no is", "."),
    ("Ok lor wat time ü finish", "?"),
    ("Not much", ","),
    ("It's great", "!"),
    ("What are you doing", "?"),
    ("MY FONE WAS ON CHARGE LST NITW WEN U TEXD ME", "."),
    ("No shoot me", "."),
    ("I just got home babe", ","),
    ("Then will they deduct your lesson tmr", "?"),
    ("No worries", ","),
    ("came to look at the flat", ","),
    ("See you in a couple of weeks", "!"),
    ("I'm not sure", ","),
    ("Same here", ","),
    ("Wake up", "!"),
    ("I cant pick the phone right now", "."),
    ("You're the boss and I'm the nanny", "."),
    ("A boy was late 2 home", "."),
    ("if you text on your way to cup stop that should work", "."),
    ("Tell them no need to investigate about me anywhere", "."),
]
