/// REAL eval set v2.1: sentences from the UCI SMS Spam Collection (ham only)
/// whose senders typed the mark themselves -- the mark is the label.
/// Marks: . ? ! plus continuations: "," (text the sender followed with a
/// comma) and an opening quote (introducer phrases like "u say" that real
/// senders followed with a quote; trailing :/- stripped).
/// Stratified 200/150/100/150/38 (638 rows). Charter: EVAL.md at repo root.
/// FROZEN: sentences never edited in a change that also touches engine code.
///
/// Split (seed 7): realCorpusDev misses may be studied; realCorpusTest is
/// HELD OUT -- aggregate score only, never inspect its sentences.

let realCorpusDev: [(text: String, label: String)] = [
    ("Wat ü doing now", "?"),
    ("Good to hear from you", "."),
    ("Please forgive me", "."),
    ("Really sorry", "."),
    ("And sometimes when i open my mouth", ","),
    ("Yes but i dont care", "!"),
    ("how are you", "?"),
    ("Do 1 thing", "!"),
    ("So anythin special happened", "?"),
    ("I miss you", "!"),
    ("Can't take any major roles in community outreach", "."),
    ("At what time are you coming", "."),
    ("Doing nothing", ","),
    ("How are you doing", "?"),
    ("I went to work", "."),
    ("Now thats going to ruin your thesis", "!"),
    ("Busy here", "."),
    ("Can you reply to confirm i've sent this to the right person", "!"),
    ("Cable and internet outage", "."),
    ("Alright if you're sure", ","),
    ("Busy transcribing", "."),
    ("If i not meeting ü all rite then i'll go home lor", "."),
    ("She was supposed to be but couldn't make it", ","),
    ("I'll snatch her purse too", "."),
    ("the windows", ","),
    ("If you're still up", ","),
    ("YEAH WAS A GOODNITE SHAME U NEVA CAME", "!"),
    ("Happy New Year Princess", "!"),
    ("Even if isn't there", ","),
    ("We will meet soon princess", "!"),
    ("Now i'm going for lunch", "."),
    ("Good afternoon", ","),
    ("i 'll tell you if i find anything in my room", "."),
    ("Call me", ","),
    ("Are you finding that job", "?"),
    ("Sweet dreams", ","),
    ("I'll text now", "!"),
    ("Dunno y u ask me", "."),
    ("I'm good", "."),
    ("SAW SCARY MOVIE YEST ITS QUITE FUNNY", "!"),
    ("Anything else", "?"),
    ("Have a lovely holiday", ","),
    ("If you want to mapquest it or something look up", "\""),
    ("You dont have to say if it is uncomfortable", "."),
    ("I got another job", "!"),
    ("So when r u leaving", "?"),
    ("Have you always been saying welp", "?"),
    ("WHO WAS THE MSG 4", "?"),
    ("When should I bring the mini cheetos bag over", "?"),
    ("swhrt how u dey", ","),
    ("Why do they get all the good stuff", "?"),
    ("As I entered my cabin my PA said", ","),
    ("Wish we were together right now", "!"),
    ("How was ur day", "?"),
    ("They finally came to fix the ceiling", "."),
    ("Did you catch the bus", "?"),
    ("Read carefully", "\""),
    ("Just got up", "."),
    ("Ok goodnight then", "."),
    ("Got wat", "?"),
    ("Night night sweet", "!"),
    ("She said", ","),
    ("U GOIN OUT 2NITE", "?"),
    ("i just wanted my bed", "!"),
    ("Does cinema plus drink appeal tomo", "?"),
    ("And stop wondering", "\""),
    ("Yeah do", "!"),
    ("Are you ready to moan and scream in ecstasy", "?"),
    ("I love to wine and dine my lady", "!"),
    ("Superb Thought", "\""),
    ("finally lol", "."),
    ("Oooh I got plenty of those", "!"),
    ("Hey come online", "!"),
    ("You remember me today", "."),
    ("Where's mummy's boy", "?"),
    ("Dunno dat's wat he told me", "."),
    ("Watch lor", "."),
    ("Hi Princess", "!"),
    ("Gotta drive back to sd from la", "."),
    ("R u over scratching it", "?"),
    ("i will pray", "!"),
    ("How did you sleep", "?"),
    ("Grazed my knees and everything", "!"),
    ("I can't believe how attached I am to seeing you every day", "."),
    ("Once free call me sir", "."),
    ("Thank you", "."),
    ("You'd like that wouldn't you", "?"),
    ("Remember all the furniture is yours", "."),
    ("I'm exhausted", "."),
    ("Geoenvironmental implications", "."),
    ("Just glad to be talking to you", "."),
    ("I miss you already", ","),
    ("Have you bookedthe hut", "?"),
    ("1's finish meeting call me", "."),
    ("I have no money 4 steve mate", "!"),
    ("I didn't mean o send that to you", "!"),
    ("Hasn't that been the pattern recently crap weekends", "?"),
    ("Are you in the library", "?"),
    ("all the same stuff as before", ","),
    ("U free on sat rite", "?"),
    ("No need lar", "."),
    ("Wishing you and your family Merry", "\""),
    ("After lunch she invited me to her apartment", "."),
    ("No problem", "."),
    ("a part of Ur heart is my life", ","),
    ("Be sure to check your yahoo email", "."),
    ("If you want the type i sent boye", ","),
    ("Good evening Sir", ","),
    ("You're right", "!"),
    ("Sorry pa", ","),
    ("Are you around tonght wen this girl comes", "?"),
    ("send dis msg to all ur friends", "."),
    ("Gd luck", "!"),
    ("WHEN THE FIRST STRIKE IS A RED ONE", "."),
    ("HMM yeah if your not too grooved out", "!"),
    ("I get home tomorrow at 5ish", "."),
    ("Pink;u r so swt", "."),
    ("Anything lar then ü not going home 4 dinner", "?"),
    ("Man this bus is so so so slow", "."),
    ("It may not add years to your Life", "!"),
    ("WHO ARE YOU SEEING", "?"),
    ("I sent them", "."),
    ("Ultimately tor motive tui achieve korli", "."),
    ("Can i get your opinion on something first", "?"),
    ("Ya very nice", "."),
    ("Did you call me just now ah", "?"),
    ("Hope you had a good day", "."),
    ("Are you not around or just still asleep", "?"),
    ("Seem ok", "?"),
    ("Don't Think About", "\""),
    ("Go until jurong point", ","),
    ("Same time + place as always", "?"),
    ("No need for the drug anymore", "."),
    ("Still looking for a job", "."),
    ("BTW you're my alibi", "."),
    ("I go now", ","),
    ("I am in escape theatre now", "."),
    ("Haha awesome", ","),
    ("Only buy 2 meals ONLY 2", "."),
    ("'An Amazing Quote''", "\""),
    ("n My Wife", ","),
    ("we have to get up at 7am every day", "!"),
    ("When are you going to ride your bike", "?"),
    ("Is it a monster", "!"),
    ("are you in college", "?"),
    ("U dun wan it's ok", "."),
    ("R u there in home", "."),
    ("No probs hon", "!"),
    ("Also north carolina and texas atm", ","),
    ("Txt back if u can", "."),
    ("'' ''OK''", ","),
    ("You flippin your shit yet", "?"),
    ("Bc is the only way to shrink them", "."),
    ("But don't", "\""),
    ("Contact joke ogunrinde", ","),
    ("Next mon can", "?"),
    ("Even my Colleagues did not wish", "."),
    ("Do you remember me", "."),
    ("How was last night", "?"),
    ("Will expect you whenever you text", "!"),
    ("Should have stayed at home", "!"),
    ("Iyo kothi chikku", ","),
    ("Hope you are having a great day", "."),
    ("You know", ","),
    ("Ü dun wan to watch infernal affair", "?"),
    ("But actually it is", ","),
    ("I'll jus wait 4 e rain 2 stop", "."),
    ("Hi hope u r both ok", ","),
    ("Water logging in desert", "."),
    ("U better respond else we shall come back", "."),
    ("in AUGUST", "!"),
    ("I'm wylie", ","),
    ("I'm gonna leave a note that says its all robs fault", "."),
    ("Damn it", "!"),
    ("That‘s the thing with apes", ","),
    ("The house is on the water with a dock", ","),
    ("Yeah hopefully", ","),
    ("Or you going to take", "?"),
    ("idc get over here", ","),
    ("I've told him that i've returned it", "."),
    ("U slept v late yest", "?"),
    ("where did you take test", "?"),
    ("Love isn't a decision", ","),
    ("Wine * good idea just had a slurp", "!"),
    ("she was asking wats matter", "?"),
    ("Thanx 4 e tau sar piah it's quite nice", "."),
    ("U eat already", "?"),
    ("Lets meet bhaskar", ","),
    ("Hmm ok", ","),
    ("I'll make a trip to Ptbo for that", "."),
    ("All done", "?"),
    ("How would you like to be treated", "?"),
    ("R ü comin back for dinner", "?"),
    ("I love you too", ","),
    ("You didnt complete your gist oh", "."),
    ("Are you angry with me", "."),
    ("It will stop on itself", "."),
    ("Thk of u oso boring wat", "."),
    ("And if you can send me bimbo and ugo's numbers", ","),
    ("Today is", "\""),
    ("You have got tallent but you are wasting", "."),
    ("Cud do", "."),
    ("I cant pick the phone right now", "."),
    ("Today is her birthday", "."),
    ("Come round", ","),
    ("Do you think of me", "?"),
    ("Maybe westshore or hyde park village", ","),
    ("Want to finally have lunch today", "?"),
    ("I'm sorry your room was so embarassing", "."),
    ("convey regards to achan", ","),
    ("I misss youuuuu", "!"),
    ("Happy new years melody", "!"),
    ("I'm not gonna pay your ticket", ","),
    ("on hen night", "."),
    ("Pls send me a comprehensive mail about who i'm paying", ","),
    ("Yeah I think my usual guy's still passed out from last night", ","),
    ("That's good", ","),
    ("Usf I guess", ","),
    ("Almost there", ","),
    ("and TRUE Friends STaY forever beyond words", ","),
    ("What are you doing", "?"),
    ("I think i've fixed it can you send a test message", "?"),
    ("You know what i mean", "."),
    ("Ard wat time will u reach", "?"),
    ("Have one with loads of reasons to smile", "."),
    ("Red;i'm in luv wid u", "."),
    ("Y she so funny we bluff her 4 wat", "."),
    ("2 celebrate my bday", ","),
    ("If urgnt", ","),
    ("I‘ve got some salt", ","),
    ("and ur rite here its too cold", ","),
    ("Good morning", ","),
    ("Ever green quote ever told by Jerry in cartoon", "\""),
    ("What u talking bout early morning", "?"),
    ("IM FINE BABES AINT BEEN UP 2 MUCH THO", "!"),
    ("The word", "\""),
    ("Yeah why not", ","),
    ("I felt Shit this morning but i think i am just hungover", "!"),
    ("What school and wat r ur plans", "."),
    ("Where are you", "?"),
    ("By the grace of God", ","),
    ("u say", "\""),
    ("IJUST TALKED TO YOUR MUM ALL MORNING", "!"),
    ("FR'NDSHIP is like a needle of a clock", "."),
    ("You call him and tell now infront of them", "."),
    ("Accept life the way it comes", "!"),
    ("ll always be there", ","),
    ("I adore you", ","),
    ("Don know", "."),
    ("im really missing u what have u been up to", "?"),
    ("Working towards getting back that net for mummy", "?"),
    ("Omg I missed you so much today", "."),
    ("Two fundamentals of cool life", "\""),
    ("We'll be at the Guild", "."),
    ("You set my soul on fire", "."),
    ("il download", ","),
    ("First the tests", ","),
    ("Nice talking to you", "!"),
    ("Go head", ","),
    ("want ya", ","),
    ("Tell me the language", "."),
    ("Not matured 8", "."),
    ("Jus chillaxin", ","),
    ("Did you run out of time on your cell already", "?"),
    ("CERI U REBEL", "!"),
    ("Thk we juz go accordin to wat we discussed yest lor", ","),
    ("Bit far", "!"),
    ("Yeah there's barely enough room for the two of us", ","),
    ("Any job prospects", "?"),
    ("I am back", "."),
    ("hiya hows it going in sunny africa", "?"),
    ("Are you bringing money", "."),
    ("always give response 2 who cares 4 U", "\""),
    ("Enjoy it", "."),
    ("I bet the brothas are all chasing you", "!"),
    ("maybe all are feeling the same", ","),
    ("yesterday i was in cbe", "."),
    ("It'll be tough", ","),
    ("Ugh y can't u just apologize", ","),
    ("Change that sentence into", "\""),
    ("She'll be ok", "."),
    ("Now project pa", "."),
    ("Uncle G", ","),
    ("Are you home yet", "?"),
    ("Me not waking up until 4 in the afternoon", ","),
    ("Yesterday its with me only", "."),
    ("Good morning princess", "!"),
    ("When u wanna", "?"),
    ("I thought slide is enough", "."),
    ("Kate jackson rec center before 7ish", ","),
    ("U gd lor go shopping i got stuff to do", "."),
    ("Yeah go on then", ","),
    ("Wot about", "?"),
    ("And I ate 1 too many slices of pizza yesterday", "."),
    ("Sweet heart how are you", "?"),
    ("I borrow ur bag ok", "."),
    ("By march ending", ","),
    ("Miss ya", ","),
    ("Love it", "!"),
    ("They can try", "!"),
    ("Is your internet down", "?"),
    ("My Parents forgot n so did my Kids", "."),
    ("am seeing in online shop so that i asked", "."),
    ("I shoot big loads so get ready", "!"),
    ("But because I love the people in my life", ","),
    ("Good good", ","),
    ("MY FONE WAS ON CHARGE LST NITW WEN U TEXD ME", "."),
    ("GOD ASKED", ","),
    ("aight we can pick some up", ","),
    ("See I'm not crazy", "."),
    ("If you must pack food", ","),
    ("U will always be ignorant", "."),
    ("God picked up a flower and dippeditinaDEW", ","),
    ("Y DIDNT U TXT ME", "?"),
    ("Should i send you naughty pix", "?"),
    ("Sounds great", "!"),
    ("Did you have a good birthday", "?"),
    ("It sucks being ill at xmas", "!"),
    ("Or legal", "."),
]

let realCorpusTest: [(text: String, label: String)] = [
    ("Your installation will happen within 3 days", "."),
    ("Me too", "!"),
    ("On the way home", "."),
    ("id b better if i had a few drinks down me 2", "!"),
    ("No did you check", "?"),
    ("BEEN SLEEPING ON DA SOFA ALL DAY", ","),
    ("There is no use in joining finance", "."),
    ("It's great", "!"),
    ("A swt thought", "\""),
    ("Painful words", "\""),
    ("Hello madam how are you", "?"),
    ("I dont knw pa", ","),
    ("As in missionary hook up", ","),
    ("No I'm good for the movie", ","),
    ("Thanks you for making my birthday truly memorable", "."),
    ("Cos my lect finishes in an hour anyway", "."),
    ("should you be texting right now", "?"),
    ("Hello my little party animal", "!"),
    ("U all wanna meet 4 dinner at nìte", "?"),
    ("No openings for that room 'til after thanksgiving without an upcharge", "."),
    ("Hope you've settled in for the new school year", "."),
    ("But I'm on a diet", "."),
    ("Meeting u is my work", "."),
    ("Men always needs a beautiful", ","),
    ("At home can do my stuff or watch tv wat", "."),
    ("Could you tell me how to do that", "?"),
    ("We r off at 9pm", "."),
    ("Made up for Friday and stuffed myself like a pig yesterday", "."),
    ("Bt innu mundhe lyf ali halla ke bilo (marriage)program edhae", ","),
    ("I thk e nite scenery not so nice leh", "."),
    ("That sucks", "."),
    ("Have you heard about that job", "?"),
    ("My one from wiv hello caroline at the end is my favourite", "."),
    ("Or u wan 2 go elsewhere", "?"),
    ("I can do that", "!"),
    ("I need srs model pls send it to my mail id pa", "."),
    ("HELLO PEACH", "!"),
    ("Make loads of money on ebay or something", "."),
    ("You at mu", "?"),
    ("I am a one woman man", "!"),
    ("That means you got an A in epi", ","),
    ("Good stuff", ","),
    ("I jog", "."),
    ("CHEERS LOU", "!"),
    ("The goverment expects us to", "\""),
    ("8 at the latest", ","),
    ("No it's waiting in e car dat's bored wat", "."),
    ("When are u wrking nxt", "?"),
    ("No it will reach by 9 only", "."),
    ("How about clothes", ","),
    ("You don‘t know either", "."),
    ("Kind of person who needs a smile to brighten his day", "!"),
    ("A few bday drinks 2 nite", "."),
    ("I'm in school so if we rush we go hungry", "."),
    ("Hows the champ just leaving glasgow", "!"),
    ("True lov n care wil nevr go unrecognized", "."),
    ("Infact happy new year", "."),
    ("Lololo ok next time then", "!"),
    ("when you thought i had left you", ","),
    ("Nah can't help you there", ","),
    ("Shhhhh nobody is supposed to know", "!"),
    ("Still here at my moms", "."),
    ("Com you see", "!"),
    ("It's ok i wun b angry", "."),
    ("Then u told her", "?"),
    ("Didn't try", ","),
    ("Tell you what", ","),
    ("life alle mone", ","),
    ("How is a pretty lady like you single", "?"),
    ("Mystery solved", "!"),
    ("I enjoy watching and playing football and basketball", "."),
    ("Perhaps * is much easy give your account identification", ","),
    ("On way back now", ","),
    ("My Parents", ","),
    ("You got called a tool", "?"),
    ("Did you get my text", "."),
    ("She failed", "."),
    ("Oh yeah", "!"),
    ("Must book a not huh", "?"),
    ("Does he miss me", "?"),
    ("came to look at the flat", ","),
    ("I went to bed not too long after i spoke with you", "."),
    ("U finish dinner already", "?"),
    ("So wats ur opinion abt him and how abt is character", "?"),
    ("or on wednesday", "."),
    ("We'd like to know if you were satisfied with the experience", "."),
    ("Noooooooo please", "."),
    ("Okey dokey", ","),
    ("What part of", "\""),
    ("HEY MATE", "!"),
    ("Another IDIOT", "\""),
    ("Ü like gd looking guys not me", "."),
    ("Wait that's still not all that clear", ","),
    ("It has issues right now", "."),
    ("Sorry battery died", ","),
    ("Its all about making that money", "."),
    ("Single line with a big meaning", "\""),
    ("Are you coming to day for class", "."),
    ("What of that day", "?"),
    ("Oh dear", ","),
    ("I'm goin2bed now", "."),
    ("Is ur lecture over", "?"),
    ("You in your room", "?"),
    ("And i'm tired", "."),
    ("Great escape or wetherspoons", "?"),
    ("Very hurting n meaningful lines ever", "\""),
    ("How are you by the way", "?"),
    ("See you at some point", "!"),
    ("Will ü b going to esplanade fr home", "?"),
    ("Dun disturb u liao u cleaning ur room", "."),
    ("Hope ur day * good", "!"),
    ("You know I simply must see", "!"),
    ("is coming", "."),
    ("What time", "."),
    ("I'm not smoking while people use", "\""),
    ("Did you ever figure out where your going for New Years", "?"),
    ("My painful personal thought", "\""),
    ("just standing", "."),
    ("Been running but only managed 5 minutes and then needed oxygen", "!"),
    ("I think of you", ","),
    ("How goes that day", "?"),
    ("So ü'll be submitting da project tmr rite", "?"),
    ("like you are the KING", "\""),
    ("you there", "?"),
    ("Are you in castor", "?"),
    ("By the way how ru and how is the house", "?"),
    ("I'm in church now", ","),
    ("A cute thought for friendship", "\""),
    ("Wat u doing there", "?"),
    ("which hides thousands of secrets", "."),
    ("happy bakrid", "!"),
    ("What time are  and that going", "?"),
    ("Merry christmas to u too annie", "!"),
    ("one thing about past is", "\""),
    ("Have nice day da", "."),
    ("y r u smiling", "?"),
    ("But will call you for sure", "."),
    ("Ü still got lessons", "?"),
    ("wiskey Brandy Rum Gin Beer Vodka Scotch Shampain Wine", "\""),
    ("Be warned Sprint is dead slow", "."),
    ("tel me who r u", "?"),
    ("Well she's in for a big surprise", "!"),
    ("Just making dinner", ","),
    ("Oh yes I can speak txt 2 u no", "!"),
    ("Tell me something exciting has happened there", "?"),
    ("Ill give u a clue", ","),
    ("I didn't mean to do that", "."),
    ("Sorry I flaked last night", ","),
    ("Not sure yet", ","),
    ("Then u going ikea str aft dat", "?"),
    ("Hows london treatin' ya treacle", "?"),
    ("Why didn't u call on your lunch", "?"),
    ("Thought xuhui told you", "?"),
    ("Is there a dog or cat in the house", "?"),
    ("Where are you call me", "."),
    ("You know my old Dom I told you about yesterday", "?"),
    ("Yen madodu", ","),
    ("It was messy wednesday", ","),
    ("Hey so tmr i meet you at 1pm orchard mrt", "?"),
    ("Hey sweet", ","),
    ("I just got home babe", ","),
    ("Are you sure you don't mean", "\""),
    ("But call me after some time", "."),
    ("I keep seeing weird shit and bein all", "\""),
    ("So what's happenin wit ola", "?"),
    ("I'll text carlos and let you know", ","),
    ("Your priority is constantly", "\""),
    ("The gas station is like a block away from my house", ","),
    ("Which brand", "?"),
    ("Were you on a friends net", "?"),
    ("Can't wait for u to come home", "."),
    ("Take it as a practice for the real thing", "."),
    ("Do you know of anyplaces doing something", "?"),
    ("I have avalarr now", "."),
    ("Hows everyone else", "?"),
    ("What time is ur flight tmr", "?"),
    ("ur mum still Thinks we will get 2GETHA", "!"),
    ("Your opinion about me", "?"),
    ("No its Brdget Jones", "!"),
    ("Dear Sir", ","),
    ("Height of", "\""),
    ("Per month", "."),
    ("Omg how did u know what I ate", "?"),
    ("Wat's my dear doing", "?"),
    ("we've planned to go shopping and to concert tmw", ","),
    ("Carlos is down but I have to pick it up from him", ","),
    ("How was your weekend", "?"),
    ("Sorry that took so long", ","),
    ("Just missed train cos of asthma attack", ","),
    ("A Boy loved a gal", "."),
    ("Er yeah", ","),
    ("Its not that time of the month nor mid of the time", "?"),
    ("I'm back", ","),
    ("HOPE URFEELING BETTERSN LUV", "!"),
    ("Cardiff is still here and still cold", "!"),
    ("go to a movie AND be home by midnight", ","),
    ("1 U CHEERED ME UP", "!"),
    ("So gd", ","),
    ("You walk around in", "\""),
    ("You could text at bus stop", "."),
    ("Wat u doing", "?"),
    ("Good journey", "!"),
    ("Was it something u ate", "?"),
    ("What do you do", "?"),
    ("Thats cool", "."),
    ("We are countin down to aburo", "."),
    ("I need to stretch open your pussy", "!"),
    ("Oh is it", "!"),
    ("I so need that", "."),
    ("Are you there now", "?"),
    ("What are you thinking about me", "?"),
    ("hw abt u", "?"),
    ("And you", "!"),
    ("Alright omw", ","),
    ("Ask g or iouri", ","),
    ("I am real", ","),
    ("Hey babe", ","),
    ("Garbage bags", ","),
    ("First time you saw me in class", "."),
    ("Short But Cute", "\""),
    ("Yeah we wouldn't leave for an hour at least", ","),
    ("I made it home and my constant thought is of you", ","),
    ("That's great", "."),
    ("Wrong phone", "!"),
    ("I weighed myself and I lost more weight", "!"),
    ("How were the photos were useful", "?"),
    ("I will search online and let you know", "."),
    ("Can a not", "?"),
    ("His father", "\""),
    ("I've seen it", "."),
    ("I'll put on the case and get him to sort it out", "!"),
    ("I am late", ","),
    ("And how many times can it be used", "."),
    ("How's your arm", "?"),
    ("gauti and sehwag out of odi series", "."),
    ("But relax", ","),
    ("But my family not responding for anything", "."),
    ("This is just wishing you a great day", "."),
    ("See you there", "!"),
    ("id luv 2 but ive had 2 go home", "!"),
    ("I wake", ","),
    ("Too late", "."),
    ("So how many days since then", "?"),
    ("MY CAKE TASTS LUSH", "!"),
    ("Reply Toll Free with Yes or No", "."),
    ("The table's occupied", ","),
    ("I just lov this line", "\""),
    ("Hey did u ever vote for the next themes", "?"),
    ("Evening * v good if somewhat event laden", "."),
    ("Start from the last page and collect from the bottom up", "."),
    ("I'm really not hungry tho", "."),
    ("what is your account number", "?"),
    ("You are everywhere dirt", ","),
    ("All the best with it", "."),
    ("This pain couldn't have come at a worse time", "."),
    ("|| Do u want | to join me with sts later", "?"),
    ("I thk ü gotta go home by urself", "."),
    ("We can think of something to do he he", "!"),
    ("I love you sooo much", ","),
    ("U can tell me all about", "!"),
    ("Is xy going 4 e lunch", "?"),
    ("what happend", "?"),
    ("Is that what time you want me to come", "?"),
    ("Okie ü wan meet at bishan", "?"),
    ("I'll bring my tape measure fri", "!"),
    ("U know me well", "."),
    ("I am in your office na", "."),
    ("Have a great day", "."),
    ("Aft some thinking mayb most prob i'll go", "."),
    ("How dare you stupid", "."),
    ("May be ur frnds or classmates", "?"),
    ("I feel nauseous", "."),
    ("but watever u shared should be true", "\""),
    ("Is he being an idiot", "?"),
    ("They can get lost", ","),
    ("I am here waiting when you come back", ","),
    ("U bathe already", "?"),
    ("Oh ho", "."),
    ("Oh all have to come ah", "?"),
    ("If none can do it", ","),
    ("I hope your next space gives you everything you want", "."),
    ("SIB never asks for sensitive information like Passwords", ","),
    ("Haf u eaten", "?"),
    ("Bright light", "!"),
    ("I where got zhong se qing you", "?"),
    ("I know you are", "."),
    ("Hope tonight isnt too bad as well but its rock night shite", "."),
    ("Did he say how fantastic I am by any chance", ","),
    ("Do you crave me", "?"),
    ("Dunno leh", ","),
    ("My planning usually stops at", "\""),
    ("Of course", "!"),
    ("Funny fact Nobody teaches volcanoes 2 erupt", ","),
    ("All are Gods blessings", "!"),
    ("Luckily i didn't have a starring role like you", "!"),
    ("Not getting anywhere with this damn job hunting over here", "!"),
    ("U need my presnts always bcz U cant mis love", "."),
    ("Just checking in on you", "."),
    ("I never realized that you were so embarassed by your accomodations", "."),
    ("Then cant get da laptop", "?"),
    ("Fighting with the world is easy", ","),
    ("Thanks a lot for your wishes on my birthday", "."),
    ("have got * few things to do", "."),
    ("Im just wondering what your doing right now", "?"),
    ("Xy suggest one not me", "."),
    ("would you like to go on a dinner date next week", "?"),
    ("Sorry sir", ","),
    ("Cos my sis not done yet", "."),
    ("Tell u aft i ask her", "."),
    ("will you like to be spoiled", "?"),
    ("I take it all back ur not a freak", "!"),
    ("I am in meeting sir", "."),
    ("You are eldest know", "."),
    ("Waqt se pehle or naseeb se zyada kisi ko kuch nahi milta", ","),
    ("My life Means a lot to me", ","),
    ("Can you feel it", "?"),
    ("Yes baby", "!"),
    ("Got any exciting karaoke type activities planned", "?"),
    ("Any luck with sorting out the car", "?"),
]
