/// REAL eval set: 500 sentences from the UCI SMS Spam Collection (ham
/// messages only) whose senders typed the terminal mark themselves --
/// the mark is the label. Stratified 250/150/100 (. ? !) from a natural
/// distribution of roughly 66/25/9; real-world scores skew higher since
/// the default guess is a period.
/// FROZEN: never edit this file in a change that also touches engine
/// rules. Teaching to the test invalidates the number.
let realCorpus: [(text: String, label: String)] = [
    ("Are you still playing with gautham", "?"),
    ("You never hear unless you book it", "."),
    ("Actually i'm waiting for 2 weeks when they start putting ad", "."),
    ("Please protect yourself from e-threats", "."),
    ("i'm also fine:)when will you complete the course", "?"),
    ("U studying in sch or going home", "?"),
    ("Done it but internet connection v slow and can‘t send it", "."),
    ("Call me 4 wat", "?"),
    ("He's going to call you", "."),
    ("This is really starting to become an issue", "."),
    ("Wat u doing there", "?"),
    ("Back in yo", "."),
    ("Great escape or wetherspoons", "?"),
    ("Yo, the game almost over", "?"),
    ("Doing my masters", "."),
    ("Or u ask they all if next sat can a not", "."),
    ("Do you know when dad will be back", "?"),
    ("Why do they get all the good stuff", "?"),
    ("Of course nothing happen lar", "."),
    ("But have to pay", "."),
    ("Can i get your opinion on something first", "?"),
    ("You dont know you jabo me abi", "."),
    ("Please forgive me", "."),
    ("She would have been worse and its gastroenteritis", "."),
    ("JADE ITS PAUL", "."),
    ("said kiss, kiss, i can't do the sound effects", "!"),
    ("I am at Truro Hospital on ext", "."),
    ("Hey elaine, is today's meeting still on", "?"),
    ("U still painting ur wall", "?"),
    ("LOOK AT THE FUCKIN TIME", "."),
    ("Can you pls send me that company name", "."),
    ("I attended but nothing is there", "."),
    ("Sounds great", "!"),
    ("I have listed da", "."),
    ("K still are you loving me", "."),
    ("Mmm thats better now i got a roast down me", "!"),
    ("All done, all handed in", "."),
    ("Omw back to tampa from west palm, you hear what happened", "?"),
    ("Ya very nice", "."),
    ("All the best in your mcat", "."),
    ("Yes :)it completely in out of form:)clark also utter waste", "."),
    ("I thk she muz c us tog then she believe", "."),
    ("I am in tirupur da, once you started from office call me", "."),
    ("Thank you for the pics", "."),
    ("Are you being lazy and bleak, hmmm", "?"),
    ("Cbe is really good nowadays:)lot of shop and showrooms:)city is shaping good", "."),
    ("Forgot you were working today", "!"),
    ("Tell me pa", "."),
    ("do you think you could send me some pix", "?"),
    ("Good journey", "!"),
    ("Got a roast in a min lovely i shall enjoy that", "!"),
    ("Under the sea, there lays a rock", "."),
    ("Fr dinner", "?"),
    ("Doesn't your heart ache without me", "?"),
    ("Thanks again, especially for the duvet (not a predictive text word)", "."),
    ("i will pray", "!"),
    ("Ok da, i already planned", "."),
    ("How goes you day, my love", "?"),
    ("How goes it", "?"),
    ("Another night then", "."),
    ("Save yourself the stress", "."),
    ("Tell me they're female :V how're you throwing in", "?"),
    ("N u still can act so real", "."),
    ("Dun wan 2 distract u also", "."),
    ("Sorry, I'll call later in meeting", "."),
    ("But my family not responding for anything", "."),
    ("pls do me a favour", "."),
    ("Once you pick that number the pin will display okay", "!"),
    ("First answer my question", "."),
    ("I cant wait to see you", "!"),
    ("Men always needs a beautiful, intelligent, caring, loving, adjustable, cooperative wife", "."),
    ("I like cheap", "!"),
    ("When did dad get back", "."),
    ("I went to bed not too long after i spoke with you", "."),
    ("That would be great", "."),
    ("Haf u eaten", "?"),
    ("My uncles in Atlanta", "."),
    ("Ugh my leg hurts", "."),
    ("how are you", "?"),
    ("What's your room number again", "?"),
    ("* Am on a train back from northampton so i'm afraid not", "!"),
    ("Good to see you", "!"),
    ("So why didnt you holla", "?"),
    ("When're you guys getting back", "?"),
    ("It's ok i wun b angry", "."),
    ("Good afternoon, my love", "."),
    ("Would really appreciate if you call me", "."),
    ("Where you at/your phone dead yet", "?"),
    ("Why didn't u call on your lunch", "?"),
    ("Got u a plate", "."),
    ("Can a not", "?"),
    ("Not sure the  thing will be resolved, tho", "."),
    ("You know my weaknesses", "!"),
    ("U dun like ah", "?"),
    ("Yes princess", "!"),
    ("Not matured 8", "."),
    ("Is it a monster", "!"),
    ("But we won't go there", "!"),
    ("Have a great day", "."),
    ("Thank you baby", "!"),
    ("Hey there", "!"),
    ("wot has u inmind 4 recreation dis eve", "?"),
    ("Awesome, think we can get an 8th at usf some time tonight", "?"),
    ("Take care", "."),
    ("Pass dis to all ur contacts n see wat u get", "!"),
    ("See you in a couple of weeks", "!"),
    ("Sorry de i went to shop", "."),
    ("MY NEW YEARS EVE WAS OK", "."),
    ("In case huiming havent sent u my num", "."),
    ("Sorry sent blank msg again", "."),
    ("Booked ticket for pongal", "?"),
    ("Sorry sir, i will call you tomorrow", "."),
    ("What did they say in the terms and conditions", "?"),
    ("Desires- u going to doctor 4 liver", "."),
    ("Early bird", "!"),
    ("SOUNDS LIKEYOUR HAVIN GR8FUN J", "!"),
    ("You should have told me earlier", "."),
    ("HOPE URFEELING BETTERSN LUV", "!"),
    ("But all in all its a great place", "."),
    ("She failed", "."),
    ("Aight, you close by or still down around alex's place", "?"),
    ("Com you see", "!"),
    ("On way back now, can i call in", "?"),
    ("Thanks for loving me so", "."),
    ("I am waiting for you", "."),
    ("Daddy will make you scream with pleasure", "!"),
    ("Still here at my moms", "."),
    ("2mro i am not coming to gym machan", "."),
    ("Gud mrng", "!"),
    ("What do you do", "?"),
    ("Sup, you in town", "?"),
    ("till den,", "."),
    ("Omg Joanna is freaking me out", "."),
    ("Haven't seen my facebook, huh", "?"),
    ("C U THIS WK", "?"),
    ("He strongly feels that you need to sacrifice to keep me here", "."),
    ("Sir, i am waiting for your call", "."),
    ("Buzz your chest", "?"),
    ("Why are u up so early", "?"),
    ("I don't think he has spatula hands", "!"),
    ("I came hostel", "."),
    ("Happy New Year", "."),
    ("I just got my invitation but i had to apologise", "."),
    ("Can you do online transaction", "?"),
    ("As if i wasn't having enough trouble sleeping", "."),
    ("Received, understood n acted upon", "!"),
    ("Super msg da:)nalla timing", "."),
    ("What is this 'hex' place you talk of", "?"),
    ("Hope tonight isnt too bad as well but its rock night shite", "."),
    ("Schools already closed for tomorrow", "."),
    ("Just to let you know you are missed and thought off", "."),
    ("I know girls always safe and selfish know i got it pa", "."),
    ("Hey did u ever vote for the next themes", "?"),
    ("Love it", "!"),
    ("For real when u getting on yo", "?"),
    ("Goodmorning, today i am late for 1hr", "."),
    ("When are u wrking nxt", "?"),
    ("\"Hi darlin did youPhone me", "?"),
    ("He v naughty make until i v wet", "."),
    ("U all wanna meet 4 dinner at nìte", "?"),
    ("No plans yet", "."),
    ("That's ok", "."),
    ("She askd me 4 lunch", "."),
    ("We are at grandmas", "."),
    ("Hey now am free you can call me", "."),
    ("the is deliver by the end of the month", "."),
    ("Shall i tell you like the pendent", "?"),
    ("So there's a ring that comes with the guys costumes", "."),
    ("are you in college", "?"),
    ("We made it", "!"),
    ("How many beers shall i get", "?"),
    ("So what's happenin wit ola", "?"),
    ("I just got home babe, are you still awake", "?"),
    ("I tot u reach liao", "."),
    ("DO U REMEMBER ME FROM BARMED", "?"),
    ("My supervisor find 4 me one lor i thk his students", "."),
    ("pls do me a favor", "."),
    ("U so free wan 2 help me", "?"),
    ("Taka lor", "."),
    ("Lol you forgot it eh", "?"),
    ("Yo my trip got postponed, you still stocked up", "?"),
    ("Thanx 4 printing n handing it up", "."),
    ("Why you Dint come with us", "."),
    ("I love your ass", "!"),
    ("Am ploughing my way through a pile of ironing", "!"),
    ("Hope your doing ok", "."),
    ("or u have no role in my life", "."),
    ("ok take care", "."),
    ("Ready for more shopping tho", "!"),
    ("ok you're forgiven", "!"),
    ("How were the photos were useful", "?"),
    ("Did enjoy concert", "?"),
    ("I crave you", "."),
    ("No I don't have cancer", "."),
    ("Wat time ü wan today", "?"),
    ("When's yours, i can't remember", "."),
    ("Now u sound like manky scouse boy steve,like", "!"),
    ("By the way how ru and how is the house", "?"),
    ("And also your time off", "?"),
    ("I can't, I don't have her number", "!"),
    ("Hey a parking garage collapsed at university hospital", "."),
    ("Just making dinner, you", "?"),
    ("Sorry * was at the grocers", "."),
    ("Not sad already lar", "."),
    ("fighting with you constantly isn't helping", "."),
    ("Am I the only one who doesn't stalk profiles", "?"),
    ("Don‘t stand to close tho- you‘ll catch something", "!"),
    ("if you text on your way to cup stop that should work", "."),
    ("and owned", "!"),
    ("God's grace has no measure", "."),
    ("if not txt or ring me and we can meet up l8r", "."),
    ("So i asked how's anthony", "."),
    ("Fills me with complete calm and reassurance", "!"),
    ("Then why you came to hostel", "."),
    ("Thanks you for making my birthday truly memorable", "."),
    ("I wonder if you'll get this text", "?"),
    ("Hi, my love", "!"),
    ("Aiyar hard 2 type", "."),
    ("Ü all got how many pages", "?"),
    ("was the party good the other night", "?"),
    ("Am in film ill call you later", "."),
    ("Miss ya, need ya, want ya, love ya", "."),
    ("It's almost noon where your at", "!"),
    ("Hope you are good", "."),
    ("Back in brum", "!"),
    ("Love has one law; Make happy the person you love", "."),
    ("For once in your life be fair", "."),
    ("HI DARLIN HOW WAS WORK DID U GET INTO TROUBLE", "?"),
    ("Lul im gettin some juicy gossip at the hospital", "."),
    ("How much are we getting", "?"),
    ("wiskey Brandy Rum Gin Beer Vodka Scotch Shampain Wine \"KUDI\"yarasu dhina vaazhthukkal", "."),
    ("Are you gonna see him again", "?"),
    ("Sorry again", "!"),
    ("It so happens that there r 2waxsto do wat you want", "."),
    ("How's your arm", "?"),
    ("Are you you happy", "?"),
    ("In fact i need money can you raise me", "?"),
    ("Do you love me", "?"),
    ("So i can stop thinkin about ipad", "."),
    ("What time", "."),
    ("Thanks  and", "!"),
    ("I'll treat you", "!"),
    ("Respectful Regards", "."),
    ("Yes baby", "!"),
    ("PS U no ur a grown up now right", "?"),
    ("i really hoped i wont have to bother you about this", "."),
    ("Sorry dude", "."),
    ("Yeah right", "!"),
    ("I just forgot", "."),
    ("Good morning princess", "!"),
    ("Bright light", "!"),
    ("Including the one at bugis", "."),
    ("15 as trying 2 sort house out, is that ok", "?"),
    ("And if you can send me bimbo and ugo's numbers, ill appreciate", "."),
    ("Goodmorning, today i am late for 2hrs", "."),
    ("I cherish having you as a brother and role model", "."),
    ("Thank you princess", "!"),
    ("Do you have a po box number", "?"),
    ("Wait, do you know if wesleys in town", "?"),
    ("Hey whats up", "?"),
    ("Is that on the telly", "?"),
    ("Spending new years with my brother and his family", "."),
    ("Is fujitsu s series lifebook good", "?"),
    ("I lost 4 pounds since my doc visit last week woot woot", "!"),
    ("R u meeting da ge at nite tmr", "?"),
    ("Ok give me 5 minutes I think I see her", "."),
    ("I appreciate you", "."),
    ("And how many miles", "."),
    ("O ic lol", "."),
    ("There are a lotta childporn cars then", "."),
    ("U Accept me as", "?"),
    ("Hey sexy buns", "!"),
    ("I want kfc its Tuesday", "."),
    ("Sleeping ah", "?"),
    ("HMM yeah if your not too grooved out", "!"),
    ("No I'm in the same boat", "."),
    ("My Wife did'nt wish me", "."),
    ("Annoying isn't it", "."),
    ("Lol your always so convincing", "."),
    ("Hope you are feeling great", "."),
    ("How should I punish you", "?"),
    ("We went there", "."),
    ("Will try", "."),
    ("Oops sorry", "!"),
    ("Do u wan me 2 buy anything go ur house", "?"),
    ("Or lady", "."),
    ("Must I summon you to me all the time now", "?"),
    ("Aight should I just plan to come up later tonight", "?"),
    ("After lunch she invited me to her apartment", "."),
    ("Is ur changes 2 da report big", "?"),
    ("Then John is the NAME of Joy's father", "."),
    ("hope u r avin a good time", "."),
    ("No, don‘t need any receipts—well done", "!"),
    ("Who knew, one day these two will become FREINDS FOREVER", "!"),
    ("K, wat s tht incident", "?"),
    ("Hows everyone else", "?"),
    ("I cant pick the phone right now", "."),
    ("How are you enjoying this semester", "?"),
    ("Hope day off ok", "."),
    ("Good morning pookie pie", "!"),
    ("First one gets in at twelve", "!"),
    ("HOWDY GORGEOUS, HOWU DOIN", "?"),
    ("I need you", "!"),
    ("We jus went sim lim look at mp3 player", "."),
    ("acc no enough", "?"),
    ("I'm gonna Google nearby cliffs now", "."),
    ("This girl doesn't need recovery time", "."),
    ("IM FINE BABES AINT BEEN UP 2 MUCH THO", "!"),
    ("Hows the champ just leaving glasgow", "!"),
    ("I kept telling Mark I'm not a weak sucker", "."),
    ("Hi elaine, is today's meeting confirmed", "?"),
    ("Yes we must speak friday - egg-potato ratio for tortilla needed", "!"),
    ("do you generally date the brothas", "?"),
    ("any problem", "?"),
    ("I'm used to it", "."),
    ("It's so warm", "."),
    ("How did you sleep", "?"),
    ("Red;i'm in luv wid u", "."),
    ("Did you make a tea", "?"),
    ("Hiya, sorry didn't hav signal", "."),
    ("Thank you", "."),
    ("He said t-shirt", "."),
    ("Can you pls send her another friend request", "."),
    ("U still in office", "?"),
    ("47per hour but means no lie in", "!"),
    ("Oh:)as usual vijay film or its different", "?"),
    ("Jordan got voted out last nite", "!"),
    ("Hi where you", "."),
    ("The theory test", "?"),
    ("went to hair cut", "."),
    ("There's no real danger", "."),
    ("In exeter still, but be home about 3", "."),
    ("R u sure they'll understand that", "!"),
    ("Ok omw now, you at castor", "?"),
    ("Just haven't decided where yet eh", "?"),
    ("Two nurses are talking about how fat they are gettin", "."),
    ("You're right", "!"),
    ("Are you alright", "?"),
    ("So how do you handle the victoria island traffic", "."),
    ("Oooooh let there be snow", "."),
    ("Can you plz tell me the ans", "."),
    ("Catching up on some sleep", "."),
    ("Nice talking to you", "!"),
    ("Where are the garage keys", "?"),
    ("wat abt u", "?"),
    ("ITS A LAPTOP TAKE IT WITH YOU", "."),
    ("It shall be fine", "."),
    ("Do ü noe if ben is going", "?"),
    ("She's quite sad", "."),
    ("Will expect you whenever you text", "!"),
    ("Shopping lor", "."),
    ("k:)how about your training process", "?"),
    ("Haha awesome, I've been to 4u a couple times", "."),
    ("Oh thats late", "!"),
    ("Going to take your babe out", "?"),
    ("Its on in engalnd", "!"),
    ("tmorow i am engaged ans its holiday", "."),
    ("Kusruthi 4", "."),
    ("I miss you", "!"),
    ("How come it took you so long to leave for Zaher's", "?"),
    ("Do you know when the result", "."),
    ("i deleted my contact that why", "?"),
    ("Princess, is your kitty shaved or natural", "?"),
    ("You wanna play THAT game, okay", "."),
    ("Still eating", "?"),
    ("I got another job", "!"),
    ("Have nice day da", "."),
    ("may be in pub later", "."),
    ("Are you there now", "?"),
    ("The problem is that my capital never complete", "."),
    ("Am i that much dirty fellow", "?"),
    ("im cool thanx", "."),
    ("How goes that new job", "?"),
    ("Last thing I need is stress", "."),
    ("id b better if i had a few drinks down me 2", "!"),
    ("When are you going to ride your bike", "?"),
    ("What time is your driving on fri", "?"),
    ("JUSWOKE UP IN A BED ON A BOATIN THE DOCKS", "."),
    ("I just need to cash in my nitros", "."),
    ("Do you remember me", "."),
    ("Good afternoon sunshine", "!"),
    ("Pls now", "."),
    ("Both :) i shoot big loads so get ready", "!"),
    ("call you da", "."),
    ("You mean a great deal to me", "."),
    ("If you dont have paracetamol dont worry it will go", "."),
    ("Will purchase d stuff today and mail to you", "."),
    ("Our plans take flight", "!"),
    ("I can't speak, bcaz mobile have problem", "."),
    ("I will be gentle princess", "!"),
    ("\"Life is nothing wen v get everything\"", "."),
    ("Wish i were with you now", "!"),
    ("I'll put on the case and get him to sort it out", "!"),
    ("Wasn't that how you went on your trip", "?"),
    ("Dun thk abt it already", "."),
    ("Keris bin doin a smidgin", "."),
    ("Are you missing me", "?"),
    ("Hi da:)how is the todays class", "?"),
    ("Not that i'm trying to invite myself or anything", "!"),
    ("Are you missing me yet", "?"),
    ("And is there a way you can send shade's stuff to her", "."),
    ("Done wif sleeping", "?"),
    ("So what did the bank say about the money", "?"),
    ("U leh busy w work", "?"),
    ("Wont a Biro do", "?"),
    ("Uncle Abbey", "!"),
    ("All are Gods blessings", "!"),
    ("Great to hear you are settling well", "."),
    ("Hey what's up charles sorry about the late reply", "."),
    ("Lol grr my mom is taking forever with my prescription", "."),
    ("Theyre doing it to lots of places", "."),
    ("Pick ü up at 4 is it", "?"),
    ("After that i wil cme", "."),
    ("Ü go home liao", "?"),
    ("I HAVE MISSED U", "!"),
    ("Hugs and snogs", "!"),
    ("U leh", "?"),
    ("Are your freezing", "?"),
    ("I had askd u a question some hours before", "."),
    ("I misss youuuuu", "!"),
    ("Me i'm not workin", "."),
    ("Thats why i need your help", "."),
    ("Have you registered to vote", "?"),
    ("MY NO", "."),
    ("How much did ur hdd casing cost", "."),
    ("Discussed with your mother ah", "?"),
    ("This phone has the weirdest auto correct", "."),
    ("GIV U DA GOSSIP L8R", "."),
    ("Mark is getting worried", "."),
    ("Am on the uworld site", "."),
    ("HI BABE IM AT HOME NOW WANNA DO SOMETHING", "?"),
    ("Wat's e road name of ur house", "?"),
    ("I am in escape theatre now", "."),
    ("Now only i reached home", "."),
    ("Hello my little party animal", "!"),
    ("not sure where to park", "."),
    ("ll post her out l8r", "."),
    ("How's da rest of da project going", "?"),
    ("I have had difficulties with her phone", "."),
    ("My Parents forgot n so did my Kids", "."),
    ("Any idea what time I should come tomorrow", "?"),
    ("Velly good, yes please", "!"),
    ("By the way, 'rencontre' is to meet again", "."),
    ("Havent planning to buy later", "."),
    ("A cuddle would be lush", "!"),
    ("You are gorgeous", "!"),
    ("Then sell our coins to someone thru paypal", "."),
    ("Mum not going robinson already", "."),
    ("All these things are important", "."),
    ("You have been wonderful and a blessing at all times", "."),
    ("As in different styles", "?"),
    ("\"alright babe, justthought id sayhey", "!"),
    ("If ü dun feel like comin it's ok", "."),
    ("Genius what's up", "."),
    ("He said will cut until i look nice", "."),
    ("Y de asking like this", "."),
    ("How dare you stupid", "."),
    ("So wat time r we meeting tmr", "?"),
    ("Wrong phone", "!"),
    ("Where can download clear movies", "."),
    ("Just opened my email and he's sent me another batch", "!"),
    ("I'm ok wif it cos i like 2 try new things", "."),
    ("Plz call me up before class", "."),
    ("It's great", "!"),
    ("You have a person to give na", "."),
    ("Sorry pa, i dont knw who ru pa", "?"),
    ("You in your room", "?"),
    ("Its here by the way", "."),
    ("Hurry come on before I crash out", "!"),
    ("No probs hon", "!"),
    ("Are you at home, got something to drop in later", "?"),
    ("and TRUE Friends STaY forever beyond words, beyond time", "."),
    ("I think I‘m waiting for the same bus", "!"),
    ("No it's waiting in e car dat's bored wat", "."),
    ("I actually did for the first time in a while", "."),
    ("You are very sexy", "!"),
    ("Crab asked: being my frnd y r u clearing my beautiful footprints", "?"),
    ("See you tomorrow", "!"),
    ("Have a beautiful day", "."),
    ("I'm done", "."),
    ("Oops I was in the shower when u called", "."),
    ("Is xy in ur car when u picking me up", "?"),
    ("Ok lor", "."),
    ("y r u smiling", "?"),
    ("I am waiting machan", "."),
    ("Hi happy birthday", "."),
    ("After that i will keep in touch more", "."),
    ("U in town alone", "?"),
    ("Is it your yahoo boys that bring in the perf", "?"),
    ("Working towards getting back that net for mummy", "?"),
    ("Wine * good idea just had a slurp", "!"),
    ("Esplanade lor", "."),
    ("Meds say take once every 8 hours", "."),
    ("Hope i can meet her", "."),
    ("I tot i told her it's true already", "."),
    ("Have you heard from this week", "?"),
    ("\"Getting tickets 4 walsall tue 6 th march", "."),
    ("No it was cancelled yeah baby", "!"),
    ("Hey so whats the plan this sat", "?"),
    ("Will keep this one", "."),
]
