// GENERATED from eval/v4/completions.tsv by eval/v4/gen-corpus.py -- do not hand-edit.
// Blind-authored keyboard-wide eval v4 (specs/keyboard-eval.md). FROZEN.

struct CompletionCase { let id: String; let sub: String; let context: String; let prefix: String; let acceptable: [String]; let half: String }

// acceptable == ["NONE"] means offering nothing (or only the typed prefix) passes.
let completionCorpus: [CompletionCase] = [
    CompletionCase(id: "cmp-001", sub: "common-word", context: "", prefix: "tomo", acceptable: ["tomorrow", "Tomorrow"], half: "test"),
    CompletionCase(id: "cmp-002", sub: "common-word", context: "", prefix: "beca", acceptable: ["because", "became"], half: "dev"),
    CompletionCase(id: "cmp-003", sub: "common-word", context: "", prefix: "peop", acceptable: ["people", "peoples"], half: "dev"),
    CompletionCase(id: "cmp-004", sub: "common-word", context: "", prefix: "thou", acceptable: ["though", "thought", "thoughts", "thousand"], half: "test"),
    CompletionCase(id: "cmp-005", sub: "common-word", context: "", prefix: "frien", acceptable: ["friend", "friends", "friendly"], half: "test"),
    CompletionCase(id: "cmp-006", sub: "common-word", context: "", prefix: "someth", acceptable: ["something"], half: "dev"),
    CompletionCase(id: "cmp-007", sub: "common-word", context: "", prefix: "weeke", acceptable: ["weekend", "weekends"], half: "dev"),
    CompletionCase(id: "cmp-008", sub: "common-word", context: "", prefix: "birthd", acceptable: ["birthday", "birthdays"], half: "test"),
    CompletionCase(id: "cmp-009", sub: "common-word", context: "", prefix: "pictur", acceptable: ["picture", "pictures"], half: "test"),
    CompletionCase(id: "cmp-010", sub: "common-word", context: "", prefix: "restau", acceptable: ["restaurant", "restaurants"], half: "test"),
    CompletionCase(id: "cmp-011", sub: "common-word", context: "", prefix: "everyth", acceptable: ["everything"], half: "dev"),
    CompletionCase(id: "cmp-012", sub: "common-word", context: "", prefix: "import", acceptable: ["important", "importance"], half: "dev"),
    CompletionCase(id: "cmp-013", sub: "common-word", context: "", prefix: "diffe", acceptable: ["different", "difference", "differently"], half: "dev"),
    CompletionCase(id: "cmp-014", sub: "common-word", context: "", prefix: "quest", acceptable: ["question", "questions"], half: "test"),
    CompletionCase(id: "cmp-015", sub: "common-word", context: "", prefix: "worki", acceptable: ["working"], half: "test"),
    CompletionCase(id: "cmp-016", sub: "common-word", context: "", prefix: "Tomo", acceptable: ["Tomorrow"], half: "dev"),
    CompletionCase(id: "cmp-017", sub: "common-word", context: "", prefix: "schoo", acceptable: ["school", "schools"], half: "dev"),
    CompletionCase(id: "cmp-018", sub: "common-word", context: "", prefix: "compu", acceptable: ["computer", "computers", "computing"], half: "test"),
    CompletionCase(id: "cmp-019", sub: "common-word", context: "", prefix: "favo", acceptable: ["favorite", "favourite", "favor", "favour"], half: "dev"),
    CompletionCase(id: "cmp-020", sub: "common-word", context: "", prefix: "iph", acceptable: ["iPhone", "iphone"], half: "test"),
    CompletionCase(id: "cmp-021", sub: "long-word", context: "", prefix: "approxim", acceptable: ["approximately", "approximate", "approximation"], half: "dev"),
    CompletionCase(id: "cmp-022", sub: "long-word", context: "", prefix: "definit", acceptable: ["definitely", "definite", "definition"], half: "dev"),
    CompletionCase(id: "cmp-023", sub: "long-word", context: "", prefix: "congratul", acceptable: ["congratulations", "congratulate"], half: "dev"),
    CompletionCase(id: "cmp-024", sub: "long-word", context: "", prefix: "unfortun", acceptable: ["unfortunately", "unfortunate"], half: "test"),
    CompletionCase(id: "cmp-025", sub: "long-word", context: "", prefix: "appreci", acceptable: ["appreciate", "appreciated", "appreciation"], half: "test"),
    CompletionCase(id: "cmp-026", sub: "long-word", context: "", prefix: "recommen", acceptable: ["recommend", "recommendation", "recommended"], half: "dev"),
    CompletionCase(id: "cmp-027", sub: "long-word", context: "", prefix: "immedi", acceptable: ["immediately", "immediate"], half: "dev"),
    CompletionCase(id: "cmp-028", sub: "long-word", context: "", prefix: "absolut", acceptable: ["absolutely", "absolute"], half: "test"),
    CompletionCase(id: "cmp-029", sub: "long-word", context: "", prefix: "underst", acceptable: ["understand", "understanding", "understood"], half: "test"),
    CompletionCase(id: "cmp-030", sub: "long-word", context: "", prefix: "experien", acceptable: ["experience", "experienced", "experiences"], half: "test"),
    CompletionCase(id: "cmp-031", sub: "long-word", context: "", prefix: "informat", acceptable: ["information", "informative"], half: "test"),
    CompletionCase(id: "cmp-032", sub: "long-word", context: "", prefix: "conversat", acceptable: ["conversation", "conversations"], half: "dev"),
    CompletionCase(id: "cmp-033", sub: "texting", context: "", prefix: "prob", acceptable: ["probably", "problem", "probable", "problems"], half: "dev"),
    CompletionCase(id: "cmp-034", sub: "texting", context: "", prefix: "def", acceptable: ["definitely", "definite", "define", "defense"], half: "test"),
    CompletionCase(id: "cmp-035", sub: "texting", context: "", prefix: "tonigh", acceptable: ["tonight"], half: "test"),
    CompletionCase(id: "cmp-036", sub: "texting", context: "", prefix: "gon", acceptable: ["gonna", "gone"], half: "dev"),
    CompletionCase(id: "cmp-037", sub: "texting", context: "", prefix: "wan", acceptable: ["want", "wanna", "wanted", "wants"], half: "dev"),
    CompletionCase(id: "cmp-038", sub: "texting", context: "", prefix: "tex", acceptable: ["text", "texting", "texted", "Texas"], half: "test"),
    CompletionCase(id: "cmp-039", sub: "texting", context: "", prefix: "awes", acceptable: ["awesome"], half: "test"),
    CompletionCase(id: "cmp-040", sub: "texting", context: "", prefix: "hila", acceptable: ["hilarious"], half: "dev"),
    CompletionCase(id: "cmp-041", sub: "texting", context: "", prefix: "seri", acceptable: ["seriously", "serious", "series"], half: "test"),
    CompletionCase(id: "cmp-042", sub: "texting", context: "", prefix: "amaz", acceptable: ["amazing", "amazed", "amazingly"], half: "dev"),
    CompletionCase(id: "cmp-043", sub: "texting", context: "", prefix: "whate", acceptable: ["whatever"], half: "dev"),
    CompletionCase(id: "cmp-044", sub: "texting", context: "", prefix: "anyw", acceptable: ["anyway", "anyways", "anywhere"], half: "test"),
    CompletionCase(id: "cmp-045", sub: "texting", context: "", prefix: "obvi", acceptable: ["obviously", "obvious"], half: "test"),
    CompletionCase(id: "cmp-046", sub: "texting", context: "", prefix: "liter", acceptable: ["literally", "literal", "literature"], half: "dev"),
    CompletionCase(id: "cmp-047", sub: "texting", context: "", prefix: "supp", acceptable: ["supposed", "support", "suppose", "supper"], half: "dev"),
    CompletionCase(id: "cmp-048", sub: "day-month", context: "", prefix: "wednes", acceptable: ["Wednesday", "wednesday"], half: "dev"),
    CompletionCase(id: "cmp-049", sub: "day-month", context: "", prefix: "Tues", acceptable: ["Tuesday"], half: "test"),
    CompletionCase(id: "cmp-050", sub: "day-month", context: "", prefix: "thurs", acceptable: ["Thursday", "thursday"], half: "test"),
    CompletionCase(id: "cmp-051", sub: "day-month", context: "", prefix: "Sat", acceptable: ["Saturday"], half: "test"),
    CompletionCase(id: "cmp-052", sub: "day-month", context: "", prefix: "mond", acceptable: ["Monday", "monday"], half: "dev"),
    CompletionCase(id: "cmp-053", sub: "day-month", context: "", prefix: "Janu", acceptable: ["January"], half: "dev"),
    CompletionCase(id: "cmp-054", sub: "day-month", context: "", prefix: "febr", acceptable: ["February", "february"], half: "test"),
    CompletionCase(id: "cmp-055", sub: "day-month", context: "", prefix: "Aug", acceptable: ["August"], half: "test"),
    CompletionCase(id: "cmp-056", sub: "day-month", context: "", prefix: "septe", acceptable: ["September", "september"], half: "dev"),
    CompletionCase(id: "cmp-057", sub: "day-month", context: "", prefix: "Octo", acceptable: ["October"], half: "dev"),
    CompletionCase(id: "cmp-058", sub: "day-month", context: "", prefix: "decem", acceptable: ["December", "december"], half: "dev"),
    CompletionCase(id: "cmp-059", sub: "day-month", context: "", prefix: "sund", acceptable: ["Sunday", "sunday"], half: "test"),
    CompletionCase(id: "cmp-060", sub: "greeting", context: "", prefix: "Hell", acceptable: ["Hello"], half: "test"),
    CompletionCase(id: "cmp-061", sub: "greeting", context: "", prefix: "morni", acceptable: ["morning", "mornings"], half: "test"),
    CompletionCase(id: "cmp-062", sub: "greeting", context: "", prefix: "afterno", acceptable: ["afternoon"], half: "dev"),
    CompletionCase(id: "cmp-063", sub: "greeting", context: "", prefix: "eveni", acceptable: ["evening", "evenings"], half: "dev"),
    CompletionCase(id: "cmp-064", sub: "greeting", context: "", prefix: "wel", acceptable: ["welcome", "well"], half: "test"),
    CompletionCase(id: "cmp-065", sub: "greeting", context: "", prefix: "congrat", acceptable: ["congrats", "congratulations"], half: "test"),
    CompletionCase(id: "cmp-066", sub: "greeting", context: "", prefix: "Than", acceptable: ["Thanks", "Thank"], half: "dev"),
    CompletionCase(id: "cmp-067", sub: "greeting", context: "", prefix: "goodby", acceptable: ["goodbye", "goodbyes"], half: "dev"),
    CompletionCase(id: "cmp-068", sub: "after-context", context: "See you ", prefix: "tomo", acceptable: ["tomorrow"], half: "test"),
    CompletionCase(id: "cmp-069", sub: "after-context", context: "Happy ", prefix: "birthd", acceptable: ["birthday"], half: "test"),
    CompletionCase(id: "cmp-070", sub: "after-context", context: "Good ", prefix: "morni", acceptable: ["morning"], half: "dev"),
    CompletionCase(id: "cmp-071", sub: "after-context", context: "Thanks so ", prefix: "mu", acceptable: ["much"], half: "test"),
    CompletionCase(id: "cmp-072", sub: "after-context", context: "I'll call you ", prefix: "lat", acceptable: ["later"], half: "dev"),
    CompletionCase(id: "cmp-073", sub: "after-context", context: "Talk to you ", prefix: "soo", acceptable: ["soon"], half: "dev"),
    CompletionCase(id: "cmp-074", sub: "after-context", context: "How are ", prefix: "yo", acceptable: ["you"], half: "test"),
    CompletionCase(id: "cmp-075", sub: "after-context", context: "Let me ", prefix: "kno", acceptable: ["know"], half: "test"),
    CompletionCase(id: "cmp-076", sub: "after-context", context: "On my ", prefix: "wa", acceptable: ["way"], half: "dev"),
    CompletionCase(id: "cmp-077", sub: "after-context", context: "Merry ", prefix: "Christ", acceptable: ["Christmas"], half: "dev"),
    CompletionCase(id: "cmp-078", sub: "after-context", context: "Happy New ", prefix: "Ye", acceptable: ["Year", "year"], half: "dev"),
    CompletionCase(id: "cmp-079", sub: "after-context", context: "Looking forward to ", prefix: "seei", acceptable: ["seeing"], half: "test"),
    CompletionCase(id: "cmp-080", sub: "short-prefix", context: "", prefix: "th", acceptable: ["the", "that", "this", "they", "then", "there", "thanks"], half: "dev"),
    CompletionCase(id: "cmp-081", sub: "short-prefix", context: "", prefix: "wh", acceptable: ["what", "when", "where", "why", "which", "who"], half: "dev"),
    CompletionCase(id: "cmp-083", sub: "short-prefix", context: "", prefix: "mo", acceptable: ["more", "most", "morning", "mom", "money", "moment"], half: "test"),
    CompletionCase(id: "cmp-085", sub: "short-prefix", context: "", prefix: "st", acceptable: ["still", "stop", "start", "stay", "stuff"], half: "test"),
    CompletionCase(id: "cmp-086", sub: "short-prefix", context: "", prefix: "gr", acceptable: ["great", "green", "group", "grab", "grocery"], half: "test"),
    CompletionCase(id: "cmp-087", sub: "short-prefix", context: "", prefix: "pl", acceptable: ["please", "play", "plan", "place", "plus"], half: "test"),
    CompletionCase(id: "cmp-088", sub: "short-prefix", context: "", prefix: "co", acceptable: ["come", "could", "cool", "coffee", "company"], half: "dev"),
    CompletionCase(id: "cmp-089", sub: "short-prefix", context: "", prefix: "fr", acceptable: ["from", "friend", "free", "Friday", "front"], half: "dev"),
    CompletionCase(id: "cmp-090", sub: "no-completion-expected", context: "", prefix: "and", acceptable: ["NONE"], half: "dev"),
    CompletionCase(id: "cmp-091", sub: "no-completion-expected", context: "", prefix: "lol", acceptable: ["NONE"], half: "dev"),
    CompletionCase(id: "cmp-093", sub: "no-completion-expected", context: "", prefix: "yep", acceptable: ["NONE"], half: "test"),
    CompletionCase(id: "cmp-094", sub: "no-completion-expected", context: "", prefix: "zxq", acceptable: ["NONE"], half: "dev"),
    CompletionCase(id: "cmp-095", sub: "no-completion-expected", context: "", prefix: "qqqq", acceptable: ["NONE"], half: "test"),
    CompletionCase(id: "cmp-096", sub: "no-completion-expected", context: "", prefix: "dfgh", acceptable: ["NONE"], half: "test"),
]
