// GENERATED from eval/v4/protect.tsv by eval/v4/gen-corpus.py -- do not hand-edit.
// Blind-authored keyboard-wide eval v4 (specs/keyboard-eval.md). FROZEN.

struct ProtectCase { let id: String; let sub: String; let context: String; let typed: String; let half: String }

let protectCorpus: [ProtectCase] = [
    ProtectCase(id: "A001", sub: "slang", context: "", typed: "lol", half: "test"),
    ProtectCase(id: "A002", sub: "slang", context: "that was so funny", typed: "lmao", half: "dev"),
    ProtectCase(id: "A003", sub: "slang", context: "", typed: "tbh", half: "dev"),
    ProtectCase(id: "A004", sub: "slang", context: "", typed: "ngl", half: "test"),
    ProtectCase(id: "A005", sub: "slang", context: "", typed: "fr", half: "test"),
    ProtectCase(id: "A006", sub: "slang", context: "im so tired", typed: "frfr", half: "dev"),
    ProtectCase(id: "A007", sub: "slang", context: "we", typed: "finna", half: "dev"),
    ProtectCase(id: "A008", sub: "slang", context: "that food was", typed: "bussin", half: "test"),
    ProtectCase(id: "A009", sub: "slang", context: "he got", typed: "rizz", half: "test"),
    ProtectCase(id: "A010", sub: "slang", context: "im", typed: "lowkey", half: "test"),
    ProtectCase(id: "A011", sub: "slang", context: "she was", typed: "highkey", half: "test"),
    ProtectCase(id: "A012", sub: "slang", context: "im", typed: "deadass", half: "dev"),
    ProtectCase(id: "A013", sub: "slang", context: "that guy is", typed: "sus", half: "dev"),
    ProtectCase(id: "A014", sub: "slang", context: "she is so", typed: "delulu", half: "test"),
    ProtectCase(id: "A015", sub: "slang", context: "", typed: "gyat", half: "test"),
    ProtectCase(id: "A016", sub: "slang", context: "he is such a", typed: "sigma", half: "dev"),
    ProtectCase(id: "A017", sub: "slang", context: "", typed: "skibidi", half: "dev"),
    ProtectCase(id: "A018", sub: "slang", context: "pulling all the", typed: "huzz", half: "test"),
    ProtectCase(id: "A019", sub: "slang", context: "that fit is", typed: "chopped", half: "test"),
    ProtectCase(id: "A020", sub: "slang", context: "", typed: "ong", half: "test"),
    ProtectCase(id: "A021", sub: "slang", context: "", typed: "istg", half: "dev"),
    ProtectCase(id: "A022", sub: "slang", context: "", typed: "ijbol", half: "dev"),
    ProtectCase(id: "A023", sub: "slang", context: "he is", typed: "goated", half: "dev"),
    ProtectCase(id: "A024", sub: "slang", context: "stop being a", typed: "simp", half: "test"),
    ProtectCase(id: "A025", sub: "slang", context: "i", typed: "stan", half: "test"),
    ProtectCase(id: "A026", sub: "slang", context: "", typed: "bruh", half: "dev"),
    ProtectCase(id: "A027", sub: "slang", context: "whats good", typed: "fam", half: "dev"),
    ProtectCase(id: "A028", sub: "slang", context: "", typed: "bffr", half: "test"),
    ProtectCase(id: "A029", sub: "slang", context: "", typed: "icl", half: "dev"),
    ProtectCase(id: "A030", sub: "slang", context: "that would", typed: "pmo", half: "test"),
    ProtectCase(id: "A031", sub: "slang", context: "", typed: "sybau", half: "dev"),
    ProtectCase(id: "A032", sub: "slang", context: "that car is", typed: "tuff", half: "dev"),
    ProtectCase(id: "A033", sub: "slang", context: "im", typed: "boutta", half: "dev"),
    ProtectCase(id: "A034", sub: "slang", context: "check her", typed: "finsta", half: "test"),
    ProtectCase(id: "A035", sub: "slang", context: "dont", typed: "unalive", half: "dev"),
    ProtectCase(id: "A036", sub: "acronym-caps", context: "ill get it done", typed: "ASAP", half: "dev"),
    ProtectCase(id: "A037", sub: "acronym-caps", context: "", typed: "FYI", half: "dev"),
    ProtectCase(id: "A038", sub: "acronym-caps", context: "works at", typed: "NASA", half: "test"),
    ProtectCase(id: "A039", sub: "acronym-caps", context: "he is the", typed: "GOAT", half: "dev"),
    ProtectCase(id: "A040", sub: "acronym-caps", context: "", typed: "LMK", half: "test"),
    ProtectCase(id: "A041", sub: "acronym-caps", context: "", typed: "IMO", half: "test"),
    ProtectCase(id: "A042", sub: "acronym-caps", context: "date is", typed: "TBD", half: "dev"),
    ProtectCase(id: "A043", sub: "acronym-caps", context: "whats your", typed: "ETA", half: "dev"),
    ProtectCase(id: "A044", sub: "acronym-caps", context: "its a", typed: "DIY", half: "test"),
    ProtectCase(id: "A045", sub: "acronym-caps", context: "i have", typed: "FOMO", half: "test"),
    ProtectCase(id: "A046", sub: "acronym-caps", context: "", typed: "POV", half: "dev"),
    ProtectCase(id: "A047", sub: "acronym-caps", context: "", typed: "IYKYK", half: "dev"),
    ProtectCase(id: "A048", sub: "acronym-caps", context: "he is an", typed: "NPC", half: "test"),
    ProtectCase(id: "A049", sub: "acronym-caps", context: "todays", typed: "OOTD", half: "test"),
    ProtectCase(id: "A050", sub: "acronym-caps", context: "", typed: "TLDR", half: "dev"),
    ProtectCase(id: "A051", sub: "name", context: "my friend", typed: "Jayden", half: "test"),
    ProtectCase(id: "A052", sub: "name", context: "", typed: "Nkechi", half: "dev"),
    ProtectCase(id: "A053", sub: "name", context: "", typed: "Saoirse", half: "dev"),
    ProtectCase(id: "A054", sub: "name", context: "her name is", typed: "Siobhan", half: "test"),
    ProtectCase(id: "A055", sub: "name", context: "", typed: "Aoife", half: "test"),
    ProtectCase(id: "A056", sub: "name", context: "ask", typed: "Priya", half: "dev"),
    ProtectCase(id: "A057", sub: "name", context: "", typed: "Mateo", half: "dev"),
    ProtectCase(id: "A058", sub: "name", context: "", typed: "Thiago", half: "test"),
    ProtectCase(id: "A059", sub: "name", context: "", typed: "Ximena", half: "test"),
    ProtectCase(id: "A060", sub: "name", context: "saw", typed: "Zendaya", half: "dev"),
    ProtectCase(id: "A061", sub: "name", context: "listening to", typed: "Kehlani", half: "test"),
    ProtectCase(id: "A062", sub: "name", context: "", typed: "Jaxon", half: "dev"),
    ProtectCase(id: "A063", sub: "name", context: "", typed: "Kaius", half: "dev"),
    ProtectCase(id: "A064", sub: "name", context: "", typed: "Anaya", half: "dev"),
    ProtectCase(id: "A065", sub: "name", context: "", typed: "Malia", half: "test"),
    ProtectCase(id: "A066", sub: "name", context: "text", typed: "Deshawn", half: "dev"),
    ProtectCase(id: "A067", sub: "name", context: "", typed: "Giannis", half: "dev"),
    ProtectCase(id: "A068", sub: "name", context: "", typed: "Kylian", half: "dev"),
    ProtectCase(id: "A069", sub: "name", context: "", typed: "Yuki", half: "test"),
    ProtectCase(id: "A070", sub: "name", context: "", typed: "Aiyana", half: "test"),
    ProtectCase(id: "A071", sub: "name", context: "", typed: "Latoya", half: "test"),
    ProtectCase(id: "A072", sub: "name", context: "", typed: "Rashida", half: "dev"),
    ProtectCase(id: "A073", sub: "name", context: "", typed: "Oluwaseun", half: "dev"),
    ProtectCase(id: "A074", sub: "name", context: "", typed: "Marisol", half: "test"),
    ProtectCase(id: "A075", sub: "name", context: "", typed: "Dakari", half: "test"),
    ProtectCase(id: "A076", sub: "brand", context: "playing on", typed: "Spotify", half: "dev"),
    ProtectCase(id: "A077", sub: "brand", context: "ill", typed: "Venmo", half: "dev"),
    ProtectCase(id: "A078", sub: "brand", context: "asked", typed: "ChatGPT", half: "test"),
    ProtectCase(id: "A079", sub: "brand", context: "new", typed: "iPhone", half: "test"),
    ProtectCase(id: "A080", sub: "brand", context: "saw it on", typed: "TikTok", half: "dev"),
    ProtectCase(id: "A081", sub: "brand", context: "add me on", typed: "Snapchat", half: "dev"),
    ProtectCase(id: "A082", sub: "brand", context: "posted on", typed: "Instagram", half: "test"),
    ProtectCase(id: "A083", sub: "brand", context: "message me on", typed: "WhatsApp", half: "test"),
    ProtectCase(id: "A084", sub: "brand", context: "watching", typed: "Netflix", half: "dev"),
    ProtectCase(id: "A085", sub: "brand", context: "practicing on", typed: "Duolingo", half: "dev"),
    ProtectCase(id: "A086", sub: "brand", context: "booked an", typed: "Airbnb", half: "test"),
    ProtectCase(id: "A087", sub: "brand", context: "pay with", typed: "PayPal", half: "test"),
    ProtectCase(id: "A088", sub: "brand", context: "on my", typed: "Xbox", half: "dev"),
    ProtectCase(id: "A089", sub: "brand", context: "got a", typed: "PlayStation", half: "dev"),
    ProtectCase(id: "A090", sub: "brand", context: "ordered from", typed: "Shein", half: "dev"),
    ProtectCase(id: "A091", sub: "brand", context: "send it on", typed: "Zelle", half: "test"),
    ProtectCase(id: "A092", sub: "brand", context: "getting a", typed: "Lyft", half: "test"),
    ProtectCase(id: "A093", sub: "brand", context: "playing", typed: "Fortnite", half: "test"),
    ProtectCase(id: "A094", sub: "brand", context: "hes on", typed: "Roblox", half: "dev"),
    ProtectCase(id: "A095", sub: "brand", context: "my", typed: "MacBook", half: "test"),
    ProtectCase(id: "A096", sub: "url", context: "go to", typed: "google.com", half: "test"),
    ProtectCase(id: "A097", sub: "url", context: "", typed: "youtube.com", half: "test"),
    ProtectCase(id: "A098", sub: "url", context: "link is", typed: "bit.ly/3xYzAb", half: "dev"),
    ProtectCase(id: "A099", sub: "url", context: "", typed: "github.com/anthropics", half: "dev"),
    ProtectCase(id: "A100", sub: "url", context: "scores at", typed: "www.espn.com", half: "test"),
    ProtectCase(id: "A101", sub: "url", context: "", typed: "https://open.spotify.com/track/abc123", half: "test"),
    ProtectCase(id: "A102", sub: "url", context: "its on", typed: "docs.google.com", half: "dev"),
    ProtectCase(id: "A103", sub: "url", context: "", typed: "reddit.com/r/ios", half: "dev"),
    ProtectCase(id: "A104", sub: "email", context: "email me at", typed: "jake.smith@gmail.com", half: "test"),
    ProtectCase(id: "A105", sub: "email", context: "", typed: "saoirse_99@yahoo.com", half: "test"),
    ProtectCase(id: "A106", sub: "email", context: "send to", typed: "info@bakery.co", half: "dev"),
    ProtectCase(id: "A107", sub: "email", context: "use", typed: "jsilver+promo@outlook.com", half: "dev"),
    ProtectCase(id: "A108", sub: "email", context: "", typed: "maria.gonzalez@uni.edu", half: "test"),
    ProtectCase(id: "A109", sub: "email", context: "", typed: "ktown4life@icloud.com", half: "dev"),
    ProtectCase(id: "A110", sub: "hashtag", context: "", typed: "#tbt", half: "test"),
    ProtectCase(id: "A112", sub: "hashtag", context: "", typed: "#nofilter", half: "dev"),
    ProtectCase(id: "A114", sub: "hashtag", context: "", typed: "#GRWM", half: "test"),
    ProtectCase(id: "A115", sub: "hashtag", context: "", typed: "#SaturdayVibes", half: "dev"),
    ProtectCase(id: "A118", sub: "handle", context: "follow", typed: "@jaydenw", half: "test"),
    ProtectCase(id: "A122", sub: "handle", context: "", typed: "@pinkydoll_", half: "dev"),
    ProtectCase(id: "A123", sub: "handle", context: "", typed: "@itzkaitlyn", half: "dev"),
    ProtectCase(id: "A126", sub: "stylization", context: "im", typed: "sooo", half: "dev"),
    ProtectCase(id: "A127", sub: "stylization", context: "", typed: "yesss", half: "dev"),
    ProtectCase(id: "A128", sub: "stylization", context: "", typed: "noooo", half: "test"),
    ProtectCase(id: "A129", sub: "stylization", context: "", typed: "hahahah", half: "test"),
    ProtectCase(id: "A131", sub: "stylization", context: "", typed: "plsss", half: "dev"),
    ProtectCase(id: "A132", sub: "stylization", context: "", typed: "omggg", half: "dev"),
    ProtectCase(id: "A133", sub: "stylization", context: "", typed: "stoppp", half: "dev"),
    ProtectCase(id: "A134", sub: "stylization", context: "", typed: "heyyy", half: "test"),
    ProtectCase(id: "A135", sub: "stylization", context: "", typed: "byeee", half: "test"),
    ProtectCase(id: "A136", sub: "stylization", context: "", typed: "okkk", half: "dev"),
    ProtectCase(id: "A137", sub: "stylization", context: "", typed: "hmmm", half: "dev"),
    ProtectCase(id: "A138", sub: "stylization", context: "", typed: "ughhh", half: "test"),
    ProtectCase(id: "A139", sub: "stylization", context: "", typed: "lmaooo", half: "test"),
    ProtectCase(id: "A140", sub: "stylization", context: "", typed: "whyyy", half: "test"),
    ProtectCase(id: "A141", sub: "stylization", context: "", typed: "yayyy", half: "test"),
    ProtectCase(id: "A142", sub: "stylization", context: "", typed: "wowww", half: "dev"),
    ProtectCase(id: "A143", sub: "stylization", context: "", typed: "duuude", half: "dev"),
    ProtectCase(id: "A144", sub: "shortform", context: "im busy", typed: "rn", half: "test"),
    ProtectCase(id: "A145", sub: "shortform", context: "im good", typed: "hbu", half: "test"),
    ProtectCase(id: "A146", sub: "shortform", context: "", typed: "wyd", half: "dev"),
    ProtectCase(id: "A147", sub: "shortform", context: "", typed: "idk", half: "dev"),
    ProtectCase(id: "A148", sub: "shortform", context: "", typed: "omw", half: "test"),
    ProtectCase(id: "A149", sub: "shortform", context: "", typed: "ty", half: "test"),
    ProtectCase(id: "A150", sub: "shortform", context: "", typed: "np", half: "test"),
    ProtectCase(id: "A151", sub: "shortform", context: "", typed: "ily", half: "test"),
    ProtectCase(id: "A152", sub: "shortform", context: "", typed: "ilysm", half: "dev"),
    ProtectCase(id: "A153", sub: "shortform", context: "", typed: "imy", half: "dev"),
    ProtectCase(id: "A154", sub: "shortform", context: "oh", typed: "nvm", half: "test"),
    ProtectCase(id: "A155", sub: "shortform", context: "come thru", typed: "tho", half: "test"),
    ProtectCase(id: "A156", sub: "shortform", context: "", typed: "thx", half: "dev"),
    ProtectCase(id: "A157", sub: "shortform", context: "", typed: "pls", half: "dev"),
    ProtectCase(id: "A158", sub: "shortform", context: "i", typed: "rly", half: "test"),
    ProtectCase(id: "A159", sub: "shortform", context: "", typed: "srsly", half: "test"),
    ProtectCase(id: "A160", sub: "shortform", context: "cant", typed: "bc", half: "dev"),
    ProtectCase(id: "A161", sub: "shortform", context: "", typed: "cuz", half: "test"),
    ProtectCase(id: "A162", sub: "shortform", context: "so many", typed: "ppl", half: "dev"),
    ProtectCase(id: "A163", sub: "shortform", context: "send me a", typed: "msg", half: "dev"),
    ProtectCase(id: "A164", sub: "shortform", context: "", typed: "def", half: "dev"),
    ProtectCase(id: "A165", sub: "shortform", context: "", typed: "prob", half: "test"),
    ProtectCase(id: "A166", sub: "shortform", context: "see you", typed: "tmrw", half: "dev"),
    ProtectCase(id: "A167", sub: "shortform", context: "", typed: "wya", half: "dev"),
    ProtectCase(id: "A168", sub: "shortform", context: "", typed: "gn", half: "dev"),
    ProtectCase(id: "A169", sub: "number-mix", context: "its a", typed: "B2B", half: "test"),
    ProtectCase(id: "A170", sub: "number-mix", context: "my", typed: "401k", half: "dev"),
    ProtectCase(id: "A171", sub: "number-mix", context: "", typed: "H2O", half: "test"),
    ProtectCase(id: "A172", sub: "number-mix", context: "no", typed: "5G", half: "dev"),
    ProtectCase(id: "A173", sub: "number-mix", context: "enable", typed: "2FA", half: "dev"),
    ProtectCase(id: "A174", sub: "number-mix", context: "got my", typed: "W2", half: "test"),
    ProtectCase(id: "A175", sub: "number-mix", context: "", typed: "K9", half: "test"),
    ProtectCase(id: "A176", sub: "number-mix", context: "", typed: "A1", half: "dev"),
    ProtectCase(id: "A177", sub: "number-mix", context: "watching", typed: "F1", half: "dev"),
    ProtectCase(id: "A178", sub: "number-mix", context: "open", typed: "24/7", half: "test"),
    ProtectCase(id: "A179", sub: "profanity-mild", context: "", typed: "damn", half: "test"),
    ProtectCase(id: "A180", sub: "profanity-mild", context: "", typed: "hell", half: "dev"),
    ProtectCase(id: "A181", sub: "profanity-mild", context: "oh", typed: "crap", half: "dev"),
    ProtectCase(id: "A182", sub: "profanity-mild", context: "dont", typed: "piss", half: "test"),
    ProtectCase(id: "A183", sub: "profanity-mild", context: "pain in the", typed: "ass", half: "test"),
    ProtectCase(id: "A184", sub: "profanity-mild", context: "thats", typed: "badass", half: "dev"),
    ProtectCase(id: "A185", sub: "non-english-loanword", context: "", typed: "gracias", half: "dev"),
    ProtectCase(id: "A186", sub: "non-english-loanword", context: "", typed: "merci", half: "test"),
    ProtectCase(id: "A187", sub: "non-english-loanword", context: "", typed: "habibi", half: "test"),
    ProtectCase(id: "A188", sub: "non-english-loanword", context: "", typed: "hola", half: "dev"),
    ProtectCase(id: "A189", sub: "non-english-loanword", context: "", typed: "danke", half: "dev"),
    ProtectCase(id: "A190", sub: "non-english-loanword", context: "", typed: "arigato", half: "dev"),
    ProtectCase(id: "A191", sub: "non-english-loanword", context: "", typed: "wallah", half: "test"),
    ProtectCase(id: "A192", sub: "non-english-loanword", context: "", typed: "inshallah", half: "test"),
    ProtectCase(id: "A193", sub: "non-english-loanword", context: "", typed: "besos", half: "test"),
    ProtectCase(id: "A194", sub: "non-english-loanword", context: "spill the", typed: "chisme", half: "dev"),
    ProtectCase(id: "A195", sub: "interjection", context: "", typed: "ugh", half: "dev"),
    ProtectCase(id: "A196", sub: "interjection", context: "", typed: "meh", half: "test"),
    ProtectCase(id: "A197", sub: "interjection", context: "", typed: "welp", half: "test"),
    ProtectCase(id: "A198", sub: "interjection", context: "", typed: "oof", half: "dev"),
    ProtectCase(id: "A199", sub: "interjection", context: "", typed: "yeet", half: "dev"),
    ProtectCase(id: "A200", sub: "interjection", context: "", typed: "psst", half: "test"),
    ProtectCase(id: "A201", sub: "interjection", context: "", typed: "hmph", half: "test"),
    ProtectCase(id: "A202", sub: "interjection", context: "", typed: "ope", half: "dev"),
    ProtectCase(id: "A203", sub: "interjection", context: "", typed: "sheesh", half: "dev"),
    ProtectCase(id: "A204", sub: "interjection", context: "", typed: "whew", half: "test"),
    ProtectCase(id: "A205", sub: "interjection", context: "", typed: "aww", half: "test"),
    ProtectCase(id: "A206", sub: "interjection", context: "", typed: "eep", half: "dev"),
]
