// GENERATED from eval/v4/cap.tsv by eval/v4/gen-corpus.py -- do not hand-edit.
// Blind-authored keyboard-wide eval v4 (specs/keyboard-eval.md). FROZEN.

struct CapCase { let id: String; let sub: String; let context: String; let expectCap: Bool; let half: String }

let capCorpus: [CapCase] = [
    CapCase(id: "cap-001", sub: "empty-field", context: "", expectCap: true, half: "dev"),
    CapCase(id: "cap-005", sub: "sentence-start", context: " ", expectCap: true, half: "test"),
    CapCase(id: "cap-006", sub: "sentence-start", context: "  ", expectCap: true, half: "dev"),
    CapCase(id: "cap-007", sub: "after-period", context: "Sounds good. ", expectCap: true, half: "dev"),
    CapCase(id: "cap-011", sub: "after-period", context: "Done. ", expectCap: true, half: "test"),
    CapCase(id: "cap-012", sub: "after-period", context: "omw. ", expectCap: true, half: "test"),
    CapCase(id: "cap-017", sub: "after-period", context: "Meeting moved to Friday. ", expectCap: true, half: "dev"),
    CapCase(id: "cap-020", sub: "after-period", context: "Dinner's ready. ", expectCap: true, half: "test"),
    CapCase(id: "cap-022", sub: "after-period", context: "Done.  ", expectCap: true, half: "dev"),
    CapCase(id: "cap-023", sub: "after-period", context: "k. ", expectCap: true, half: "dev"),
    CapCase(id: "cap-029", sub: "after-question", context: "Are you coming? ", expectCap: true, half: "test"),
    CapCase(id: "cap-031", sub: "after-question", context: "u up? ", expectCap: true, half: "dev"),
    CapCase(id: "cap-032", sub: "after-question", context: "Really? ", expectCap: true, half: "dev"),
    CapCase(id: "cap-038", sub: "after-question", context: "Seriously?? ", expectCap: true, half: "dev"),
    CapCase(id: "cap-040", sub: "after-question", context: "You did what?! ", expectCap: true, half: "test"),
    CapCase(id: "cap-041", sub: "after-exclaim", context: "Let's go! ", expectCap: true, half: "dev"),
    CapCase(id: "cap-043", sub: "after-exclaim", context: "Congrats! ", expectCap: true, half: "dev"),
    CapCase(id: "cap-048", sub: "after-exclaim", context: "So excited!! ", expectCap: true, half: "test"),
    CapCase(id: "cap-049", sub: "after-exclaim", context: "yesss! ", expectCap: true, half: "test"),
    CapCase(id: "cap-053", sub: "after-abbrev", context: "Ask Mr. ", expectCap: false, half: "dev"),
    CapCase(id: "cap-054", sub: "after-abbrev", context: "I emailed Dr. ", expectCap: false, half: "test"),
    CapCase(id: "cap-055", sub: "after-abbrev", context: "Tell Mrs. ", expectCap: false, half: "test"),
    CapCase(id: "cap-056", sub: "after-abbrev", context: "This is Ms. ", expectCap: false, half: "dev"),
    CapCase(id: "cap-057", sub: "after-abbrev", context: "citrus fruits, e.g. ", expectCap: false, half: "dev"),
    CapCase(id: "cap-059", sub: "after-abbrev", context: "the deadline, i.e. ", expectCap: false, half: "test"),
    CapCase(id: "cap-061", sub: "after-abbrev", context: "snacks, drinks, etc. and", expectCap: false, half: "test"),
    CapCase(id: "cap-062", sub: "after-abbrev", context: "cats vs. ", expectCap: false, half: "dev"),
    CapCase(id: "cap-063", sub: "after-abbrev", context: "on Main St. near", expectCap: false, half: "dev"),
    CapCase(id: "cap-064", sub: "after-abbrev", context: "Ken Griffey Jr. ", expectCap: false, half: "test"),
    CapCase(id: "cap-066", sub: "after-abbrev", context: "office of Prof. ", expectCap: false, half: "dev"),
    CapCase(id: "cap-067", sub: "after-abbrev", context: "it costs approx. ", expectCap: false, half: "dev"),
    CapCase(id: "cap-068", sub: "after-abbrev", context: "Fifth Ave. between", expectCap: false, half: "test"),
    CapCase(id: "cap-069", sub: "after-abbrev", context: "dinner at 6 p.m. ", expectCap: false, half: "test"),
    CapCase(id: "cap-071", sub: "after-abbrev", context: "Sunset Blvd. and", expectCap: false, half: "test"),
    CapCase(id: "cap-072", sub: "after-abbrev", context: "my appt. is", expectCap: false, half: "dev"),
    CapCase(id: "cap-073", sub: "after-ellipsis", context: "so... ", expectCap: true, half: "dev"),
    CapCase(id: "cap-077", sub: "after-ellipsis", context: "maybe… ", expectCap: true, half: "dev"),
    CapCase(id: "cap-082", sub: "after-ellipsis", context: "anyway.... ", expectCap: true, half: "test"),
    CapCase(id: "cap-083", sub: "after-newline", context: "ok\n", expectCap: true, half: "test"),
    CapCase(id: "cap-086", sub: "after-newline", context: "So that's the plan.\n", expectCap: true, half: "test"),
    CapCase(id: "cap-088", sub: "after-newline", context: "Agenda:\n", expectCap: true, half: "dev"),
    CapCase(id: "cap-089", sub: "after-newline", context: "one\ntwo\n", expectCap: true, half: "dev"),
    CapCase(id: "cap-090", sub: "after-newline", context: "hello\n\n", expectCap: true, half: "dev"),
    CapCase(id: "cap-093", sub: "after-newline", context: "The meeting is at 3\n", expectCap: true, half: "test"),
    CapCase(id: "cap-097", sub: "after-quote", context: "He said \"That's enough.\" ", expectCap: true, half: "test"),
    CapCase(id: "cap-098", sub: "after-quote", context: "\"Stop!\" ", expectCap: true, half: "dev"),
    CapCase(id: "cap-100", sub: "after-quote", context: "He asked \"why?\" ", expectCap: true, half: "dev"),
    CapCase(id: "cap-101", sub: "after-quote", context: "She said “I’m done.” ", expectCap: true, half: "test"),
    CapCase(id: "cap-102", sub: "after-quote", context: "He said 'done.' ", expectCap: true, half: "dev"),
    CapCase(id: "cap-104", sub: "after-quote", context: "he called it \"fun\" and ", expectCap: false, half: "dev"),
    CapCase(id: "cap-108", sub: "after-quote", context: "add the 'utils' folder to ", expectCap: false, half: "test"),
    CapCase(id: "cap-109", sub: "after-emoji", context: "Done! 🎉 ", expectCap: true, half: "test"),
    CapCase(id: "cap-111", sub: "after-emoji", context: "That was wild! 😂😂 ", expectCap: true, half: "test"),
    CapCase(id: "cap-113", sub: "after-emoji", context: "ok. 👍 ", expectCap: true, half: "dev"),
    CapCase(id: "cap-116", sub: "after-emoji", context: "hey 😂 ", expectCap: false, half: "dev"),
    CapCase(id: "cap-120", sub: "after-emoji", context: "that cat 🐱 is ", expectCap: false, half: "dev"),
    CapCase(id: "cap-121", sub: "after-comma-no", context: "sounds good, ", expectCap: false, half: "test"),
    CapCase(id: "cap-124", sub: "after-comma-no", context: "First, ", expectCap: false, half: "dev"),
    CapCase(id: "cap-130", sub: "after-comma-no", context: "red, blue, ", expectCap: false, half: "test"),
    CapCase(id: "cap-132", sub: "after-comma-no", context: "btw, ", expectCap: false, half: "dev"),
    CapCase(id: "cap-133", sub: "mid-sentence-no", context: "I am going to the ", expectCap: false, half: "dev"),
    CapCase(id: "cap-139", sub: "mid-sentence-no", context: "I'm at th", expectCap: false, half: "test"),
    CapCase(id: "cap-141", sub: "mid-sentence-no", context: "state-of-the-", expectCap: false, half: "dev"),
    CapCase(id: "cap-142", sub: "mid-sentence-no", context: "don'", expectCap: false, half: "dev"),
    CapCase(id: "cap-143", sub: "mid-sentence-no", context: "we tried; ", expectCap: false, half: "dev"),
    CapCase(id: "cap-144", sub: "mid-sentence-no", context: "It was fine - ", expectCap: false, half: "test"),
    CapCase(id: "cap-145", sub: "mid-sentence-no", context: "mac & ", expectCap: false, half: "test"),
    CapCase(id: "cap-146", sub: "mid-sentence-no", context: "and/", expectCap: false, half: "dev"),
    CapCase(id: "cap-147", sub: "mid-sentence-no", context: "I think (", expectCap: false, half: "dev"),
    CapCase(id: "cap-148", sub: "mid-sentence-no", context: "pi is 3.14 and ", expectCap: false, half: "test"),
    CapCase(id: "cap-150", sub: "mid-sentence-no", context: "check https://example.com/", expectCap: false, half: "test"),
    CapCase(id: "cap-152", sub: "mid-sentence-no", context: "email me at jake@", expectCap: false, half: "dev"),
    CapCase(id: "cap-155", sub: "mid-sentence-no", context: "50% of ", expectCap: false, half: "test"),
    CapCase(id: "cap-156", sub: "mid-sentence-no", context: "room #", expectCap: false, half: "dev"),
    CapCase(id: "cap-157", sub: "mid-sentence-no", context: "got an A+ on ", expectCap: false, half: "dev"),
    CapCase(id: "cap-159", sub: "mid-sentence-no", context: "T", expectCap: false, half: "test"),
    CapCase(id: "cap-161", sub: "mid-sentence-no", context: "its giving ", expectCap: false, half: "test"),
    CapCase(id: "cap-165", sub: "standalone-i", context: "i", expectCap: true, half: "dev"),
    CapCase(id: "cap-166", sub: "standalone-i", context: "can i", expectCap: true, half: "dev"),
    CapCase(id: "cap-174", sub: "standalone-i", context: "idk if i", expectCap: true, half: "test"),
    CapCase(id: "cap-175", sub: "after-number", context: "I got 100. ", expectCap: true, half: "test"),
    CapCase(id: "cap-177", sub: "after-number", context: "Meet at 5? ", expectCap: true, half: "dev"),
    CapCase(id: "cap-178", sub: "after-number", context: "Party ends at 10! ", expectCap: true, half: "test"),
    CapCase(id: "cap-179", sub: "after-number", context: "It costs $50. ", expectCap: true, half: "dev"),
    CapCase(id: "cap-183", sub: "after-parenthetical", context: "He finally showed up (two hours late). ", expectCap: true, half: "dev"),
    CapCase(id: "cap-185", sub: "after-parenthetical", context: "(No parking there.) ", expectCap: true, half: "dev"),
    CapCase(id: "cap-187", sub: "after-parenthetical", context: "I think (as usual) ", expectCap: false, half: "test"),
    CapCase(id: "cap-191", sub: "after-colon", context: "Here's the plan: ", expectCap: false, half: "dev"),
    CapCase(id: "cap-196", sub: "after-colon", context: "meet at 3:", expectCap: false, half: "test"),
    CapCase(id: "cap-199", sub: "greeting-line", context: "Hi John,\n", expectCap: true, half: "dev"),
    CapCase(id: "cap-201", sub: "greeting-line", context: "hey,\n", expectCap: true, half: "test"),
    CapCase(id: "cap-204", sub: "greeting-line", context: "Dear Sir or Madam,\n", expectCap: true, half: "dev"),
]
