// GENERATED from eval/v4/symbols.tsv by eval/v4/gen-corpus.py -- do not hand-edit.
// Blind-authored keyboard-wide eval v4 (specs/keyboard-eval.md). FROZEN.

struct SymbolCase { let id: String; let sub: String; let context: String; let typed: String; let expected: String; let half: String }

let symbolCorpus: [SymbolCase] = [
    SymbolCase(id: "sym-001", sub: "contraction-fix", context: "i", typed: "dont", expected: "don’t", half: "test"),
    SymbolCase(id: "sym-002", sub: "contraction-fix", context: "no we", typed: "dont", expected: "don’t", half: "dev"),
    SymbolCase(id: "sym-004", sub: "contraction-fix", context: "sorry i", typed: "cant", expected: "can’t", half: "dev"),
    SymbolCase(id: "sym-005", sub: "contraction-fix", context: "she", typed: "cant", expected: "can’t", half: "test"),
    SymbolCase(id: "sym-006", sub: "contraction-fix", context: "it", typed: "wont", expected: "won’t", half: "dev"),
    SymbolCase(id: "sym-007", sub: "contraction-fix", context: "the app", typed: "wont", expected: "won’t", half: "dev"),
    SymbolCase(id: "sym-008", sub: "contraction-fix", context: "", typed: "im", expected: "I’m", half: "dev"),
    SymbolCase(id: "sym-009", sub: "contraction-fix", context: "lol", typed: "im", expected: "I’m", half: "test"),
    SymbolCase(id: "sym-010", sub: "contraction-fix", context: "", typed: "im omw", expected: "I’m omw", half: "test"),
    SymbolCase(id: "sym-011", sub: "contraction-fix", context: "", typed: "ive", expected: "I’ve", half: "test"),
    SymbolCase(id: "sym-012", sub: "contraction-fix", context: "omg", typed: "ive", expected: "I’ve", half: "dev"),
    SymbolCase(id: "sym-013", sub: "contraction-fix", context: "lol", typed: "youre", expected: "you’re", half: "dev"),
    SymbolCase(id: "sym-014", sub: "contraction-fix", context: "i swear", typed: "youre", expected: "you’re", half: "test"),
    SymbolCase(id: "sym-015", sub: "contraction-fix", context: "i think", typed: "theyre", expected: "they’re", half: "test"),
    SymbolCase(id: "sym-016", sub: "contraction-fix", context: "omg", typed: "theyre", expected: "they’re", half: "dev"),
    SymbolCase(id: "sym-017", sub: "contraction-fix", context: "it", typed: "wasnt", expected: "wasn’t", half: "dev"),
    SymbolCase(id: "sym-019", sub: "contraction-fix", context: "i", typed: "didnt", expected: "didn’t", half: "test"),
    SymbolCase(id: "sym-020", sub: "contraction-fix", context: "u", typed: "didnt", expected: "didn’t", half: "test"),
    SymbolCase(id: "sym-021", sub: "contraction-fix", context: "that", typed: "isnt", expected: "isn’t", half: "test"),
    SymbolCase(id: "sym-022", sub: "contraction-fix", context: "they", typed: "arent", expected: "aren’t", half: "dev"),
    SymbolCase(id: "sym-023", sub: "contraction-fix", context: "she", typed: "doesnt", expected: "doesn’t", half: "dev"),
    SymbolCase(id: "sym-024", sub: "contraction-fix", context: "i", typed: "couldnt", expected: "couldn’t", half: "test"),
    SymbolCase(id: "sym-025", sub: "contraction-fix", context: "you", typed: "shouldnt", expected: "shouldn’t", half: "test"),
    SymbolCase(id: "sym-026", sub: "contraction-fix", context: "he", typed: "wouldnt", expected: "wouldn’t", half: "dev"),
    SymbolCase(id: "sym-027", sub: "contraction-fix", context: "i", typed: "havent", expected: "haven’t", half: "dev"),
    SymbolCase(id: "sym-028", sub: "contraction-fix", context: "she", typed: "hasnt", expected: "hasn’t", half: "test"),
    SymbolCase(id: "sym-029", sub: "contraction-fix", context: "we", typed: "hadnt", expected: "hadn’t", half: "test"),
    SymbolCase(id: "sym-030", sub: "contraction-fix", context: "they", typed: "werent", expected: "weren’t", half: "test"),
    SymbolCase(id: "sym-031", sub: "contraction-fix", context: "and", typed: "weve", expected: "we’ve", half: "test"),
    SymbolCase(id: "sym-032", sub: "contraction-fix", context: "wow", typed: "youve", expected: "you’ve", half: "dev"),
    SymbolCase(id: "sym-033", sub: "contraction-fix", context: "i bet", typed: "theyve", expected: "they’ve", half: "dev"),
    SymbolCase(id: "sym-034", sub: "contraction-fix", context: "maybe", typed: "youll", expected: "you’ll", half: "test"),
    SymbolCase(id: "sym-035", sub: "contraction-fix", context: "i hope", typed: "theyll", expected: "they’ll", half: "test"),
    SymbolCase(id: "sym-036", sub: "contraction-fix", context: "figured", typed: "youd", expected: "you’d", half: "dev"),
    SymbolCase(id: "sym-037", sub: "contraction-fix", context: "i knew", typed: "theyd", expected: "they’d", half: "dev"),
    SymbolCase(id: "sym-038", sub: "contraction-fix", context: "lol", typed: "thats", expected: "that’s", half: "test"),
    SymbolCase(id: "sym-039", sub: "contraction-fix", context: "omg", typed: "thats so cool", expected: "that’s so cool", half: "test"),
    SymbolCase(id: "sym-040", sub: "contraction-fix", context: "idk", typed: "whos coming", expected: "who’s coming", half: "test"),
    SymbolCase(id: "sym-041", sub: "contraction-fix", context: "i think", typed: "hes", expected: "he’s", half: "dev"),
    SymbolCase(id: "sym-042", sub: "contraction-fix", context: "yeah", typed: "shes", expected: "she’s", half: "dev"),
    SymbolCase(id: "sym-043", sub: "contraction-fix", context: "ok", typed: "lets go", expected: "let’s go", half: "dev"),
    SymbolCase(id: "sym-044", sub: "contraction-fix", context: "alright", typed: "lets do it", expected: "let’s do it", half: "test"),
    SymbolCase(id: "sym-045", sub: "contraction-fix", context: "he", typed: "aint", expected: "ain’t", half: "test"),
    SymbolCase(id: "sym-046", sub: "contraction-fix", context: "you", typed: "mustnt", expected: "mustn’t", half: "dev"),
    SymbolCase(id: "sym-047", sub: "contraction-fix", context: "yo", typed: "whats up", expected: "what’s up", half: "dev"),
    SymbolCase(id: "sym-048", sub: "contraction-fix", context: "lol", typed: "wheres the party", expected: "where’s the party", half: "test"),
    SymbolCase(id: "sym-049", sub: "contraction-fix", context: "so", typed: "hows it going", expected: "how’s it going", half: "test"),
    SymbolCase(id: "sym-050", sub: "contraction-fix", context: "omg", typed: "theres a line", expected: "there’s a line", half: "test"),
    SymbolCase(id: "sym-051", sub: "contraction-fix", context: "ok", typed: "heres the plan", expected: "here’s the plan", half: "dev"),
    SymbolCase(id: "sym-052", sub: "contraction-fix", context: "i think", typed: "itll work", expected: "it’ll work", half: "dev"),
    SymbolCase(id: "sym-053", sub: "contraction-fix", context: "yeah", typed: "thatll do", expected: "that’ll do", half: "dev"),
    SymbolCase(id: "sym-054", sub: "contraction-fix", context: "i", typed: "couldve sworn", expected: "could’ve sworn", half: "test"),
    SymbolCase(id: "sym-055", sub: "contraction-fix", context: "you", typed: "shouldve seen it", expected: "should’ve seen it", half: "dev"),
    SymbolCase(id: "sym-056", sub: "contraction-fix", context: "we", typed: "wouldve won", expected: "would’ve won", half: "dev"),
    SymbolCase(id: "sym-057", sub: "contraction-fix", context: "hey", typed: "yall", expected: "y’all", half: "dev"),
    SymbolCase(id: "sym-058", sub: "contraction-fix", context: "at 6", typed: "oclock", expected: "o’clock", half: "test"),
    SymbolCase(id: "sym-059", sub: "contraction-fix", context: "yes", typed: "maam", expected: "ma’am", half: "dev"),
    SymbolCase(id: "sym-060", sub: "contraction-ambiguous-no", context: "the old", typed: "well", expected: "well", half: "test"),
    SymbolCase(id: "sym-062", sub: "contraction-ambiguous-no", context: "oh", typed: "well", expected: "well", half: "dev"),
    SymbolCase(id: "sym-063", sub: "contraction-ambiguous-no", context: "it went really", typed: "well", expected: "well", half: "dev"),
    SymbolCase(id: "sym-064", sub: "contraction-ambiguous-no", context: "i feel", typed: "ill", expected: "ill", half: "test"),
    SymbolCase(id: "sym-067", sub: "contraction-ambiguous-no", context: "my", typed: "id", expected: "id", half: "dev"),
    SymbolCase(id: "sym-071", sub: "contraction-ambiguous-no", context: "what the", typed: "hell", expected: "hell", half: "test"),
    SymbolCase(id: "sym-074", sub: "contraction-ambiguous-no", context: "sea", typed: "shell", expected: "shell", half: "test"),
    SymbolCase(id: "sym-078", sub: "contraction-ambiguous-no", context: "we plan to", typed: "wed", expected: "wed", half: "test"),
    SymbolCase(id: "sym-080", sub: "contraction-ambiguous-no", context: "see you", typed: "Wed", expected: "Wed", half: "dev"),
    SymbolCase(id: "sym-081", sub: "contraction-ambiguous-no", context: "the dog wagged", typed: "its", expected: "its", half: "dev"),
    SymbolCase(id: "sym-084", sub: "contraction-ambiguous-no", context: "they", typed: "were", expected: "were", half: "dev"),
    SymbolCase(id: "sym-086", sub: "contraction-ambiguous-no", context: "the tool", typed: "shed", expected: "shed", half: "test"),
    SymbolCase(id: "sym-089", sub: "contraction-ambiguous-no", context: "Professor", typed: "Cant", expected: "Cant", half: "dev"),
    SymbolCase(id: "sym-093", sub: "contraction-ambiguous-no", context: "", typed: "IM me later", expected: "IM me later", half: "test"),
    SymbolCase(id: "sym-094", sub: "contraction-ambiguous-no", context: "go to", typed: "example.com/dont-panic", expected: "example.com/dont-panic", half: "dev"),
    SymbolCase(id: "sym-095", sub: "contraction-ambiguous-no", context: "email", typed: "dont.reply@shop.com", expected: "dont.reply@shop.com", half: "dev"),
    SymbolCase(id: "sym-096", sub: "contraction-ambiguous-no", context: "his handle is", typed: "@wasnt_me", expected: "@wasnt_me", half: "test"),
    SymbolCase(id: "sym-097", sub: "contraction-ambiguous-no", context: "", typed: "#cantstopwontstop", expected: "#cantstopwontstop", half: "test"),
    SymbolCase(id: "sym-098", sub: "quote-open", context: "", typed: "\"hello", expected: "“hello", half: "dev"),
    SymbolCase(id: "sym-100", sub: "quote-open", context: "she", typed: "said \"come over", expected: "said “come over", half: "dev"),
    SymbolCase(id: "sym-102", sub: "quote-open", context: "", typed: "(\"so called", expected: "(“so called", half: "dev"),
    SymbolCase(id: "sym-103", sub: "quote-open", context: "", typed: "[\"sic", expected: "[“sic", half: "dev"),
    SymbolCase(id: "sym-104", sub: "quote-open", context: "the sign read —", typed: "\"closed", expected: "“closed", half: "test"),
    SymbolCase(id: "sym-105", sub: "quote-open", context: "he texted", typed: "back: \"k", expected: "back: “k", half: "test"),
    SymbolCase(id: "sym-106", sub: "quote-open", context: "she", typed: "said, \"hi", expected: "said, “hi", half: "dev"),
    SymbolCase(id: "sym-107", sub: "quote-open", context: "the word", typed: "'moist' is gross", expected: "‘moist’ is gross", half: "dev"),
    SymbolCase(id: "sym-108", sub: "quote-open", context: "", typed: "('best' behavior)", expected: "(‘best’ behavior)", half: "test"),
    SymbolCase(id: "sym-109", sub: "quote-open", context: "", typed: "'quotes' are hard", expected: "‘quotes’ are hard", half: "test"),
    SymbolCase(id: "sym-110", sub: "quote-open", context: "my favorite word is", typed: "\"defenestration\"", expected: "“defenestration”", half: "test"),
    SymbolCase(id: "sym-111", sub: "quote-open", context: "", typed: "\"wait\" then \"go\"", expected: "“wait” then “go”", half: "test"),
    SymbolCase(id: "sym-113", sub: "quote-open", context: "", typed: "{\"id\": 1}", expected: "{\"id\": 1}", half: "dev"),
    SymbolCase(id: "sym-114", sub: "quote-open", context: "paste", typed: "curl -H \"Accept: text/html\"", expected: "curl -H \"Accept: text/html\"", half: "test"),
    SymbolCase(id: "sym-116", sub: "quote-close", context: "she said “come", typed: "over\"", expected: "over”", half: "dev"),
    SymbolCase(id: "sym-117", sub: "quote-close", context: "“no", typed: "way\"", expected: "way”", half: "dev"),
    SymbolCase(id: "sym-118", sub: "quote-close", context: "he said “k", typed: "\"", expected: "”", half: "test"),
    SymbolCase(id: "sym-119", sub: "quote-close", context: "she called it ‘art", typed: "'", expected: "’", half: "test"),
    SymbolCase(id: "sym-120", sub: "quote-close", context: "“stop", typed: "it\" pls", expected: "it” pls", half: "test"),
    SymbolCase(id: "sym-121", sub: "quote-close", context: "she yelled “wait", typed: "--\"", expected: "—”", half: "test"),
    SymbolCase(id: "sym-122", sub: "quote-close", context: "“i never", typed: "--\"", expected: "—”", half: "dev"),
    SymbolCase(id: "sym-123", sub: "quote-close", context: "“fine (i guess)", typed: "\"", expected: "”", half: "dev"),
    SymbolCase(id: "sym-124", sub: "quote-close", context: "it’s “fine", typed: "\" honestly", expected: "” honestly", half: "test"),
    SymbolCase(id: "sym-126", sub: "quote-close", context: "he said “brb", typed: "\" and left", expected: "” and left", half: "dev"),
    SymbolCase(id: "sym-127", sub: "quote-close", context: "my ‘so-called", typed: "' friends", expected: "’ friends", half: "dev"),
    SymbolCase(id: "sym-129", sub: "quote-close", context: "she said “i’m 25", typed: "\"", expected: "”", half: "test"),
    SymbolCase(id: "sym-132", sub: "quote-close", context: "“ok", typed: "\" she replied", expected: "” she replied", half: "dev"),
    SymbolCase(id: "sym-133", sub: "quote-close", context: "‘maybe", typed: "' idk", expected: "’ idk", half: "dev"),
    SymbolCase(id: "sym-135", sub: "quote-close", context: "that word ‘yeet", typed: "' again", expected: "’ again", half: "test"),
    SymbolCase(id: "sym-136", sub: "quote-after-punct", context: "she said “on my way", typed: ".\"", expected: ".”", half: "dev"),
    SymbolCase(id: "sym-137", sub: "quote-after-punct", context: "he asked “you coming", typed: "?\"", expected: "?”", half: "dev"),
    SymbolCase(id: "sym-138", sub: "quote-after-punct", context: "she yelled “stop", typed: "!\"", expected: "!”", half: "test"),
    SymbolCase(id: "sym-139", sub: "quote-after-punct", context: "“fine", typed: ",\" she said", expected: ",” she said", half: "test"),
    SymbolCase(id: "sym-140", sub: "quote-after-punct", context: "", typed: "Done. \"next\"", expected: "Done. “next”", half: "test"),
    SymbolCase(id: "sym-144", sub: "quote-after-punct", context: "‘done", typed: ".'", expected: ".’", half: "test"),
    SymbolCase(id: "sym-145", sub: "quote-after-punct", context: "she texted “omw", typed: "...\"", expected: "…”", half: "dev"),
    SymbolCase(id: "sym-146", sub: "quote-after-punct", context: "hold on", typed: "; \"sure\"", expected: "; “sure”", half: "dev"),
    SymbolCase(id: "sym-150", sub: "quote-nested", context: "she said “he calls it", typed: "'art'", expected: "‘art’", half: "test"),
    SymbolCase(id: "sym-151", sub: "quote-nested", context: "", typed: "\"a 'quick' fix\"", expected: "“a ‘quick’ fix”", half: "dev"),
    SymbolCase(id: "sym-153", sub: "quote-nested", context: "he wrote “call it ‘done", typed: "'\"", expected: "’”", half: "dev"),
    SymbolCase(id: "sym-154", sub: "quote-nested", context: "“it", typed: "'s fine\"", expected: "’s fine”", half: "test"),
    SymbolCase(id: "sym-156", sub: "quote-nested", context: "", typed: "'he said \"go\" i think'", expected: "‘he said “go” i think’", half: "dev"),
    SymbolCase(id: "sym-158", sub: "quote-nested", context: "“try 'restart", typed: "' first\"", expected: "’ first”", half: "test"),
    SymbolCase(id: "sym-159", sub: "quote-nested", context: "", typed: "\"rock 'n' roll\"", expected: "“rock ’n’ roll”", half: "dev"),
    SymbolCase(id: "sym-160", sub: "apostrophe-word-internal", context: "i", typed: "don't", expected: "don’t", half: "test"),
    SymbolCase(id: "sym-163", sub: "apostrophe-word-internal", context: "i think", typed: "it's", expected: "it’s", half: "dev"),
    SymbolCase(id: "sym-164", sub: "apostrophe-word-internal", context: "", typed: "I'm", expected: "I’m", half: "test"),
    SymbolCase(id: "sym-166", sub: "apostrophe-word-internal", context: "i", typed: "would've", expected: "would’ve", half: "dev"),
    SymbolCase(id: "sym-167", sub: "apostrophe-word-internal", context: "hey", typed: "y'all", expected: "y’all", half: "dev"),
    SymbolCase(id: "sym-169", sub: "apostrophe-word-internal", context: "at 7", typed: "o'clock", expected: "o’clock", half: "test"),
    SymbolCase(id: "sym-170", sub: "apostrophe-word-internal", context: "", typed: "rock 'n' roll", expected: "rock ’n’ roll", half: "test"),
    SymbolCase(id: "sym-171", sub: "apostrophe-word-internal", context: "met", typed: "O'Brien", expected: "O’Brien", half: "test"),
    SymbolCase(id: "sym-173", sub: "apostrophe-word-internal", context: "making", typed: "s'mores", expected: "s’mores", half: "dev"),
    SymbolCase(id: "sym-174", sub: "apostrophe-word-internal", context: "the", typed: "gov't", expected: "gov’t", half: "test"),
    SymbolCase(id: "sym-176", sub: "apostrophe-word-internal", context: "lol", typed: "how'd it go", expected: "how’d it go", half: "dev"),
    SymbolCase(id: "sym-180", sub: "apostrophe-word-internal", context: "i was", typed: "goin' home", expected: "goin’ home", half: "dev"),
    SymbolCase(id: "sym-184", sub: "apostrophe-decade", context: "music from the", typed: "'90s", expected: "’90s", half: "dev"),
    SymbolCase(id: "sym-187", sub: "apostrophe-decade", context: "", typed: "'90s kids remember", expected: "’90s kids remember", half: "test"),
    SymbolCase(id: "sym-188", sub: "apostrophe-decade", context: "class of", typed: "'09", expected: "’09", half: "dev"),
    SymbolCase(id: "sym-190", sub: "apostrophe-decade", context: "wait", typed: "'til tomorrow", expected: "’til tomorrow", half: "dev"),
    SymbolCase(id: "sym-191", sub: "apostrophe-decade", context: "get", typed: "'em", expected: "’em", half: "dev"),
    SymbolCase(id: "sym-192", sub: "apostrophe-decade", context: "just", typed: "'cause", expected: "’cause", half: "test"),
    SymbolCase(id: "sym-193", sub: "apostrophe-decade", context: "", typed: "'twas the night", expected: "’twas the night", half: "test"),
    SymbolCase(id: "sym-194", sub: "apostrophe-decade", context: "talk", typed: "'bout it", expected: "’bout it", half: "test"),
    SymbolCase(id: "sym-195", sub: "apostrophe-decade", context: "see you", typed: "'round", expected: "’round", half: "dev"),
    SymbolCase(id: "sym-196", sub: "prime-measurement", context: "he’s", typed: "5'10\"", expected: "5'10\"", half: "test"),
    SymbolCase(id: "sym-199", sub: "prime-measurement", context: "", typed: "6'2\"", expected: "6'2\"", half: "dev"),
    SymbolCase(id: "sym-200", sub: "prime-measurement", context: "the ceiling is", typed: "9'", expected: "9'", half: "dev"),
    SymbolCase(id: "sym-201", sub: "prime-measurement", context: "an", typed: "8' ladder", expected: "8' ladder", half: "test"),
    SymbolCase(id: "sym-202", sub: "prime-measurement", context: "a", typed: "32\" monitor", expected: "32\" monitor", half: "dev"),
    SymbolCase(id: "sym-204", sub: "prime-measurement", context: "", typed: "8.5\" x 11\" paper", expected: "8.5\" x 11\" paper", half: "dev"),
    SymbolCase(id: "sym-205", sub: "prime-measurement", context: "coordinates", typed: "40°26'46\"N", expected: "40°26'46\"N", half: "test"),
    SymbolCase(id: "sym-208", sub: "emdash", context: "", typed: "wait--what", expected: "wait—what", half: "dev"),
    SymbolCase(id: "sym-211", sub: "emdash", context: "i was", typed: "late -- again", expected: "late — again", half: "test"),
    SymbolCase(id: "sym-212", sub: "emdash", context: "", typed: "--and another thing", expected: "—and another thing", half: "dev"),
    SymbolCase(id: "sym-213", sub: "emdash", context: "one rule", typed: "--no phones", expected: "—no phones", half: "dev"),
    SymbolCase(id: "sym-214", sub: "emdash", context: "", typed: "she was--is--my best friend", expected: "she was—is—my best friend", half: "test"),
    SymbolCase(id: "sym-216", sub: "emdash", context: "run", typed: "npm install --save-dev", expected: "npm install --save-dev", half: "dev"),
    SymbolCase(id: "sym-217", sub: "emdash", context: "", typed: "git log --oneline", expected: "git log --oneline", half: "dev"),
    SymbolCase(id: "sym-218", sub: "emdash", context: "a", typed: "long-term plan", expected: "long-term plan", half: "test"),
    SymbolCase(id: "sym-219", sub: "emdash", context: "i’m", typed: "twenty-two", expected: "twenty-two", half: "test"),
    SymbolCase(id: "sym-220", sub: "emdash", context: "works", typed: "9-5", expected: "9-5", half: "test"),
    SymbolCase(id: "sym-221", sub: "emdash", context: "call", typed: "555-0192", expected: "555-0192", half: "test"),
    SymbolCase(id: "sym-222", sub: "emdash", context: "", typed: "---", expected: "---", half: "dev"),
    SymbolCase(id: "sym-224", sub: "ellipsis", context: "", typed: "idk...", expected: "idk…", half: "test"),
    SymbolCase(id: "sym-226", sub: "ellipsis", context: "", typed: "wait... what", expected: "wait… what", half: "dev"),
    SymbolCase(id: "sym-227", sub: "ellipsis", context: "", typed: "...ok then", expected: "…ok then", half: "dev"),
    SymbolCase(id: "sym-231", sub: "ellipsis", context: "", typed: "..", expected: "..", half: "test"),
    SymbolCase(id: "sym-232", sub: "ellipsis", context: "pages", typed: "1..10", expected: "1..10", half: "dev"),
    SymbolCase(id: "sym-233", sub: "ellipsis", context: "", typed: ". . .", expected: ". . .", half: "dev"),
    SymbolCase(id: "sym-234", sub: "ellipsis", context: "", typed: "ok..", expected: "ok..", half: "test"),
    SymbolCase(id: "sym-235", sub: "ellipsis", context: "version", typed: "1.2.3", expected: "1.2.3", half: "test"),
    SymbolCase(id: "sym-236", sub: "possessive-s", context: "", typed: "Jake's car", expected: "Jake’s car", half: "dev"),
    SymbolCase(id: "sym-237", sub: "possessive-s", context: "the", typed: "dog's bowl", expected: "dog’s bowl", half: "dev"),
    SymbolCase(id: "sym-238", sub: "possessive-s", context: "", typed: "James's idea", expected: "James’s idea", half: "test"),
    SymbolCase(id: "sym-240", sub: "possessive-s", context: "", typed: "everyone's invited", expected: "everyone’s invited", half: "test"),
    SymbolCase(id: "sym-242", sub: "possessive-s", context: "on", typed: "Chris' desk", expected: "Chris’ desk", half: "dev"),
    SymbolCase(id: "sym-243", sub: "possessive-s", context: "at the", typed: "kids' table", expected: "kids’ table", half: "dev"),
    SymbolCase(id: "sym-245", sub: "possessive-s", context: "lunch at", typed: "McDonald's", expected: "McDonald’s", half: "test"),
    SymbolCase(id: "sym-249", sub: "possessive-s", context: "", typed: "y'all's plans", expected: "y’all’s plans", half: "test"),
    SymbolCase(id: "sym-250", sub: "plural-not-possessive-no", context: "", typed: "three dogs", expected: "three dogs", half: "test"),
    SymbolCase(id: "sym-251", sub: "plural-not-possessive-no", context: "in the", typed: "1990s", expected: "1990s", half: "dev"),
    SymbolCase(id: "sym-252", sub: "plural-not-possessive-no", context: "burning", typed: "CDs", expected: "CDs", half: "dev"),
    SymbolCase(id: "sym-254", sub: "plural-not-possessive-no", context: "the", typed: "Smiths", expected: "Smiths", half: "test"),
]
