// GENERATED from eval/oracle/corpus/probes.tsv by
// eval/oracle/gen-probes.py -- do not hand-edit. Controlled probes
// of stock's autocorrect (specs/autocorrect-parity.md unit 0).

let oracleProbes: [OracleRow] = [
    OracleRow(id: "A-001", slice: "probes", typed: "heklo", offsets: []),
    OracleRow(id: "A-002", slice: "probes", typed: "hejlo", offsets: []),
    OracleRow(id: "A-003", slice: "probes", typed: "healo", offsets: []),
    OracleRow(id: "A-004", slice: "probes", typed: "wager", offsets: []),
    OracleRow(id: "A-005", slice: "probes", typed: "waeer", offsets: []),
    OracleRow(id: "A-006", slice: "probes", typed: "wamer", offsets: []),
    OracleRow(id: "A-007", slice: "probes", typed: "tajle", offsets: []),
    OracleRow(id: "A-008", slice: "probes", typed: "taule", offsets: []),
    OracleRow(id: "A-009", slice: "probes", typed: "taple", offsets: []),
    OracleRow(id: "A-010", slice: "probes", typed: "mokey", offsets: []),
    OracleRow(id: "A-011", slice: "probes", typed: "moiey", offsets: []),
    OracleRow(id: "A-012", slice: "probes", typed: "moqey", offsets: []),
    OracleRow(id: "A-013", slice: "probes", typed: "phine", offsets: []),
    OracleRow(id: "A-014", slice: "probes", typed: "phmne", offsets: []),
    OracleRow(id: "A-015", slice: "probes", typed: "phfne", offsets: []),
    OracleRow(id: "A-016", slice: "probes", typed: "hoise", offsets: []),
    OracleRow(id: "A-017", slice: "probes", typed: "honse", offsets: []),
    OracleRow(id: "A-018", slice: "probes", typed: "hoxse", offsets: []),
    OracleRow(id: "A-019", slice: "probes", typed: "niyht", offsets: []),
    OracleRow(id: "A-020", slice: "probes", typed: "nidht", offsets: []),
    OracleRow(id: "A-021", slice: "probes", typed: "nipht", offsets: []),
    OracleRow(id: "A-022", slice: "probes", typed: "mofie", offsets: []),
    OracleRow(id: "A-023", slice: "probes", typed: "moyie", offsets: []),
    OracleRow(id: "A-024", slice: "probes", typed: "molie", offsets: []),
    OracleRow(id: "A-025", slice: "probes", typed: "mueic", offsets: []),
    OracleRow(id: "A-026", slice: "probes", typed: "mufic", offsets: []),
    OracleRow(id: "A-027", slice: "probes", typed: "muoic", offsets: []),
    OracleRow(id: "A-028", slice: "probes", typed: "grren", offsets: []),
    OracleRow(id: "A-029", slice: "probes", typed: "grten", offsets: []),
    OracleRow(id: "A-030", slice: "probes", typed: "gruen", offsets: []),
    OracleRow(id: "A-031", slice: "probes", typed: "fisld", offsets: []),
    OracleRow(id: "A-032", slice: "probes", typed: "fixld", offsets: []),
    OracleRow(id: "A-033", slice: "probes", typed: "fibld", offsets: []),
    OracleRow(id: "A-034", slice: "probes", typed: "patty", offsets: []),
    OracleRow(id: "A-035", slice: "probes", typed: "payty", offsets: []),
    OracleRow(id: "A-036", slice: "probes", typed: "panty", offsets: []),
    OracleRow(id: "A-037", slice: "probes", typed: "sodry", offsets: []),
    OracleRow(id: "A-038", slice: "probes", typed: "socry", offsets: []),
    OracleRow(id: "A-039", slice: "probes", typed: "soory", offsets: []),
    OracleRow(id: "A-040", slice: "probes", typed: "haopy", offsets: []),
    OracleRow(id: "A-041", slice: "probes", typed: "haipy", offsets: []),
    OracleRow(id: "A-042", slice: "probes", typed: "haxpy", offsets: []),
    OracleRow(id: "A-043", slice: "probes", typed: "chsck", offsets: []),
    OracleRow(id: "A-044", slice: "probes", typed: "chxck", offsets: []),
    OracleRow(id: "A-045", slice: "probes", typed: "chlck", offsets: []),
    OracleRow(id: "A-046", slice: "probes", typed: "stzrt", offsets: []),
    OracleRow(id: "A-047", slice: "probes", typed: "stdrt", offsets: []),
    OracleRow(id: "A-048", slice: "probes", typed: "stgrt", offsets: []),
    OracleRow(id: "A-049", slice: "probes", typed: "dinher", offsets: []),
    OracleRow(id: "A-050", slice: "probes", typed: "dinuer", offsets: []),
    OracleRow(id: "A-051", slice: "probes", typed: "dinxer", offsets: []),
    OracleRow(id: "A-052", slice: "probes", typed: "flihht", offsets: []),
    OracleRow(id: "A-053", slice: "probes", typed: "flijht", offsets: []),
    OracleRow(id: "A-054", slice: "probes", typed: "flilht", offsets: []),
    OracleRow(id: "A-055", slice: "probes", typed: "coftee", offsets: []),
    OracleRow(id: "A-056", slice: "probes", typed: "cofhee", offsets: []),
    OracleRow(id: "A-057", slice: "probes", typed: "cofoee", offsets: []),
    OracleRow(id: "A-058", slice: "probes", typed: "morming", offsets: []),
    OracleRow(id: "A-059", slice: "probes", typed: "moruing", offsets: []),
    OracleRow(id: "A-060", slice: "probes", typed: "mording", offsets: []),
    OracleRow(id: "B-061", slice: "probes", typed: "bello", offsets: []),
    OracleRow(id: "B-062", slice: "probes", typed: "heklo", offsets: []),
    OracleRow(id: "B-063", slice: "probes", typed: "helli", offsets: []),
    OracleRow(id: "B-064", slice: "probes", typed: "eater", offsets: []),
    OracleRow(id: "B-065", slice: "probes", typed: "wager", offsets: []),
    OracleRow(id: "B-066", slice: "probes", typed: "watee", offsets: []),
    OracleRow(id: "B-067", slice: "probes", typed: "loney", offsets: []),
    OracleRow(id: "B-068", slice: "probes", typed: "mojey", offsets: []),
    OracleRow(id: "B-069", slice: "probes", typed: "monet", offsets: []),
    OracleRow(id: "B-070", slice: "probes", typed: "ohone", offsets: []),
    OracleRow(id: "B-071", slice: "probes", typed: "phpne", offsets: []),
    OracleRow(id: "B-072", slice: "probes", typed: "phonw", offsets: []),
    OracleRow(id: "B-073", slice: "probes", typed: "uouse", offsets: []),
    OracleRow(id: "B-074", slice: "probes", typed: "hohse", offsets: []),
    OracleRow(id: "B-075", slice: "probes", typed: "housd", offsets: []),
    OracleRow(id: "B-076", slice: "probes", typed: "bight", offsets: []),
    OracleRow(id: "B-077", slice: "probes", typed: "nivht", offsets: []),
    OracleRow(id: "B-078", slice: "probes", typed: "nighg", offsets: []),
    OracleRow(id: "B-079", slice: "probes", typed: "larty", offsets: []),
    OracleRow(id: "B-080", slice: "probes", typed: "pafty", offsets: []),
    OracleRow(id: "B-081", slice: "probes", typed: "partt", offsets: []),
    OracleRow(id: "B-082", slice: "probes", typed: "gheck", offsets: []),
    OracleRow(id: "B-083", slice: "probes", typed: "chwck", offsets: []),
    OracleRow(id: "B-084", slice: "probes", typed: "checj", offsets: []),
    OracleRow(id: "B-085", slice: "probes", typed: "voffee", offsets: []),
    OracleRow(id: "B-086", slice: "probes", typed: "cofdee", offsets: []),
    OracleRow(id: "B-087", slice: "probes", typed: "coffed", offsets: []),
    OracleRow(id: "B-088", slice: "probes", typed: "korning", offsets: []),
    OracleRow(id: "B-089", slice: "probes", typed: "morming", offsets: []),
    OracleRow(id: "B-090", slice: "probes", typed: "morninf", offsets: []),
    OracleRow(id: "C-091", slice: "probes", typed: "gello", offsets: []),
    OracleRow(id: "C-092", slice: "probes", typed: "geolo", offsets: []),
    OracleRow(id: "C-093", slice: "probes", typed: "geolp", offsets: []),
    OracleRow(id: "C-094", slice: "probes", typed: "qater", offsets: []),
    OracleRow(id: "C-095", slice: "probes", typed: "qayer", offsets: []),
    OracleRow(id: "C-096", slice: "probes", typed: "qayed", offsets: []),
    OracleRow(id: "C-097", slice: "probes", typed: "noney", offsets: []),
    OracleRow(id: "C-098", slice: "probes", typed: "nomey", offsets: []),
    OracleRow(id: "C-099", slice: "probes", typed: "nomeh", offsets: []),
    OracleRow(id: "C-100", slice: "probes", typed: "lhone", offsets: []),
    OracleRow(id: "C-101", slice: "probes", typed: "lhkne", offsets: []),
    OracleRow(id: "C-102", slice: "probes", typed: "lhkns", offsets: []),
    OracleRow(id: "C-103", slice: "probes", typed: "vouse", offsets: []),
    OracleRow(id: "C-104", slice: "probes", typed: "vojse", offsets: []),
    OracleRow(id: "C-105", slice: "probes", typed: "vojsw", offsets: []),
    OracleRow(id: "C-106", slice: "probes", typed: "hight", offsets: []),
    OracleRow(id: "C-107", slice: "probes", typed: "hibht", offsets: []),
    OracleRow(id: "C-108", slice: "probes", typed: "hibhf", offsets: []),
    OracleRow(id: "C-109", slice: "probes", typed: "oarty", offsets: []),
    OracleRow(id: "C-110", slice: "probes", typed: "oadty", offsets: []),
    OracleRow(id: "C-111", slice: "probes", typed: "oadth", offsets: []),
    OracleRow(id: "C-112", slice: "probes", typed: "vheck", offsets: []),
    OracleRow(id: "C-113", slice: "probes", typed: "vhrck", offsets: []),
    OracleRow(id: "C-114", slice: "probes", typed: "vhrcn", offsets: []),
    OracleRow(id: "C-115", slice: "probes", typed: "xoffee", offsets: []),
    OracleRow(id: "C-116", slice: "probes", typed: "xorfee", offsets: []),
    OracleRow(id: "C-117", slice: "probes", typed: "xorfwe", offsets: []),
    OracleRow(id: "C-118", slice: "probes", typed: "lorning", offsets: []),
    OracleRow(id: "C-119", slice: "probes", typed: "lotning", offsets: []),
    OracleRow(id: "C-120", slice: "probes", typed: "lotnjng", offsets: []),
    OracleRow(id: "D-121", slice: "probes", typed: "cqt", offsets: []),
    OracleRow(id: "D-122", slice: "probes", typed: "dkg", offsets: []),
    OracleRow(id: "D-123", slice: "probes", typed: "rjn", offsets: []),
    OracleRow(id: "D-124", slice: "probes", typed: "bys", offsets: []),
    OracleRow(id: "D-125", slice: "probes", typed: "plqne", offsets: []),
    OracleRow(id: "D-126", slice: "probes", typed: "chsir", offsets: []),
    OracleRow(id: "D-127", slice: "probes", typed: "brsad", offsets: []),
    OracleRow(id: "D-128", slice: "probes", typed: "smule", offsets: []),
    OracleRow(id: "D-129", slice: "probes", typed: "birtbday", offsets: []),
    OracleRow(id: "D-130", slice: "probes", typed: "hospktal", offsets: []),
    OracleRow(id: "D-131", slice: "probes", typed: "compjter", offsets: []),
    OracleRow(id: "D-132", slice: "probes", typed: "sandsich", offsets: []),
    OracleRow(id: "E-133", slice: "probes", typed: "heklo", offsets: []),
    OracleRow(id: "E-134", slice: "probes", typed: "helo", offsets: []),
    OracleRow(id: "E-135", slice: "probes", typed: "helllo", offsets: []),
    OracleRow(id: "E-136", slice: "probes", typed: "wager", offsets: []),
    OracleRow(id: "E-137", slice: "probes", typed: "waetr", offsets: []),
    OracleRow(id: "E-138", slice: "probes", typed: "waer", offsets: []),
    OracleRow(id: "E-139", slice: "probes", typed: "watter", offsets: []),
    OracleRow(id: "E-140", slice: "probes", typed: "mojey", offsets: []),
    OracleRow(id: "E-141", slice: "probes", typed: "moeny", offsets: []),
    OracleRow(id: "E-142", slice: "probes", typed: "moey", offsets: []),
    OracleRow(id: "E-143", slice: "probes", typed: "monney", offsets: []),
    OracleRow(id: "E-144", slice: "probes", typed: "phpne", offsets: []),
    OracleRow(id: "E-145", slice: "probes", typed: "phnoe", offsets: []),
    OracleRow(id: "E-146", slice: "probes", typed: "phne", offsets: []),
    OracleRow(id: "E-147", slice: "probes", typed: "phoone", offsets: []),
    OracleRow(id: "E-148", slice: "probes", typed: "hohse", offsets: []),
    OracleRow(id: "E-149", slice: "probes", typed: "hosue", offsets: []),
    OracleRow(id: "E-150", slice: "probes", typed: "hose", offsets: []),
    OracleRow(id: "E-151", slice: "probes", typed: "houuse", offsets: []),
    OracleRow(id: "E-152", slice: "probes", typed: "nivht", offsets: []),
    OracleRow(id: "E-153", slice: "probes", typed: "nihgt", offsets: []),
    OracleRow(id: "E-154", slice: "probes", typed: "niht", offsets: []),
    OracleRow(id: "E-155", slice: "probes", typed: "nigght", offsets: []),
    OracleRow(id: "E-156", slice: "probes", typed: "pafty", offsets: []),
    OracleRow(id: "E-157", slice: "probes", typed: "patry", offsets: []),
    OracleRow(id: "E-158", slice: "probes", typed: "paty", offsets: []),
    OracleRow(id: "E-159", slice: "probes", typed: "parrty", offsets: []),
    OracleRow(id: "E-160", slice: "probes", typed: "chwck", offsets: []),
    OracleRow(id: "E-161", slice: "probes", typed: "chcek", offsets: []),
    OracleRow(id: "E-162", slice: "probes", typed: "chck", offsets: []),
    OracleRow(id: "E-163", slice: "probes", typed: "cheeck", offsets: []),
    OracleRow(id: "E-164", slice: "probes", typed: "cofdee", offsets: []),
    OracleRow(id: "E-165", slice: "probes", typed: "cofefe", offsets: []),
    OracleRow(id: "E-166", slice: "probes", typed: "cofee", offsets: []),
    OracleRow(id: "E-167", slice: "probes", typed: "cofffee", offsets: []),
    OracleRow(id: "E-168", slice: "probes", typed: "morming", offsets: []),
    OracleRow(id: "E-169", slice: "probes", typed: "morinng", offsets: []),
    OracleRow(id: "E-170", slice: "probes", typed: "moring", offsets: []),
    OracleRow(id: "E-171", slice: "probes", typed: "mornning", offsets: []),
    OracleRow(id: "F-172", slice: "probes", typed: "wafer", offsets: []),
    OracleRow(id: "F-173", slice: "probes", typed: "can i have some wafer please", offsets: []),
    OracleRow(id: "F-174", slice: "probes", typed: "phkne", offsets: []),
    OracleRow(id: "F-175", slice: "probes", typed: "i left my phkne at home", offsets: []),
    OracleRow(id: "F-176", slice: "probes", typed: "nifht", offsets: []),
    OracleRow(id: "F-177", slice: "probes", typed: "see you tomorrow nifht then", offsets: []),
    OracleRow(id: "F-178", slice: "probes", typed: "chwck", offsets: []),
    OracleRow(id: "F-179", slice: "probes", typed: "let me chwck the time", offsets: []),
    OracleRow(id: "F-180", slice: "probes", typed: "coftee", offsets: []),
    OracleRow(id: "F-181", slice: "probes", typed: "i need more coftee now", offsets: []),
]

let oracleCarrierProbes: [OracleRow] = [
    OracleRow(id: "Ac-001", slice: "carrier", typed: "i said heklo to him", offsets: []),
    OracleRow(id: "Ac-002", slice: "carrier", typed: "i said hejlo to him", offsets: []),
    OracleRow(id: "Ac-003", slice: "carrier", typed: "i said healo to him", offsets: []),
    OracleRow(id: "Ac-004", slice: "carrier", typed: "i said wager to him", offsets: []),
    OracleRow(id: "Ac-005", slice: "carrier", typed: "i said waeer to him", offsets: []),
    OracleRow(id: "Ac-006", slice: "carrier", typed: "i said wamer to him", offsets: []),
    OracleRow(id: "Ac-007", slice: "carrier", typed: "i said tajle to him", offsets: []),
    OracleRow(id: "Ac-008", slice: "carrier", typed: "i said taule to him", offsets: []),
    OracleRow(id: "Ac-009", slice: "carrier", typed: "i said taple to him", offsets: []),
    OracleRow(id: "Ac-010", slice: "carrier", typed: "i said mokey to him", offsets: []),
    OracleRow(id: "Ac-011", slice: "carrier", typed: "i said moiey to him", offsets: []),
    OracleRow(id: "Ac-012", slice: "carrier", typed: "i said moqey to him", offsets: []),
    OracleRow(id: "Ac-013", slice: "carrier", typed: "i said phine to him", offsets: []),
    OracleRow(id: "Ac-014", slice: "carrier", typed: "i said phmne to him", offsets: []),
    OracleRow(id: "Ac-015", slice: "carrier", typed: "i said phfne to him", offsets: []),
    OracleRow(id: "Ac-016", slice: "carrier", typed: "i said hoise to him", offsets: []),
    OracleRow(id: "Ac-017", slice: "carrier", typed: "i said honse to him", offsets: []),
    OracleRow(id: "Ac-018", slice: "carrier", typed: "i said hoxse to him", offsets: []),
    OracleRow(id: "Ac-019", slice: "carrier", typed: "i said niyht to him", offsets: []),
    OracleRow(id: "Ac-020", slice: "carrier", typed: "i said nidht to him", offsets: []),
    OracleRow(id: "Ac-021", slice: "carrier", typed: "i said nipht to him", offsets: []),
    OracleRow(id: "Ac-022", slice: "carrier", typed: "i said mofie to him", offsets: []),
    OracleRow(id: "Ac-023", slice: "carrier", typed: "i said moyie to him", offsets: []),
    OracleRow(id: "Ac-024", slice: "carrier", typed: "i said molie to him", offsets: []),
    OracleRow(id: "Ac-025", slice: "carrier", typed: "i said mueic to him", offsets: []),
    OracleRow(id: "Ac-026", slice: "carrier", typed: "i said mufic to him", offsets: []),
    OracleRow(id: "Ac-027", slice: "carrier", typed: "i said muoic to him", offsets: []),
    OracleRow(id: "Ac-028", slice: "carrier", typed: "i said grren to him", offsets: []),
    OracleRow(id: "Ac-029", slice: "carrier", typed: "i said grten to him", offsets: []),
    OracleRow(id: "Ac-030", slice: "carrier", typed: "i said gruen to him", offsets: []),
    OracleRow(id: "Ac-031", slice: "carrier", typed: "i said fisld to him", offsets: []),
    OracleRow(id: "Ac-032", slice: "carrier", typed: "i said fixld to him", offsets: []),
    OracleRow(id: "Ac-033", slice: "carrier", typed: "i said fibld to him", offsets: []),
    OracleRow(id: "Ac-034", slice: "carrier", typed: "i said patty to him", offsets: []),
    OracleRow(id: "Ac-035", slice: "carrier", typed: "i said payty to him", offsets: []),
    OracleRow(id: "Ac-036", slice: "carrier", typed: "i said panty to him", offsets: []),
    OracleRow(id: "Ac-037", slice: "carrier", typed: "i said sodry to him", offsets: []),
    OracleRow(id: "Ac-038", slice: "carrier", typed: "i said socry to him", offsets: []),
    OracleRow(id: "Ac-039", slice: "carrier", typed: "i said soory to him", offsets: []),
    OracleRow(id: "Ac-040", slice: "carrier", typed: "i said haopy to him", offsets: []),
    OracleRow(id: "Ac-041", slice: "carrier", typed: "i said haipy to him", offsets: []),
    OracleRow(id: "Ac-042", slice: "carrier", typed: "i said haxpy to him", offsets: []),
    OracleRow(id: "Ac-043", slice: "carrier", typed: "i said chsck to him", offsets: []),
    OracleRow(id: "Ac-044", slice: "carrier", typed: "i said chxck to him", offsets: []),
    OracleRow(id: "Ac-045", slice: "carrier", typed: "i said chlck to him", offsets: []),
    OracleRow(id: "Ac-046", slice: "carrier", typed: "i said stzrt to him", offsets: []),
    OracleRow(id: "Ac-047", slice: "carrier", typed: "i said stdrt to him", offsets: []),
    OracleRow(id: "Ac-048", slice: "carrier", typed: "i said stgrt to him", offsets: []),
    OracleRow(id: "Ac-049", slice: "carrier", typed: "i said dinher to him", offsets: []),
    OracleRow(id: "Ac-050", slice: "carrier", typed: "i said dinuer to him", offsets: []),
    OracleRow(id: "Ac-051", slice: "carrier", typed: "i said dinxer to him", offsets: []),
    OracleRow(id: "Ac-052", slice: "carrier", typed: "i said flihht to him", offsets: []),
    OracleRow(id: "Ac-053", slice: "carrier", typed: "i said flijht to him", offsets: []),
    OracleRow(id: "Ac-054", slice: "carrier", typed: "i said flilht to him", offsets: []),
    OracleRow(id: "Ac-055", slice: "carrier", typed: "i said coftee to him", offsets: []),
    OracleRow(id: "Ac-056", slice: "carrier", typed: "i said cofhee to him", offsets: []),
    OracleRow(id: "Ac-057", slice: "carrier", typed: "i said cofoee to him", offsets: []),
    OracleRow(id: "Ac-058", slice: "carrier", typed: "i said morming to him", offsets: []),
    OracleRow(id: "Ac-059", slice: "carrier", typed: "i said moruing to him", offsets: []),
    OracleRow(id: "Ac-060", slice: "carrier", typed: "i said mording to him", offsets: []),
    OracleRow(id: "Bc-061", slice: "carrier", typed: "i said bello to him", offsets: []),
    OracleRow(id: "Bc-062", slice: "carrier", typed: "i said heklo to him", offsets: []),
    OracleRow(id: "Bc-063", slice: "carrier", typed: "i said helli to him", offsets: []),
    OracleRow(id: "Bc-064", slice: "carrier", typed: "i said eater to him", offsets: []),
    OracleRow(id: "Bc-065", slice: "carrier", typed: "i said wager to him", offsets: []),
    OracleRow(id: "Bc-066", slice: "carrier", typed: "i said watee to him", offsets: []),
    OracleRow(id: "Bc-067", slice: "carrier", typed: "i said loney to him", offsets: []),
    OracleRow(id: "Bc-068", slice: "carrier", typed: "i said mojey to him", offsets: []),
    OracleRow(id: "Bc-069", slice: "carrier", typed: "i said monet to him", offsets: []),
    OracleRow(id: "Bc-070", slice: "carrier", typed: "i said ohone to him", offsets: []),
    OracleRow(id: "Bc-071", slice: "carrier", typed: "i said phpne to him", offsets: []),
    OracleRow(id: "Bc-072", slice: "carrier", typed: "i said phonw to him", offsets: []),
    OracleRow(id: "Bc-073", slice: "carrier", typed: "i said uouse to him", offsets: []),
    OracleRow(id: "Bc-074", slice: "carrier", typed: "i said hohse to him", offsets: []),
    OracleRow(id: "Bc-075", slice: "carrier", typed: "i said housd to him", offsets: []),
    OracleRow(id: "Bc-076", slice: "carrier", typed: "i said bight to him", offsets: []),
    OracleRow(id: "Bc-077", slice: "carrier", typed: "i said nivht to him", offsets: []),
    OracleRow(id: "Bc-078", slice: "carrier", typed: "i said nighg to him", offsets: []),
    OracleRow(id: "Bc-079", slice: "carrier", typed: "i said larty to him", offsets: []),
    OracleRow(id: "Bc-080", slice: "carrier", typed: "i said pafty to him", offsets: []),
    OracleRow(id: "Bc-081", slice: "carrier", typed: "i said partt to him", offsets: []),
    OracleRow(id: "Bc-082", slice: "carrier", typed: "i said gheck to him", offsets: []),
    OracleRow(id: "Bc-083", slice: "carrier", typed: "i said chwck to him", offsets: []),
    OracleRow(id: "Bc-084", slice: "carrier", typed: "i said checj to him", offsets: []),
    OracleRow(id: "Bc-085", slice: "carrier", typed: "i said voffee to him", offsets: []),
    OracleRow(id: "Bc-086", slice: "carrier", typed: "i said cofdee to him", offsets: []),
    OracleRow(id: "Bc-087", slice: "carrier", typed: "i said coffed to him", offsets: []),
    OracleRow(id: "Bc-088", slice: "carrier", typed: "i said korning to him", offsets: []),
    OracleRow(id: "Bc-089", slice: "carrier", typed: "i said morming to him", offsets: []),
    OracleRow(id: "Bc-090", slice: "carrier", typed: "i said morninf to him", offsets: []),
    OracleRow(id: "Cc-091", slice: "carrier", typed: "i said gello to him", offsets: []),
    OracleRow(id: "Cc-092", slice: "carrier", typed: "i said geolo to him", offsets: []),
    OracleRow(id: "Cc-093", slice: "carrier", typed: "i said geolp to him", offsets: []),
    OracleRow(id: "Cc-094", slice: "carrier", typed: "i said qater to him", offsets: []),
    OracleRow(id: "Cc-095", slice: "carrier", typed: "i said qayer to him", offsets: []),
    OracleRow(id: "Cc-096", slice: "carrier", typed: "i said qayed to him", offsets: []),
    OracleRow(id: "Cc-097", slice: "carrier", typed: "i said noney to him", offsets: []),
    OracleRow(id: "Cc-098", slice: "carrier", typed: "i said nomey to him", offsets: []),
    OracleRow(id: "Cc-099", slice: "carrier", typed: "i said nomeh to him", offsets: []),
    OracleRow(id: "Cc-100", slice: "carrier", typed: "i said lhone to him", offsets: []),
    OracleRow(id: "Cc-101", slice: "carrier", typed: "i said lhkne to him", offsets: []),
    OracleRow(id: "Cc-102", slice: "carrier", typed: "i said lhkns to him", offsets: []),
    OracleRow(id: "Cc-103", slice: "carrier", typed: "i said vouse to him", offsets: []),
    OracleRow(id: "Cc-104", slice: "carrier", typed: "i said vojse to him", offsets: []),
    OracleRow(id: "Cc-105", slice: "carrier", typed: "i said vojsw to him", offsets: []),
    OracleRow(id: "Cc-106", slice: "carrier", typed: "i said hight to him", offsets: []),
    OracleRow(id: "Cc-107", slice: "carrier", typed: "i said hibht to him", offsets: []),
    OracleRow(id: "Cc-108", slice: "carrier", typed: "i said hibhf to him", offsets: []),
    OracleRow(id: "Cc-109", slice: "carrier", typed: "i said oarty to him", offsets: []),
    OracleRow(id: "Cc-110", slice: "carrier", typed: "i said oadty to him", offsets: []),
    OracleRow(id: "Cc-111", slice: "carrier", typed: "i said oadth to him", offsets: []),
    OracleRow(id: "Cc-112", slice: "carrier", typed: "i said vheck to him", offsets: []),
    OracleRow(id: "Cc-113", slice: "carrier", typed: "i said vhrck to him", offsets: []),
    OracleRow(id: "Cc-114", slice: "carrier", typed: "i said vhrcn to him", offsets: []),
    OracleRow(id: "Cc-115", slice: "carrier", typed: "i said xoffee to him", offsets: []),
    OracleRow(id: "Cc-116", slice: "carrier", typed: "i said xorfee to him", offsets: []),
    OracleRow(id: "Cc-117", slice: "carrier", typed: "i said xorfwe to him", offsets: []),
    OracleRow(id: "Cc-118", slice: "carrier", typed: "i said lorning to him", offsets: []),
    OracleRow(id: "Cc-119", slice: "carrier", typed: "i said lotning to him", offsets: []),
    OracleRow(id: "Cc-120", slice: "carrier", typed: "i said lotnjng to him", offsets: []),
    OracleRow(id: "Dc-121", slice: "carrier", typed: "i said cqt to him", offsets: []),
    OracleRow(id: "Dc-122", slice: "carrier", typed: "i said dkg to him", offsets: []),
    OracleRow(id: "Dc-123", slice: "carrier", typed: "i said rjn to him", offsets: []),
    OracleRow(id: "Dc-124", slice: "carrier", typed: "i said bys to him", offsets: []),
    OracleRow(id: "Dc-125", slice: "carrier", typed: "i said plqne to him", offsets: []),
    OracleRow(id: "Dc-126", slice: "carrier", typed: "i said chsir to him", offsets: []),
    OracleRow(id: "Dc-127", slice: "carrier", typed: "i said brsad to him", offsets: []),
    OracleRow(id: "Dc-128", slice: "carrier", typed: "i said smule to him", offsets: []),
    OracleRow(id: "Dc-129", slice: "carrier", typed: "i said birtbday to him", offsets: []),
    OracleRow(id: "Dc-130", slice: "carrier", typed: "i said hospktal to him", offsets: []),
    OracleRow(id: "Dc-131", slice: "carrier", typed: "i said compjter to him", offsets: []),
    OracleRow(id: "Dc-132", slice: "carrier", typed: "i said sandsich to him", offsets: []),
    OracleRow(id: "Ec-133", slice: "carrier", typed: "i said heklo to him", offsets: []),
    OracleRow(id: "Ec-134", slice: "carrier", typed: "i said helo to him", offsets: []),
    OracleRow(id: "Ec-135", slice: "carrier", typed: "i said helllo to him", offsets: []),
    OracleRow(id: "Ec-136", slice: "carrier", typed: "i said wager to him", offsets: []),
    OracleRow(id: "Ec-137", slice: "carrier", typed: "i said waetr to him", offsets: []),
    OracleRow(id: "Ec-138", slice: "carrier", typed: "i said waer to him", offsets: []),
    OracleRow(id: "Ec-139", slice: "carrier", typed: "i said watter to him", offsets: []),
    OracleRow(id: "Ec-140", slice: "carrier", typed: "i said mojey to him", offsets: []),
    OracleRow(id: "Ec-141", slice: "carrier", typed: "i said moeny to him", offsets: []),
    OracleRow(id: "Ec-142", slice: "carrier", typed: "i said moey to him", offsets: []),
    OracleRow(id: "Ec-143", slice: "carrier", typed: "i said monney to him", offsets: []),
    OracleRow(id: "Ec-144", slice: "carrier", typed: "i said phpne to him", offsets: []),
    OracleRow(id: "Ec-145", slice: "carrier", typed: "i said phnoe to him", offsets: []),
    OracleRow(id: "Ec-146", slice: "carrier", typed: "i said phne to him", offsets: []),
    OracleRow(id: "Ec-147", slice: "carrier", typed: "i said phoone to him", offsets: []),
    OracleRow(id: "Ec-148", slice: "carrier", typed: "i said hohse to him", offsets: []),
    OracleRow(id: "Ec-149", slice: "carrier", typed: "i said hosue to him", offsets: []),
    OracleRow(id: "Ec-150", slice: "carrier", typed: "i said hose to him", offsets: []),
    OracleRow(id: "Ec-151", slice: "carrier", typed: "i said houuse to him", offsets: []),
    OracleRow(id: "Ec-152", slice: "carrier", typed: "i said nivht to him", offsets: []),
    OracleRow(id: "Ec-153", slice: "carrier", typed: "i said nihgt to him", offsets: []),
    OracleRow(id: "Ec-154", slice: "carrier", typed: "i said niht to him", offsets: []),
    OracleRow(id: "Ec-155", slice: "carrier", typed: "i said nigght to him", offsets: []),
    OracleRow(id: "Ec-156", slice: "carrier", typed: "i said pafty to him", offsets: []),
    OracleRow(id: "Ec-157", slice: "carrier", typed: "i said patry to him", offsets: []),
    OracleRow(id: "Ec-158", slice: "carrier", typed: "i said paty to him", offsets: []),
    OracleRow(id: "Ec-159", slice: "carrier", typed: "i said parrty to him", offsets: []),
    OracleRow(id: "Ec-160", slice: "carrier", typed: "i said chwck to him", offsets: []),
    OracleRow(id: "Ec-161", slice: "carrier", typed: "i said chcek to him", offsets: []),
    OracleRow(id: "Ec-162", slice: "carrier", typed: "i said chck to him", offsets: []),
    OracleRow(id: "Ec-163", slice: "carrier", typed: "i said cheeck to him", offsets: []),
    OracleRow(id: "Ec-164", slice: "carrier", typed: "i said cofdee to him", offsets: []),
    OracleRow(id: "Ec-165", slice: "carrier", typed: "i said cofefe to him", offsets: []),
    OracleRow(id: "Ec-166", slice: "carrier", typed: "i said cofee to him", offsets: []),
    OracleRow(id: "Ec-167", slice: "carrier", typed: "i said cofffee to him", offsets: []),
    OracleRow(id: "Ec-168", slice: "carrier", typed: "i said morming to him", offsets: []),
    OracleRow(id: "Ec-169", slice: "carrier", typed: "i said morinng to him", offsets: []),
    OracleRow(id: "Ec-170", slice: "carrier", typed: "i said moring to him", offsets: []),
    OracleRow(id: "Ec-171", slice: "carrier", typed: "i said mornning to him", offsets: []),
    OracleRow(id: "Fc-172", slice: "carrier", typed: "i said wafer to him", offsets: []),
    OracleRow(id: "Fc-173", slice: "carrier", typed: "i said can i have some wafer please to him", offsets: []),
    OracleRow(id: "Fc-174", slice: "carrier", typed: "i said phkne to him", offsets: []),
    OracleRow(id: "Fc-175", slice: "carrier", typed: "i said i left my phkne at home to him", offsets: []),
    OracleRow(id: "Fc-176", slice: "carrier", typed: "i said nifht to him", offsets: []),
    OracleRow(id: "Fc-177", slice: "carrier", typed: "i said see you tomorrow nifht then to him", offsets: []),
    OracleRow(id: "Fc-178", slice: "carrier", typed: "i said chwck to him", offsets: []),
    OracleRow(id: "Fc-179", slice: "carrier", typed: "i said let me chwck the time to him", offsets: []),
    OracleRow(id: "Fc-180", slice: "carrier", typed: "i said coftee to him", offsets: []),
    OracleRow(id: "Fc-181", slice: "carrier", typed: "i said i need more coftee now to him", offsets: []),
]
